const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

const controller = fs.readFileSync('src/analytics/analytics.controller.ts', 'utf8');
const service = fs.readFileSync('src/analytics/analytics.service.ts', 'utf8');
const repository = fs.readFileSync('src/analytics/repositories/analytics.repository.ts', 'utf8');
const rollup = fs.readFileSync('src/analytics/jobs/analytics-rollup.job.ts', 'utf8');
const domain = fs.readFileSync('src/analytics/analytics-domain-event.ts', 'utf8');
const leads = fs.readFileSync('src/leads/leads.service.ts', 'utf8');
const distribution = fs.readFileSync('src/distribution/distribution.service.ts', 'utf8');

const count = (text, pattern) => (text.match(new RegExp(pattern, 'g')) || []).length;

class AnalyticsHarness {
  constructor() { this.events = []; this.daily = new Map(); this.hourly = new Map(); this.campaign = new Map(); this.whatsapp = new Map(); this.broker = new Map(); }
  record(event) { if (!domain.includes(`'${event.eventType}'`)) throw new Error('Evento de analytics inválido'); const key = `${event.organizationId}:${event.idempotencyKey}`; if (this.events.find((item) => `${item.organizationId}:${item.idempotencyKey}` === key)) return { duplicate: true }; this.events.push({ ...event, processedAt: null }); return event; }
  overview(org) { return [...this.daily.values()].filter((row) => row.organizationId === org).reduce((total, row) => ({ leads: total.leads + row.leads, campaigns: total.campaigns + row.campaigns, distributions: total.distributions + row.distributions, whatsappSent: total.whatsappSent + row.whatsappSent, whatsappRead: total.whatsappRead + row.whatsappRead, conversions: total.conversions + row.conversions }), { leads: 0, campaigns: 0, distributions: 0, whatsappSent: 0, whatsappRead: 0, conversions: 0 }); }
  processNext(fail = false) { const event = this.events.find((item) => !item.processedAt); if (!event) return false; if (fail) throw new Error('rollup failed'); this.apply(event); event.processedAt = new Date(); return true; }
  apply(event) { const day = event.occurredAt.toISOString().slice(0, 10); const dailyKey = `${event.organizationId}:${day}`; const daily = this.daily.get(dailyKey) || { organizationId: event.organizationId, leads: 0, campaigns: 0, distributions: 0, whatsappSent: 0, whatsappRead: 0, conversions: 0 }; if (event.eventType === 'LEAD_CREATED') daily.leads++; if (event.eventType === 'MESSAGE_SENT') daily.whatsappSent++; if (event.eventType === 'MESSAGE_READ') daily.whatsappRead++; if (event.eventType === 'DISTRIBUTION_ASSIGNED') daily.distributions++; if (event.eventType === 'DEAL_WON') daily.conversions++; this.daily.set(dailyKey, daily); if (event.eventType === 'LEAD_CREATED') this.hourly.set(`${event.organizationId}:${event.occurredAt.toISOString().slice(0, 13)}`, true); if (event.campaignId && event.eventType === 'MESSAGE_SENT') this.inc(this.campaign, `${event.organizationId}:${event.campaignId}`, 'sent'); if (event.campaignId && event.eventType === 'MESSAGE_READ') this.inc(this.campaign, `${event.organizationId}:${event.campaignId}`, 'opened'); if (event.whatsappAccountId && event.eventType === 'MESSAGE_SENT') this.inc(this.whatsapp, `${event.organizationId}:${event.whatsappAccountId}`, 'sent'); if (event.whatsappAccountId && event.eventType === 'MESSAGE_READ') this.inc(this.whatsapp, `${event.organizationId}:${event.whatsappAccountId}`, 'read'); if (event.brokerUserId && event.eventType === 'DISTRIBUTION_ASSIGNED') this.inc(this.broker, `${event.organizationId}:${event.brokerUserId}`, 'assignedLeads'); if (event.brokerUserId && event.eventType === 'DEAL_WON') this.inc(this.broker, `${event.organizationId}:${event.brokerUserId}`, 'wonDeals'); if (event.brokerUserId && event.eventType === 'DEAL_LOST') this.inc(this.broker, `${event.organizationId}:${event.brokerUserId}`, 'lostDeals'); }
  inc(map, key, field) { const row = map.get(key) || {}; row[field] = (row[field] || 0) + 1; map.set(key, row); }
}

test('AnalyticsController has exactly one route of each expected type', () => { assert.equal(count(controller, '@Get\\('), 7); assert.equal(count(controller, '@Post\\('), 1); ['overview', 'daily', 'hourly', 'campaigns', 'brokers', 'managers', 'whatsapp', 'events'].forEach((route) => assert.ok(controller.includes(`'${route}'`))); });
test('valid event is persisted and invalid event is rejected', () => { const h = new AnalyticsHarness(); assert.equal(h.record({ organizationId: 'org-1', eventType: 'LEAD_CREATED', idempotencyKey: 'lead-created:1', occurredAt: new Date() }).eventType, 'LEAD_CREATED'); assert.throws(() => h.record({ organizationId: 'org-1', eventType: 'BAD', idempotencyKey: 'bad', occurredAt: new Date() }), /Evento de analytics inválido/); });
test('duplicate idempotency is ignored without failing operational flow', () => { const h = new AnalyticsHarness(); const event = { organizationId: 'org-1', eventType: 'LEAD_CREATED', idempotencyKey: 'same', occurredAt: new Date() }; h.record(event); assert.deepEqual(h.record(event), { duplicate: true }); });
test('organization isolation and broker self-scope are present in service code', () => { assert.match(service, /organizationId !== ctx\.organizationId/); assert.match(service, /Role\.BROKER/); assert.match(service, /brokerUserId !== ctx\.id/); });
test('overview sums only aggregated daily metrics', () => { const h = new AnalyticsHarness(); h.record({ organizationId: 'org-1', eventType: 'LEAD_CREATED', idempotencyKey: '1', occurredAt: new Date() }); h.record({ organizationId: 'org-2', eventType: 'LEAD_CREATED', idempotencyKey: '2', occurredAt: new Date() }); h.processNext(); h.processNext(); assert.equal(h.overview('org-1').leads, 1); });
test('LEAD_CREATED increments daily and hourly', () => { const h = new AnalyticsHarness(); h.record({ organizationId: 'org-1', eventType: 'LEAD_CREATED', idempotencyKey: 'lead', occurredAt: new Date() }); h.processNext(); assert.equal(h.overview('org-1').leads, 1); assert.equal(h.hourly.size, 1); });
test('MESSAGE_SENT increments daily campaign and whatsapp when ids exist', () => { const h = new AnalyticsHarness(); h.record({ organizationId: 'org-1', eventType: 'MESSAGE_SENT', idempotencyKey: 'msg', occurredAt: new Date(), campaignId: 'camp-1', whatsappAccountId: 'wa-1' }); h.processNext(); assert.equal(h.overview('org-1').whatsappSent, 1); assert.equal(h.campaign.get('org-1:camp-1').sent, 1); assert.equal(h.whatsapp.get('org-1:wa-1').sent, 1); });
test('MESSAGE_READ increments read and opened metrics', () => { const h = new AnalyticsHarness(); h.record({ organizationId: 'org-1', eventType: 'MESSAGE_READ', idempotencyKey: 'read', occurredAt: new Date(), campaignId: 'camp-1', whatsappAccountId: 'wa-1' }); h.processNext(); assert.equal(h.overview('org-1').whatsappRead, 1); assert.equal(h.campaign.get('org-1:camp-1').opened, 1); assert.equal(h.whatsapp.get('org-1:wa-1').read, 1); });
test('DISTRIBUTION_ASSIGNED without brokerUserId does not break or increment broker', () => { const h = new AnalyticsHarness(); h.record({ organizationId: 'org-1', eventType: 'DISTRIBUTION_ASSIGNED', idempotencyKey: 'dist', occurredAt: new Date(), distributionId: 'dist-1' }); h.processNext(); assert.equal(h.overview('org-1').distributions, 1); assert.equal(h.broker.size, 0); });
test('DEAL_WON and DEAL_LOST update broker metrics when brokerUserId exists', () => { const h = new AnalyticsHarness(); h.record({ organizationId: 'org-1', eventType: 'DEAL_WON', idempotencyKey: 'won', occurredAt: new Date(), brokerUserId: 'broker-1' }); h.record({ organizationId: 'org-1', eventType: 'DEAL_LOST', idempotencyKey: 'lost', occurredAt: new Date(), brokerUserId: 'broker-1' }); h.processNext(); h.processNext(); assert.equal(h.overview('org-1').conversions, 1); assert.equal(h.broker.get('org-1:broker-1').wonDeals, 1); assert.equal(h.broker.get('org-1:broker-1').lostDeals, 1); });
test('events without campaignId or whatsappAccountId do not break', () => { const h = new AnalyticsHarness(); h.record({ organizationId: 'org-1', eventType: 'MESSAGE_SENT', idempotencyKey: 'noids', occurredAt: new Date() }); assert.equal(h.processNext(), true); });
test('event is not processed twice and concurrent-safe SQL is present', () => { const h = new AnalyticsHarness(); h.record({ organizationId: 'org-1', eventType: 'LEAD_CREATED', idempotencyKey: 'once', occurredAt: new Date() }); assert.equal(h.processNext(), true); assert.equal(h.processNext(), false); assert.match(repository, /FOR UPDATE SKIP LOCKED/); assert.match(repository, /LIMIT 1/); });
test('processedAt is set only after success and failed rollup keeps event pending', () => { const h = new AnalyticsHarness(); h.record({ organizationId: 'org-1', eventType: 'LEAD_CREATED', idempotencyKey: 'fail', occurredAt: new Date() }); assert.throws(() => h.processNext(true), /rollup failed/); assert.equal(h.events[0].processedAt, null); h.processNext(); assert.ok(h.events[0].processedAt); });
test('operational emissions are before returns and use semantic distribution id', () => { assert.equal(/return this\.findOne\([^;]+;\s*\n\s*await this\.analyticsEvents/s.test(leads), false); assert.equal(distribution.includes('brokerUserId:created.distributionMemberId'), false); assert.match(distribution, /distributionId:created\.id/); });
test('repository and service avoid any and dynamic prisma model access in analytics', () => { assert.equal(/this\.prisma as any/.test(repository), false); assert.equal(/\bas any\b/.test(repository + service + rollup), false); });
