const assert=require('node:assert/strict');const test=require('node:test');
const{matchesSaoPauloSegmentation,classifySegmentedLeads}=require('../dist/src/campaigns/campaign-audience.js');
const{estimateCampaignOperation}=require('../dist/src/campaigns/campaign-estimation.js');
const base={id:'lead-1',phone:'11999999999',normalizedPhone:null,assignedUserId:'broker-1',managerUserId:'manager-1',source:'MANUAL',status:'NEW',temperature:'HOT',createdAt:new Date('2026-01-10'),metadata:{city:'São Paulo',region:'SUL',bairro:'Moema',empreendimento:'Parque SP',preco:500000,renda:9000,dormitorios:2,possuiVaga:true,possuiVaranda:true,minhaCasaMinhaVida:false}};
test('segmentação imobiliária aplica região, bairro, renda, empreendimento, gerente e corretor em São Paulo',()=>{assert.equal(matchesSaoPauloSegmentation(base,{region:'SUL',neighborhood:'moe',development:'Parque',minIncome:8000,maxIncome:10000,managerId:'manager-1',brokerId:'broker-1'}),true);assert.equal(matchesSaoPauloSegmentation(base,{region:'NORTE'}),false);assert.equal(matchesSaoPauloSegmentation({...base,metadata:{...base.metadata,city:'Campinas'}},{}),false)});
test('materialização classifica telefones vazios, inválidos e duplicados de modo idempotente',()=>{const result=classifySegmentedLeads([base,{...base,id:'lead-2',phone:'(11) 99999-9999'},{...base,id:'lead-3',phone:''},{...base,id:'lead-4',phone:'123'}],{});assert.equal(result.eligible.length,1);assert.equal(result.duplicates,1);assert.equal(result.withoutPhone,1);assert.equal(result.invalid,1)});
test('duração considera mensagens, velocidade e concorrência sem NaN',()=>{const value=estimateCampaignOperation(600,60,2,'MARKETING',new Date('2026-01-01T10:00:00Z'));assert.equal(value.durationMinutes,5);assert.equal(value.estimatedEndAt,'2026-01-01T10:05:00.000Z');assert.equal(Number.isNaN(value.estimatedCost),false)});
test('custo não é inventado quando não existe configuração',()=>{delete process.env.CAMPAIGN_COST_UTILITY;const value=estimateCampaignOperation(10,10,1,'UTILITY');assert.equal(value.costConfigured,false);assert.equal(value.costPerMessage,null);assert.equal(value.estimatedCost,null)});
test('custo reutiliza configuração por categoria',()=>{process.env.CAMPAIGN_COST_AUTHENTICATION='0.125';const value=estimateCampaignOperation(8,10,1,'AUTHENTICATION');assert.equal(value.costPerMessage,0.125);assert.equal(value.estimatedCost,1);delete process.env.CAMPAIGN_COST_AUTHENTICATION});
