const assert=require('node:assert/strict');const test=require('node:test');const{MessagingService}=require('../dist/src/messaging/messaging.service.js');const{CampaignsController}=require('../dist/src/campaigns/campaigns.controller.js');
const template={status:'APPROVED',isActive:true,deletedAt:null,archivedAt:null,metaTemplateId:'meta-1',metaName:'hello',language:'pt_BR',components:[{type:'BODY',text:'Olá {{1}}'}]};
function fixture({campaign=true,status='DRAFT',templateValue=template,duplicate=false,recent=0,metaError}={}){const calls={audit:[],meta:[],campaignUpdates:0,queues:0,recipients:0};const prisma={campaign:{findFirst:async({where})=>campaign&&where.organizationId==='org-1'?{id:'campaign-1',organizationId:'org-1',status,whatsappAccountId:'account-1',whatsappTemplate:templateValue,totalSent:9}:null,update:async()=>{calls.campaignUpdates++}},auditLog:{findFirst:async()=>duplicate?{id:'audit-1'}:null,count:async()=>recent,create:async({data})=>{calls.audit.push(data);return data}},whatsappAccount:{findFirst:async({where})=>where.organizationId==='org-1'?{id:'account-1',organizationId:'org-1',provider:'META_CLOUD',status:'ACTIVE',tokenConfigured:true,deletedAt:null,accessToken:'encrypted',phoneNumberId:'phone-id',normalizedPhone:'+551100000000',apiVersion:'v23.0'}:null},messageQueue:{create:async()=>{calls.queues++}},campaignRecipient:{create:async()=>{calls.recipients++}}};const meta={sendTemplate:async input=>{calls.meta.push(input);if(metaError)throw metaError;return{externalMessageId:'provider-secret-id'}}};const service=new MessagingService(prisma,meta,{decrypt:value=>{assert.equal(value,'encrypted');return'token'}});return{service,calls}}
const data={phone:'+5511954325801',idempotencyKey:'click-1',values:[{component:'BODY',position:1,value:'Ana'}]};
test('envia teste aprovado no draft, audita e não altera campanha, métricas, recipients ou fila',async()=>{const{service,calls}=fixture();const result=await service.sendCampaignTest('user-1','org-1','campaign-1',data);assert.deepEqual(result,{sent:true,duplicate:false});assert.equal(calls.meta.length,1);assert.equal(calls.meta[0].to,'5511954325801');assert.equal(calls.meta[0].components[0].parameters[0].text,'Ana');assert.equal(calls.audit[0].action,'campaign.test.sent');assert.equal(calls.audit[0].metadata.providerMessageIdHash.length,64);assert.equal(calls.campaignUpdates,0);assert.equal(calls.queues,0);assert.equal(calls.recipients,0)});
test('rejeita template rejeitado, campanha inexistente, tenant incorreto e campanha finalizada',async()=>{for(const options of [{templateValue:{...template,status:'REJECTED'}},{campaign:false},{status:'COMPLETED'}]){const{service,calls}=fixture(options);await assert.rejects(()=>service.sendCampaignTest('user-1',options.campaign===false?'other':'org-1','campaign-1',data));assert.equal(calls.meta.length,0)}});
test('idempotência retorna sucesso sem novo envio',async()=>{const{service,calls}=fixture({duplicate:true});assert.deepEqual(await service.sendCampaignTest('user-1','org-1','campaign-1',data),{sent:true,duplicate:true});assert.equal(calls.meta.length,0);assert.equal(calls.audit.length,0)});
test('rate limit bloqueia antes da Meta',async()=>{const{service,calls}=fixture({recent:5});await assert.rejects(()=>service.sendCampaignTest('user-1','org-1','campaign-1',data),/TEST_RATE_LIMITED/);assert.equal(calls.meta.length,0)});
test('token inválido e erro Meta são classificados, auditados e permitem retry consciente',async()=>{for(const message of ['OAuth token expired','Meta unavailable']){const first=fixture({metaError:new Error(message)});await assert.rejects(()=>first.service.sendCampaignTest('user-1','org-1','campaign-1',data));assert.equal(first.calls.audit[0].action,'campaign.test.failed');assert.equal(first.calls.campaignUpdates,0);const retry=fixture();await retry.service.sendCampaignTest('user-1','org-1','campaign-1',{...data,idempotencyKey:'retry-2'});assert.equal(retry.calls.meta.length,1)}});
test('timeout é retryable, auditado e não é repetido automaticamente',async()=>{const{service,calls}=fixture({metaError:new Error('request timeout')});await assert.rejects(()=>service.sendCampaignTest('user-1','org-1','campaign-1',data),error=>error.response.code==='RETRYABLE_TIMEOUT');assert.equal(calls.meta.length,1);assert.equal(calls.audit[0].after.category,'RETRYABLE_TIMEOUT')});
test('endpoint exige permissão de envio WhatsApp',()=>{assert.deepEqual(Reflect.getMetadata('permissions',CampaignsController.prototype.testMessage),['whatsapp:messages:send'])});
