const assert=require('node:assert/strict');const{test}=require('node:test');const{TimelineService}=require('../dist/src/leads/timeline.service');
const date=value=>new Date(`2026-07-2${value}T12:00:00.000Z`);const ctx=(permissions=[])=>({id:'broker-1',organizationId:'org-1',global:false,permissions,role:'BROKER',roles:['BROKER']});
function harness(seed={}){const calls=[];const model=(name,items=[])=>({findMany:async args=>{calls.push([name,args]);return items}});const prisma={leadEvent:model('leadEvent',seed.events),leadActivity:model('leadActivity',seed.activities),leadDistribution:model('leadDistribution',seed.distributions),campaignRecipient:model('campaignRecipient',seed.recipients),auditLog:model('auditLog',seed.audits),whatsappMessage:model('whatsappMessage',seed.messages),dealEvent:model('dealEvent',seed.dealEvents)};return{service:new TimelineService(prisma),calls}}
test('unifies, normalizes, deduplicates and orders existing timeline sources',async()=>{const duplicateClick={id:'click-1',recipientId:'recipient-1',clickedAt:date(3),isUnique:true,isRepeated:false,redirectStatus:'REDIRECTED'};const{service}=harness({events:[{id:'event-1',idempotencyKey:null,eventType:'LEAD_CREATED',description:'Lead criado',occurredAt:date(1),actorUserId:'broker-1',actorUser:{id:'broker-1',name:'Ana'},payload:{token:'secret',from:'NEW'}}],distributions:[{id:'dist-1',status:'DISTRIBUTED',createdAt:date(2),distributedAt:date(2),slaDueAt:date(4),campaign:{name:'Campanha A'},assignedUser:{id:'broker-1',name:'Ana'},history:[],followUps:[],clicks:[duplicateClick,duplicateClick]}],activities:[],recipients:[],audits:[]});const page=await service.forLead('lead-1','org-1',ctx(),{limit:30});assert.deepEqual(page.items.map(item=>item.type),['CAMPAIGN_CLICKED','LEAD_DISTRIBUTED','LEAD_CREATED']);assert.equal(page.items.filter(item=>item.type==='CAMPAIGN_CLICKED').length,1);assert.equal('token' in page.items.at(-1).details,false)});
test('cursor pagination is stable and default limit is honored',async()=>{const events=Array.from({length:35},(_,i)=>({id:`event-${String(i).padStart(2,'0')}`,idempotencyKey:null,eventType:'LEAD_UPDATED',description:`Evento ${i}`,occurredAt:new Date(2026,0,1,0,0,i),actorUserId:null,actorUser:null,payload:{}}));const{service}=harness({events,activities:[],distributions:[],recipients:[],audits:[]});const first=await service.forLead('lead-1','org-1',ctx(),{});assert.equal(first.items.length,30);assert.equal(first.pageInfo.hasMore,true);const second=await service.forLead('lead-1','org-1',ctx(),{cursor:first.pageInfo.nextCursor,limit:30});assert.equal(second.items.length,5);assert.equal(new Set([...first.items,...second.items].map(item=>item.id)).size,35)});
test('private activities are queried only for author unless privileged',async()=>{const regular=harness({events:[],activities:[],distributions:[],recipients:[],audits:[]});await regular.service.forLead('lead-1','org-1',ctx(),{});assert.deepEqual(regular.calls.find(([name])=>name==='leadActivity')[1].where.AND[0].OR,[{visibility:'TEAM'},{createdByUserId:'broker-1'}]);const admin=harness({events:[],activities:[],distributions:[],recipients:[],audits:[]});await admin.service.forLead('lead-1','org-1',ctx(['leads:read-all']),{});assert.equal(admin.calls.find(([name])=>name==='leadActivity')[1].where.AND,undefined)});
test('every source query is tenant and lead scoped without N+1 loops',async()=>{const{service,calls}=harness({events:[],activities:[],distributions:[],recipients:[],audits:[]});await service.forLead('lead-1','org-1',ctx(),{});assert.equal(calls.length,7);for(const[name,args]of calls){assert.equal(args.where.organizationId??args.where.campaign?.organizationId,'org-1',name);if(!['auditLog','dealEvent'].includes(name))assert.equal(args.where.leadId,'lead-1',name)}});
test('invalid cursor is rejected without leaking implementation data',async()=>{const{service}=harness({events:[],activities:[],distributions:[],recipients:[],audits:[]});await assert.rejects(()=>service.forLead('lead-1','org-1',ctx(),{cursor:'invalid'}),/Cursor da timeline é inválido/)});

const { validate }=require('class-validator');
const { LeadTimelineQueryDto }=require('../dist/src/leads/dto/lead-timeline.dto');
const { LeadsService }=require('../dist/src/leads/leads.service');

test('ascending and descending ordering use persistent id as timestamp tie-breaker',async()=>{const same=new Date('2026-08-01T10:00:00Z'),events=['a','c','b'].map(id=>({id,idempotencyKey:null,eventType:'LEAD_UPDATED',description:id,occurredAt:same,actorUserId:null,actorUser:null,payload:{}}));const h=harness({events});const desc=await h.service.forLead('lead-1','org-1',ctx(),{order:'desc'});const asc=await h.service.forLead('lead-1','org-1',ctx(),{order:'asc'});assert.deepEqual(desc.items.map(item=>item.id),['lead:c','lead:b','lead:a']);assert.deepEqual(asc.items.map(item=>item.id),['lead:a','lead:b','lead:c'])});

test('activity LeadEvent duplicate is removed in favor of structured activity',async()=>{const occurredAt=date(2),h=harness({events:[{id:'activity-event',idempotencyKey:null,eventType:'LEAD_ACTIVITY_CREATED',description:'Atividade criada',occurredAt,actorUserId:'broker-1',actorUser:{id:'broker-1',name:'Ana'},payload:{activityId:'activity-1'}}],activities:[{id:'activity-1',type:'CALL',title:'Ligação',description:null,note:null,createdAt:occurredAt,completedAt:null,status:'PENDING',result:null,nextFollowUpAt:null,visibility:'TEAM',createdByUser:{id:'broker-1',name:'Ana'},responsibleUser:{id:'broker-1',name:'Ana'}}]});const page=await h.service.forLead('lead-1','org-1',ctx(),{});assert.deepEqual(page.items.map(item=>item.id),['activity:activity-1:created'])});

test('audit dedupe requires a structured transition and preserves legitimate nearby events',async()=>{const at=date(2),h=harness({events:[{id:'status-a',idempotencyKey:null,eventType:'LEAD_STATUS_CHANGED',description:'A',occurredAt:at,actorUserId:'broker-1',actorUser:{id:'broker-1',name:'Ana'},payload:{from:'NEW',to:'QUALIFIED'}},{id:'status-b',idempotencyKey:null,eventType:'LEAD_STATUS_CHANGED',description:'B',occurredAt:at,actorUserId:'broker-1',actorUser:{id:'broker-1',name:'Ana'},payload:{from:'QUALIFIED',to:'CONVERTED'}}],audits:[{id:'audit-a',action:'lead.status_changed',entityId:'lead-1',occurredAt:new Date(at.getTime()+500),actorUserId:'broker-1',actorUser:{id:'broker-1',name:'Ana'},before:{from:'NEW'},after:{to:'QUALIFIED'},metadata:null},{id:'audit-empty',action:'lead.status_changed',entityId:'lead-1',occurredAt:new Date(at.getTime()+600),actorUserId:'broker-1',actorUser:{id:'broker-1',name:'Ana'},before:null,after:null,metadata:null}]});const page=await h.service.forLead('lead-1','org-1',ctx(),{});assert.equal(page.items.some(item=>item.id==='audit:audit-a'),false);assert.equal(page.items.some(item=>item.id==='audit:audit-empty'),true);assert.equal(page.items.filter(item=>item.source==='LEADS').length,2)});

test('database queries receive limit plus one and source/search/date filters before pagination',async()=>{const h=harness({events:[]});await h.service.forLead('lead-1','org-1',ctx(),{limit:30,source:'LEADS',search:'cliente',from:'2026-07-01T00:00:00Z',to:'2026-07-31T23:59:59Z'});assert.equal(h.calls.length,1);const args=h.calls[0][1];assert.equal(args.take,31);assert.equal(args.where.description.contains,'cliente');assert.ok(args.where.occurredAt.gte instanceof Date);assert.ok(args.where.occurredAt.lte instanceof Date)});

test('DTO rejects timeline limits above one hundred',async()=>{const errors=await validate(Object.assign(new LeadTimelineQueryDto(),{limit:101}));assert.ok(errors.some(error=>error.property==='limit'))});

function leadsHarness({actorRole='BROKER',assignedUserId='broker-1',managerUserId='manager-1',failEvent=false}={}){const state={activities:[],events:[],audits:[]};const actorId=actorRole==='MANAGER'?'manager-1':actorRole==='ADMIN'?'admin-1':'broker-1';const permissions=actorRole==='ADMIN'?['leads:read-all']:[];const lead={id:'lead-1',organizationId:'org-1',assignedUserId,managerUserId,createdByUserId:'creator',deletedAt:null,archivedAt:null,activities:[],events:[],externalIdentities:[],_count:{events:0,activities:0}};const visible=()=>actorRole==='ADMIN'||assignedUserId===actorId||managerUserId===actorId;const tx={leadActivity:{create:async({data})=>{const row={id:'activity-1',createdAt:new Date(),updatedAt:new Date(),completedAt:null,...data};state.activities.push(row);return row},update:async({data})=>Object.assign(state.activities[0],data)},leadEvent:{create:async({data})=>{if(failEvent)throw new Error('event failed');state.events.push(data);return data}}};const prisma={lead:{findFirst:async()=>visible()?lead:null},user:{findFirst:async()=>({id:'broker-1',organizationId:'org-1',active:true,status:'ACTIVE',deletedAt:null,role:'BROKER'})},leadActivity:{findFirst:async()=>state.activities[0]??null},$transaction:async callback=>{const snapshot=structuredClone(state);try{return await callback(tx)}catch(error){state.activities.splice(0,state.activities.length,...snapshot.activities);state.events.splice(0,state.events.length,...snapshot.events);throw error}}};const access={resolve:async()=>({id:actorId,role:actorRole,organizationId:'org-1',global:false,permissions,roles:[actorRole]})};const audit={record:async data=>state.audits.push(data)};return{service:new LeadsService(prisma,access,{forLead:async()=>({})},audit,{emit:async()=>{}}),state,user:{id:actorId,role:actorRole}}}

test('broker and manager cannot read a lead outside their responsibility while tenant admin can',async()=>{await assert.rejects(()=>leadsHarness({assignedUserId:'other',managerUserId:'other'}).service.findOne('lead-1',{id:'broker-1',role:'BROKER'}),/Lead não encontrado/);await assert.rejects(()=>leadsHarness({actorRole:'MANAGER',assignedUserId:'other',managerUserId:'other'}).service.findOne('lead-1',{id:'manager-1',role:'MANAGER'}),/Lead não encontrado/);assert.equal((await leadsHarness({actorRole:'ADMIN',assignedUserId:'other',managerUserId:'other'}).service.findOne('lead-1',{id:'admin-1',role:'ADMIN'})).id,'lead-1')});

test('activity and LeadEvent commit atomically and audit only after success',async()=>{const ok=leadsHarness();await ok.service.createActivity('lead-1',{title:'Ligação',dueAt:'2026-08-01T12:00:00Z',responsibleUserId:'broker-1',type:'CALL',visibility:'PRIVATE'},ok.user);assert.equal(ok.state.activities.length,1);assert.equal(ok.state.events.length,1);assert.equal(ok.state.audits.length,1);const failed=leadsHarness({failEvent:true});await assert.rejects(()=>failed.service.createActivity('lead-1',{title:'Ligação',dueAt:'2026-08-01T12:00:00Z',responsibleUserId:'broker-1'},failed.user),/event failed/);assert.equal(failed.state.activities.length,0);assert.equal(failed.state.audits.length,0)});

test('appointment can be completed or canceled through the existing activity update',async()=>{const completed=leadsHarness();await completed.service.createActivity('lead-1',{title:'Visita',dueAt:'2026-08-01T12:00:00Z',responsibleUserId:'broker-1',type:'VISIT'},completed.user);await completed.service.updateActivity('lead-1','activity-1',{status:'COMPLETED'},completed.user);assert.equal(completed.state.activities[0].status,'COMPLETED');assert.ok(completed.state.activities[0].completedAt);const canceled=leadsHarness();await canceled.service.createActivity('lead-1',{title:'Retorno',dueAt:'2026-08-01T12:00:00Z',responsibleUserId:'broker-1'},canceled.user);await canceled.service.updateActivity('lead-1','activity-1',{status:'CANCELED'},canceled.user);assert.equal(canceled.state.activities[0].status,'CANCELED')});
