const assert=require('node:assert/strict');const test=require('node:test');
const {CampaignsService}=require('../dist/src/campaigns/campaigns.service');
const {normalizeBrazilianPhone,parseCsv,classifyRows,escapeCsv,safeColumnId,detectMediaMime}=require('../dist/src/campaigns/campaign-preparation');
const base={id:'c1',organizationId:'o1',status:'DRAFT',category:'UTILITY',whatsappAccountId:'a1',whatsappTemplateId:'t1',listConfirmedAt:new Date(),import:{validRows:1,columnMapping:{includedColumns:['nome_1']}},variableMappings:[],whatsappTemplate:{components:[]}};
function fx(o={}){const calls={create:[],update:[],agents:[],meta:0,jobs:0,credits:0};const p={user:{findFirst:async()=>({organizationId:'o1'}),count:async()=>o.userCount??1},campaign:{findFirst:async({where})=>where.id==='cross'?null:{...base,...o.campaign},create:async({data})=>(calls.create.push(data),data),update:async({data})=>(calls.update.push(data),{...base,...data})},whatsappAccount:{findFirst:async({where})=>['evolution','archived'].includes(where.id)?null:{id:where.id}},whatsappTemplate:{findFirst:async()=>o.noTemplate?null:{id:'t1',category:o.templateCategory||'UTILITY',components:o.components||[]}},campaignAgent:{deleteMany:async()=>{},createMany:async({data})=>calls.agents.push(...data)},campaignRecipient:{findMany:async()=>o.rows||[],count:async()=>o.rows?.length||0},$transaction:async x=>typeof x==='function'?x(p):Promise.all(x)};return{service:new CampaignsService(p),calls}}
const data=()=>parseCsv(Buffer.from('Nome,Telefone\nAna,11999999999\nBia,\nAna2,11999999999'));
test('01 cria campanha DRAFT',async()=>assert.equal((await fx().service.create('u',{name:'C',campaignType:'UTILITY'})).status,'DRAFT'));
test('02 deriva tenant autenticado',async()=>{const f=fx();await f.service.create('u',{name:'C',campaignType:'UTILITY'});assert.equal(f.calls.create[0].organizationId,'o1')});
test('03 rejeita acesso cruzado',async()=>assert.rejects(()=>fx().service.findOne('u','cross'),/não encontrada/));
test('04 aceita conta Meta ativa',async()=>fx().service.create('u',{name:'C',campaignType:'UTILITY',whatsappAccountId:'a1'}));
test('05 rejeita Evolution',async()=>assert.rejects(()=>fx().service.create('u',{name:'C',campaignType:'UTILITY',whatsappAccountId:'evolution'}),/Conta oficial/));
test('06 rejeita conta arquivada',async()=>assert.rejects(()=>fx().service.create('u',{name:'C',campaignType:'UTILITY',whatsappAccountId:'archived'}),/Conta oficial/));
test('07 lê CSV válido',()=>assert.equal(data().rows.length,3));
test('08 rejeita XLS amigavelmente',async()=>assert.rejects(()=>fx().service.uploadList('u','c1',{buffer:Buffer.from('d0cf11e0','hex'),originalname:'x.xls',size:4,mimetype:'x'}),/somente arquivos CSV/));
test('09 rejeita XLSX amigavelmente',async()=>assert.rejects(()=>fx().service.uploadList('u','c1',{buffer:Buffer.from('504b0304','hex'),originalname:'x.xlsx',size:4,mimetype:'x'}),/somente arquivos CSV/));
test('10 rejeita arquivo inválido',async()=>assert.rejects(()=>fx().service.uploadList('u','c1',{buffer:Buffer.from('abc'),originalname:'x',size:3,mimetype:'x'}),/CSV válido/));
test('11 rejeita planilha vazia',()=>assert.throws(()=>parseCsv(Buffer.alloc(0)),/vazio/));
test('12 detecta cabeçalhos',()=>assert.deepEqual(data().headers.map(x=>x.name),['Nome','Telefone']));
test('13 seleciona coluna por id seguro',()=>assert.equal(safeColumnId('Telefone',1),'telefone_2'));
test('14 normaliza brasileiro',()=>assert.equal(normalizeBrazilianPhone('(11)99999-9999').phone,'5511999999999'));
test('15 adiciona DDI',()=>assert.equal(normalizeBrazilianPhone('11999999999').ddiCorrected,true));
test('16 rejeita DDD inválido',()=>assert.equal(normalizeBrazilianPhone('5500999999999').reason,'PHONE_INVALID_DDD'));
test('17 rejeita comprimento',()=>assert.equal(normalizeBrazilianPhone('123').reason,'PHONE_INVALID_LENGTH'));
test('18 detecta duplicado',()=>assert.equal(classifyRows(data().rows,'telefone_2')[2].status,'DUPLICATE'));
test('19 produz resumo comportamental',()=>assert.deepEqual(Object.fromEntries(['VALID','INVALID','DUPLICATE'].map(s=>[s,classifyRows(data().rows,'telefone_2').filter(x=>x.status===s).length])),{VALID:1,INVALID:1,DUPLICATE:1}));
const row=s=>({originalData:{nome_1:'=X'},phone:s==='PENDING'?'5511999999999':'',status:s,invalidReason:s==='FAILED'?'PHONE_EMPTY':s==='SKIPPED'?'DUPLICATE_PHONE':null,originalRowNumber:2});
test('20 exporta inválidos',async()=>assert.match(await fx({rows:[row('FAILED')]}).service.exportList('u','c1','invalid'),/PHONE_EMPTY/));
test('21 exporta duplicados',async()=>assert.match(await fx({rows:[row('SKIPPED')]}).service.exportList('u','c1','duplicates'),/DUPLICATE_PHONE/));
test('22 exporta limpos',async()=>assert.match(await fx({rows:[row('PENDING')]}).service.exportList('u','c1','clean'),/VALID/));
test('23 bloqueia CSV Injection',()=>assert.equal(escapeCsv('=X'),"\"'=X\""));
test('24 aceita template disponível',async()=>fx().service.configureTemplate('u','c1',{whatsappTemplateId:'t1',variableMappings:[]}));
test('25 rejeita template indisponível',async()=>assert.rejects(()=>fx({noTemplate:true}).service.configureTemplate('u','c1',{whatsappTemplateId:'t1',variableMappings:[]}),/indisponível/));
test('26 rejeita categoria incompatível',async()=>assert.rejects(()=>fx({templateCategory:'MARKETING'}).service.configureTemplate('u','c1',{whatsappTemplateId:'t1',variableMappings:[]}),/incompatível/));
const one=t=>fx({components:[{type:'BODY',text:'{{1}}'}]}).service.configureTemplate('u','c1',{whatsappTemplateId:'t1',variableMappings:[{component:'BODY',position:1,sourceType:t,...(t==='COLUMN'?{sourceColumn:'nome_1'}:{}),...(t==='FIXED'?{fixedValue:'Oi'}:{})}]});
test('27 mapeia COLUMN',()=>one('COLUMN'));test('28 mapeia FIXED',()=>one('FIXED'));test('29 mapeia LEAD_NAME',()=>one('LEAD_NAME'));test('30 mapeia LEAD_PHONE',()=>one('LEAD_PHONE'));
test('31 rejeita variável ausente',async()=>assert.rejects(()=>fx({components:[{type:'BODY',text:'{{1}}'}]}).service.configureTemplate('u','c1',{whatsappTemplateId:'t1',variableMappings:[]}),/variáveis obrigatórias/));
test('32 exige buttonIndex',async()=>assert.rejects(()=>fx({components:[{type:'BUTTONS',buttons:[{type:'URL',url:'https://x/{{1}}'}]}]}).service.configureTemplate('u','c1',{whatsappTemplateId:'t1',variableMappings:[{component:'BUTTON',position:1,sourceType:'FIXED',fixedValue:'x'}]}),/buttonIndex/));
test('33 revisão exige mídia',async()=>assert.rejects(()=>fx({campaign:{whatsappTemplate:{components:[{type:'HEADER',format:'IMAGE'}]}}}).service.review('u','c1',{confirmed:true}),/exige mídia/));
test('34 detecta mídia incompatível',()=>assert.equal(detectMediaMime(Buffer.from('x')),null));
test('35 rejeita corretor externo',async()=>assert.rejects(()=>fx({userCount:0}).service.configureDestination('u','c1',{mode:'AGENT_FIXED',agentId:'x'}),/Corretor/));
test('36 salva AGENT_FIXED',async()=>{const f=fx();await f.service.configureDestination('u','c1',{mode:'AGENT_FIXED',agentId:'b'});assert.equal(f.calls.update.at(-1).destinationConfig.mode,'AGENT_FIXED')});
test('37 salva ROUND_ROBIN sem executar',async()=>{const f=fx();await f.service.configureDestination('u','c1',{mode:'ROUND_ROBIN',agents:[{userId:'b',position:0,weight:2,active:true}],initialIndex:2});assert.equal(f.calls.agents.length,1);assert.equal(f.calls.update.at(-1).destinationConfig.initialIndex,2)});
test('38 salva etapa parcial',async()=>{const f=fx();await f.service.saveStep('u','c1',3);assert.equal(f.calls.update.at(-1).currentStep,3)});
test('39 reabre rascunho',async()=>assert.equal((await fx({campaign:{currentStep:3}}).service.findOne('u','c1')).currentStep,3));
test('40 revisão exige confirmação',async()=>assert.rejects(()=>fx().service.review('u','c1',{confirmed:false}),/Confirme/));
test('41 não chama Meta',async()=>{const f=fx();await f.service.saveStep('u','c1',2);assert.equal(f.calls.meta,0)});
test('42 não cria job',async()=>{const f=fx();await f.service.configureDestination('u','c1',{mode:'FIXED_URL',fixedUrl:'https://x.com'});assert.equal(f.calls.jobs,0)});
test('43 não consome crédito',async()=>{const f=fx();await f.service.saveStep('u','c1',4);assert.equal(f.calls.credits,0)});
