const assert=require('node:assert/strict'); const test=require('node:test');
const {MetaWhatsappHttpClient}=require('../dist/src/whatsapp/meta/meta-whatsapp-http.client');
const response=(body,ok=true,status=200)=>({ok,status,json:async()=>body});
test('sincroniza uma página com campos oficiais',async()=>{const old=global.fetch;global.fetch=async()=>response({data:[{id:'1',name:'hello',language:'pt_BR',category:'UTILITY',status:'APPROVED',components:[]} ]});try{const rows=await new MetaWhatsappHttpClient().syncTemplates({accessToken:'secret',businessAccountId:'waba'});assert.equal(rows.length,1);assert.equal(rows[0].id,'1')}finally{global.fetch=old}});
test('segue paginação por paging.next sem expor token',async()=>{const old=global.fetch;let calls=0;global.fetch=async(url,init)=>{calls++;assert.equal(new URL(url).hostname,'graph.facebook.com');assert.equal(new URL(url).searchParams.has('access_token'),false);assert.equal(init.headers.authorization,'Bearer secret');return response(calls===1?{data:[{id:'1'}],paging:{next:'https://graph.facebook.com/v23.0/waba/message_templates?after=x',cursors:{after:'x'}}}:{data:[{id:'2'}]})};try{const rows=await new MetaWhatsappHttpClient().syncTemplates({accessToken:'secret',businessAccountId:'waba'});assert.equal(rows.length,2);assert.equal(calls,2)}finally{global.fetch=old}});
test('detecta cursor repetido e bloqueia URL externa',async()=>{const old=global.fetch;let calls=0;global.fetch=async()=>response(++calls===1?{data:[],paging:{next:'https://graph.facebook.com/v23.0/x?after=x',cursors:{after:'x'}}}:{data:[],paging:{next:'https://graph.facebook.com/v23.0/x?after=x',cursors:{after:'x'}}});try{await assert.rejects(()=>new MetaWhatsappHttpClient().syncTemplates({accessToken:'secret',businessAccountId:'waba'}),/PAGING_LOOP/)}finally{global.fetch=old}const client=new MetaWhatsappHttpClient();await assert.rejects(()=>client.request('https://evil.example/templates','secret'),/PAGING_URL_INVALID/)});
test('sanitiza access token em erro da Meta',async()=>{const old=global.fetch;global.fetch=async()=>response({error:{type:'OAuthException',message:'bad access_token=secret',code:190}},false,400);try{await assert.rejects(()=>new MetaWhatsappHttpClient().syncTemplates({accessToken:'secret',businessAccountId:'waba'}),e=>!e.message.includes('secret')&&e.message.includes('[REDACTED]'))}finally{global.fetch=old}});
test('serviço contém isolamento tenant, provider, arquivo, upsert, arquivamento, webhook e status seguro',()=>{const fs=require('node:fs');const s=fs.readFileSync('src/whatsapp/whatsapp.service.ts','utf8');for(const pattern of ['organizationId:org','META_CLOUD','deletedAt:null','totalFound','unchanged','updateMany','WHATSAPP_TEMPLATE_SYNC_REQUIRED','processTemplateUpdate',"internal==='APPROVED'",'whatsappAccountId:q.whatsappAccountId'])assert.ok(s.includes(pattern),pattern)});

const {WhatsappService}=require('../dist/src/whatsapp/whatsapp.service');const {parseMetaTemplateComponents,toSafeTemplate}=require('../dist/src/whatsapp/templates/template-components');const user={id:'u'};
function fx(o={}){const account={id:'a1',organizationId:'o1',provider:'META_CLOUD',status:'ACTIVE',deletedAt:null,wabaId:'w',accessToken:'x',...o.account};const local=o.local||[];const calls={updates:[],many:[],queries:[],events:[]};let n=0;const prisma={whatsappAccount:{findFirst:async({where})=>where.id===account.id&&where.organizationId===account.organizationId&&(!('deletedAt'in where)||where.deletedAt===account.deletedAt)?account:null,update:async()=>account},whatsappTemplate:{findFirst:async({where})=>o.find?o.find(where):local.find(t=>t.organizationId===where.organizationId&&(!where.id||t.id===where.id)&&(!where.whatsappAccountId||t.whatsappAccountId===where.whatsappAccountId)&&(!where.metaTemplateId||t.metaTemplateId===where.metaTemplateId))||null,findMany:async a=>(calls.queries.push(a),o.rows||[]),count:async()=>o.total||0,create:async({data})=>({id:`n${++n}`,...data}),update:async a=>(calls.updates.push(a),{id:a.where.id,...a.data}),updateMany:async a=>(calls.many.push(a),{count:o.archived||0})},whatsappWebhookEvent:{create:async({data})=>{const e={id:`e${++n}`,...data};calls.events.push(e);return e},update:async a=>a},$transaction:async a=>Promise.all(a)};const service=new WhatsappService(prisma,{resolve:async()=>({id:'u',global:false,organizationId:'o1'})},{record:async()=>{}},{decrypt:()=> 'token'},{syncTemplates:async()=>o.remote||[]},{});return{service,calls,account}}
test('rejeita sincronização cross-tenant',async()=>{await assert.rejects(()=>fx({account:{organizationId:'o2'}}).service.syncTemplates({whatsappAccountId:'a1'},user),/Conta WhatsApp não encontrada/)});
test('rejeita conta EVOLUTION',async()=>{await assert.rejects(()=>fx({account:{provider:'EVOLUTION'}}).service.syncTemplates({whatsappAccountId:'a1'},user),/META_ONLY/)});
test('rejeita conta arquivada',async()=>{await assert.rejects(()=>fx({account:{deletedAt:new Date()}}).service.syncTemplates({whatsappAccountId:'a1'},user),/Conta WhatsApp não encontrada/)});
test('arquiva removidos dentro do tenant e conta',async()=>{const f=fx({archived:1});const r=await f.service.syncTemplates({whatsappAccountId:'a1'},user);assert.equal(r.archived,1);assert.deepEqual(f.calls.many[0].where,{organizationId:'o1',whatsappAccountId:'a1',deletedAt:null,archivedAt:null})});
test('reativa template reaparecido',async()=>{const t={id:'t1',organizationId:'o1',whatsappAccountId:'a1',metaTemplateId:'m1',name:'x',language:'pt_BR',archivedAt:new Date()};const f=fx({local:[t],remote:[{id:'m1',name:'x',language:'pt_BR',category:'UTILITY',status:'APPROVED',components:[]}]});await f.service.syncTemplates({whatsappAccountId:'a1'},user);const d=f.calls.updates.find(x=>x.where.id==='t1').data;assert.equal(d.archivedAt,null);assert.equal(d.isActive,true)});
test('status desconhecido persiste UNKNOWN e indisponível',async()=>{let created;const f=fx({remote:[{id:'m1',name:'x',language:'pt_BR',category:'UTILITY',status:'FUTURE',components:[]}]});f.service.prisma.whatsappTemplate.create=async({data})=>(created={id:'t',...data});await f.service.syncTemplates({whatsappAccountId:'a1'},user);assert.equal(created.status,'UNKNOWN');assert.equal(created.isActive,false);assert.equal(toSafeTemplate({...created,whatsappAccount:{provider:'META_CLOUD',status:'ACTIVE'}}).availableForSending,false)});
test('availableForSending exige aprovação, ativo, Meta ativa, id e ausência de arquivo',()=>{const base={status:'APPROVED',isActive:true,archivedAt:null,deletedAt:null,metaTemplateId:'m',components:[],whatsappAccount:{provider:'META_CLOUD',status:'ACTIVE'}};assert.equal(toSafeTemplate(base).availableForSending,true);for(const x of [{status:'UNKNOWN'},{isActive:false},{archivedAt:new Date()},{deletedAt:new Date()},{metaTemplateId:null},{whatsappAccount:{provider:'EVOLUTION',status:'ACTIVE'}},{whatsappAccount:{provider:'META_CLOUD',status:'INACTIVE'}}])assert.equal(toSafeTemplate({...base,...x}).availableForSending,false)});
test('extrai variáveis HEADER BODY BUTTON com posição tipo exemplo ordem e botão',()=>{const r=parseMetaTemplateComponents([{type:'HEADER',format:'TEXT',text:'Oi {{1}}',example:{header_text:['Rodrigo']}},{type:'BODY',text:'Pedido {{1}}: {{2}}',example:{body_text:[['ABC','10']]}},{type:'BUTTONS',buttons:[{type:'URL',url:'https://x/{{1}}',example:['ABC']}]}]);assert.deepEqual(r.variables,[{position:1,component:'HEADER',type:'TEXT',example:'Rodrigo',required:true,order:1},{position:1,component:'BODY',type:'TEXT',example:'ABC',required:true,order:2},{position:2,component:'BODY',type:'TEXT',example:'10',required:true,order:3},{position:1,component:'BUTTON',type:'URL',example:'ABC',required:true,order:4,buttonIndex:0}])});
test('webhook atualiza template correto e nunca outro tenant',async()=>{const t={id:'t1',organizationId:'o1',whatsappAccountId:'a1',metaTemplateId:'m1',category:'UTILITY'};const f=fx({local:[t]});await f.service.processTemplateUpdate(f.account,{message_template_id:'m1',event:'APPROVED'});assert.equal(f.calls.updates[0].where.id,'t1');const other=fx({find:()=>null});await other.service.processTemplateUpdate(other.account,{message_template_id:'m1',event:'REJECTED'});assert.equal(other.calls.updates.length,0)});
test('listagem aplica tenant, conta, status, categoria, idioma, nome e paginação',async()=>{const f=fx({total:25,account:{lastSyncAt:new Date('2026-01-01')}});const r=await f.service.findTemplates({whatsappAccountId:'a1',status:'APPROVED',category:'UTILITY',language:'pt_BR',search:'ola',page:2,pageSize:10},user);const a=f.calls.queries[0];assert.equal(a.where.organizationId,'o1');for(const [k,v] of Object.entries({whatsappAccountId:'a1',status:'APPROVED',category:'UTILITY',language:'pt_BR'}))assert.equal(a.where[k],v);assert.ok(a.where.OR);assert.equal(a.skip,10);assert.equal(a.take,10);assert.equal(r.totalPages,3);assert.equal(r.lastSyncedAt.toISOString(),'2026-01-01T00:00:00.000Z')});
test('detalhe tenant-aware não retorna credenciais e calcula disponibilidade',async()=>{const t={id:'t1',organizationId:'o1',status:'APPROVED',isActive:true,archivedAt:null,deletedAt:null,metaTemplateId:'m',components:[],whatsappAccount:{id:'a1',name:'Conta',provider:'META_CLOUD',status:'ACTIVE'}};const f=fx({find:w=>w.organizationId==='o1'?t:null});const r=await f.service.getTemplate('t1',user);assert.equal(r.availableForSending,true);for(const k of ['accessToken','appSecret','verifyToken','webhookSecret'])assert.equal(k in r.whatsappAccount,false)});
