import { AgentAvailabilityStatus, LeadAttendanceStatus } from '@prisma/client';
import { Transform, Type } from 'class-transformer';
import { IsBoolean, IsDateString, IsEnum, IsIn, IsInt, IsOptional, IsString, Max, MaxLength, Min, MinLength } from 'class-validator';
export class ListReceivedLeadsDto{@IsOptional()@Type(()=>Number)@IsInt()@Min(1)page=1;@IsOptional()@Type(()=>Number)@IsInt()@Min(1)@Max(100)limit=20;@IsOptional()@IsString()search?:string;@IsOptional()@IsString()campaignId?:string;@IsOptional()@IsString()development?:string;@IsOptional()@IsString()region?:string;@IsOptional()@IsString()neighborhood?:string;@IsOptional()@IsString()brokerId?:string;@IsOptional()@IsString()managerId?:string;@IsOptional()@IsEnum(LeadAttendanceStatus)status?:LeadAttendanceStatus;@IsOptional()@Transform(({value})=>value===true||value==='true')@IsBoolean()pendingOnly?:boolean;@IsOptional()@Transform(({value})=>value===true||value==='true')@IsBoolean()overdueOnly?:boolean;@IsOptional()@IsDateString()from?:string;@IsOptional()@IsDateString()to?:string}
export class UpdateAttendanceDto{@IsEnum(LeadAttendanceStatus)status:LeadAttendanceStatus;@IsOptional()@IsString()@MaxLength(1000)notes?:string}
export class FollowUpDto{@IsIn(['YES','NO','NOT_TRIED'])contactAttempted:string;@IsIn(['YES','NO','WAITING'])customerResponded:string;@IsEnum(LeadAttendanceStatus)status:LeadAttendanceStatus;@IsOptional()@IsString()@MaxLength(1000)notes?:string;@IsOptional()@IsDateString()nextFollowUpAt?:string}
export class ReassignLeadDto{@IsString()brokerUserId:string;@IsString()@MinLength(3)@MaxLength(500)reason:string}
export class AvailabilityDto{@IsEnum(AgentAvailabilityStatus)status:AgentAvailabilityStatus;@IsOptional()@IsString()@MaxLength(500)reason?:string}
export class DistributionSettingsDto{@IsOptional()@IsBoolean()requirePreviousUpdates?:boolean;@IsOptional()@IsInt()@Min(1)@Max(10080)firstContactMinutes?:number;@IsOptional()@IsInt()@Min(1)@Max(10080)firstUpdateMinutes?:number;@IsOptional()@IsInt()@Min(1)@Max(43200)nextFollowUpMinutes?:number;@IsOptional()@IsString()@MaxLength(500)fallbackUrl?:string}
export class ManualReleaseDto{@IsString()@MinLength(3)@MaxLength(500)reason:string}
