import { Injectable } from '@nestjs/common';
import {
  MetaContact,
  MetaEmbeddedAsset,
  MetaSendResult,
  MetaTemplate,
  MetaWhatsappClient,
} from './meta-whatsapp.client';

@Injectable()
export class MetaWhatsappHttpClient extends MetaWhatsappClient {
  private readonly graphVersion = process.env.META_GRAPH_API_VERSION || 'v20.0'; private readonly timeoutMs = Number(process.env.META_WHATSAPP_TIMEOUT_MS || 8000);
  private base(apiVersion?: string | null) { return `https://graph.facebook.com/${apiVersion || this.graphVersion}`; }
  private async request<T>(path: string, token: string, init: RequestInit = {}, apiVersion?: string | null): Promise<T> { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), this.timeoutMs); try { const res = await fetch(`${this.base(apiVersion)}${path}`, { ...init, signal: controller.signal, headers: { 'content-type': 'application/json', authorization: `Bearer ${token}`, ...(init.headers || {}) } }); const body = await res.json().catch(() => ({})); if (!res.ok) { const code = body?.error?.code ? ` (${body.error.code})` : ''; throw new Error(`${body?.error?.type || 'Meta API error'}${code}: ${body?.error?.message || res.status}`); } return body as T; } finally { clearTimeout(timeout); } }
  private appCredentials() { const appId=process.env.META_APP_ID, appSecret=process.env.META_APP_SECRET; if(!appId||!appSecret) throw new Error('META_APP_ID e META_APP_SECRET são obrigatórios'); return {appId,appSecret}; }
  async exchangeCode(code:string){ const {appId,appSecret}=this.appCredentials(); const p=new URLSearchParams({client_id:appId,client_secret:appSecret,code}); const r=await this.request<{access_token:string;expires_in?:number}>(`/oauth/access_token?${p}`,''); return {accessToken:r.access_token,expiresAt:r.expires_in?new Date(Date.now()+r.expires_in*1000):null}; }
  async renewToken(token:string){ const {appId,appSecret}=this.appCredentials(); const p=new URLSearchParams({grant_type:'fb_exchange_token',client_id:appId,client_secret:appSecret,fb_exchange_token:token}); const r=await this.request<{access_token:string;expires_in?:number}>(`/oauth/access_token?${p}`,''); return {accessToken:r.access_token,expiresAt:r.expires_in?new Date(Date.now()+r.expires_in*1000):null}; }
  async inspectToken(token:string){ const {appId,appSecret}=this.appCredentials(); const appToken=`${appId}|${appSecret}`; const r=await this.request<{data:{is_valid:boolean;expires_at?:number;scopes?:string[];type?:string}}>(`/debug_token?input_token=${encodeURIComponent(token)}`,appToken); return {valid:r.data.is_valid,expiresAt:r.data.expires_at?new Date(r.data.expires_at*1000):null,scopes:r.data.scopes||[],type:r.data.type}; }
  async discoverEmbeddedAssets(token:string){ const businesses=await this.request<{data:{id:string;name:string}[]}>(`/me/businesses?fields=id,name&limit=100`,token); const assets:MetaEmbeddedAsset[]=[]; for(const business of businesses.data||[]){ const wabas=await this.request<{data:{id:string;name:string}[]}>(`/${business.id}/owned_whatsapp_business_accounts?fields=id,name&limit=100`,token); for(const waba of wabas.data||[]){ const phones=await this.request<{data:{id:string;display_phone_number:string;verified_name?:string;quality_rating?:string;code_verification_status?:string}[]}>(`/${waba.id}/phone_numbers?fields=id,display_phone_number,verified_name,quality_rating,code_verification_status&limit=100`,token); for(const phone of phones.data||[]) assets.push({businessId:business.id,businessName:business.name,wabaId:waba.id,wabaName:waba.name,phoneNumberId:phone.id,displayPhoneNumber:phone.display_phone_number,verifiedName:phone.verified_name,qualityRating:phone.quality_rating,status:phone.code_verification_status}); }} return assets; }
  async testConnection(input: { accessToken: string; phoneNumberId: string; apiVersion?: string | null }) { const r = await this.request<{ display_phone_number?: string; verified_name?: string; quality_rating?: string; messaging_limit_tier?: string }>(`/${encodeURIComponent(input.phoneNumberId)}?fields=id,display_phone_number,verified_name,quality_rating,messaging_limit_tier`, input.accessToken, {}, input.apiVersion); return { ok: true, displayPhoneNumber: r.display_phone_number, verifiedName: r.verified_name, qualityRating: r.quality_rating, messagingLimitTier: r.messaging_limit_tier }; }
  async syncAccount(input: { accessToken: string; phoneNumberId: string; apiVersion?: string | null }) { const r = await this.testConnection(input); return { displayPhoneNumber: r.displayPhoneNumber, verifiedName: r.verifiedName, qualityRating: r.qualityRating, messagingLimitTier: r.messagingLimitTier }; }
  async sendText(input: { accessToken: string; phoneNumberId: string; to: string; text: string; replyToExternalMessageId?: string }): Promise<MetaSendResult> { const body: Record<string, unknown> = { messaging_product: 'whatsapp', to: input.to, type: 'text', text: { body: input.text } }; if (input.replyToExternalMessageId) body.context = { message_id: input.replyToExternalMessageId }; const r = await this.request<{ messages?: { id: string }[] }>(`/${input.phoneNumberId}/messages`, input.accessToken, { method: 'POST', body: JSON.stringify(body) }); return { externalMessageId: r.messages?.[0]?.id || '' }; }
  async sendTemplate(input: { accessToken: string; phoneNumberId: string; to: string; name: string; language: string; components?: unknown[] }): Promise<MetaSendResult> { const r = await this.request<{ messages?: { id: string }[] }>(`/${input.phoneNumberId}/messages`, input.accessToken, { method: 'POST', body: JSON.stringify({ messaging_product: 'whatsapp', to: input.to, type: 'template', template: { name: input.name, language: { code: input.language }, components: input.components || [] } }) }); return { externalMessageId: r.messages?.[0]?.id || '' }; }
  async sendContacts(input: { accessToken: string; phoneNumberId: string; to: string; contacts: MetaContact[] }): Promise<MetaSendResult> { const contacts = input.contacts.map((contact) => ({ name: { formatted_name: contact.displayName }, phones: [{ phone: contact.phoneE164.replace('+', ''), type: 'CELL', wa_id: contact.phoneE164.replace('+', '') }] })); const r = await this.request<{ messages?: { id: string }[] }>(`/${input.phoneNumberId}/messages`, input.accessToken, { method: 'POST', body: JSON.stringify({ messaging_product: 'whatsapp', to: input.to, type: 'contacts', contacts }) }); return { externalMessageId: r.messages?.[0]?.id || '' }; }
  async sendMedia(input: { accessToken: string; phoneNumberId: string; to: string; type: string; mediaId: string; caption?: string }): Promise<MetaSendResult> { const r = await this.request<{ messages?: { id: string }[] }>(`/${input.phoneNumberId}/messages`, input.accessToken, { method: 'POST', body: JSON.stringify({ messaging_product: 'whatsapp', to: input.to, type: input.type, [input.type]: { id: input.mediaId, caption: input.caption } }) }); return { externalMessageId: r.messages?.[0]?.id || '' }; }
  async syncTemplates(input: { accessToken: string; businessAccountId: string }): Promise<MetaTemplate[]> { const r = await this.request<{ data?: MetaTemplate[] }>(`/${input.businessAccountId}/message_templates`, input.accessToken); return r.data || []; }
}
