"use client";

import Script from "next/script";
import { useCallback, useEffect, useState } from "react";
import { Building2, CheckCircle2, Link2, RefreshCw, ShieldCheck } from "lucide-react";
import { whatsappService } from "@/services/whatsapp.service";
import { WhatsappAccount, WhatsappAccountStatus } from "@/types/whatsapp";

declare global { interface Window { FB?: { init(options:Record<string,unknown>):void; login(callback:(response:{authResponse?:{code?:string}})=>void,options:Record<string,unknown>):void } } }
const statusLabels:Record<WhatsappAccountStatus,string>={ACTIVE:"Ativa",INACTIVE:"Inativa",PENDING:"Pendente",ERROR:"Erro",DISCONNECTED:"Desconectada",SUSPENDED:"Suspensa",TOKEN_EXPIRED:"Token expirado"};
function date(value?:string|null){ return value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—"; }

export default function WhatsappPage(){
 const [accounts,setAccounts]=useState<WhatsappAccount[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{setAccounts((await whatsappService.getAccounts({pageSize:100})).items);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar contas.");}finally{setLoading(false);}},[]);
 useEffect(()=>{const id=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(id);},[load]);
 async function connect(accountId?:string){setBusy(accountId||"new");setError("");try{const config=await whatsappService.getEmbeddedSignupConfig(accountId); if(!window.FB) throw new Error("O SDK seguro da Meta ainda está carregando."); window.FB.init({appId:config.appId,cookie:true,xfbml:false,version:config.apiVersion}); window.FB.login(async response=>{try{const code=response.authResponse?.code;if(!code) throw new Error("A autorização da Meta foi cancelada.");const result=await whatsappService.completeEmbeddedSignup({code,state:config.state,accountId});setMessage(`${result.accountsConnected} conta(s) sincronizada(s) com sucesso.`);await load();}catch(e){setError(e instanceof Error?e.message:"Falha ao concluir a conexão.");}finally{setBusy(null);}},{config_id:config.configId,response_type:"code",override_default_response_type:true,extras:{feature:"whatsapp_embedded_signup",sessionInfoVersion:"3"}});}catch(e){setError(e instanceof Error?e.message:"Falha ao abrir a Meta.");setBusy(null);}}
 async function sync(account:WhatsappAccount){setBusy(account.id);setError("");try{await whatsappService.syncAccount(account.id);await whatsappService.syncTemplates({accountId:account.id});setMessage("Dados e templates atualizados.");await load();}catch(e){setError(e instanceof Error?e.message:"Falha ao sincronizar.");}finally{setBusy(null);}}
 return <main className="space-y-6"><Script src="https://connect.facebook.net/pt_BR/sdk.js" strategy="afterInteractive"/>
  <header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-4xl font-bold">WhatsApp Business Platform</h1><p className="mt-2 max-w-3xl text-slate-400">Conexão enterprise pela autorização oficial da Meta. Credenciais são recebidas pelo OAuth, criptografadas e nunca precisam ser copiadas.</p></div><button onClick={()=>void connect()} disabled={!!busy} className="inline-flex items-center gap-2 ds-radius-control ds-primary px-5 py-3 font-semibold hover:bg-blue-500 disabled:opacity-50"><Link2 size={18}/>Conectar com Meta</button></header>
  {message&&<div className="ds-radius-control border border-green-800 bg-green-950/50 p-3 text-green-200">{message}</div>}{error&&<div className="ds-radius-control border border-red-800 bg-red-950/50 p-3 text-red-200">{error}</div>}
  <section className="grid gap-3 md:grid-cols-3"><div className="ds-radius-surface border ds-border ds-surface p-4"><ShieldCheck className="text-green-400"/><strong className="mt-2 block">OAuth oficial</strong><span className="text-sm text-slate-400">Embedded Signup com permissões gerenciadas pela Meta.</span></div><div className="ds-radius-surface border ds-border ds-surface p-4"><Building2 className="text-blue-400"/><strong className="mt-2 block">Múltiplas contas</strong><span className="text-sm text-slate-400">Businesses, WABAs e números autorizados são descobertos automaticamente.</span></div><div className="ds-radius-surface border ds-border ds-surface p-4"><RefreshCw className="text-violet-400"/><strong className="mt-2 block">Sincronização segura</strong><span className="text-sm text-slate-400">Status, qualidade, display name e templates sempre atualizados.</span></div></section>
  <section className="overflow-hidden ds-radius-surface border ds-border ds-surface"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b ds-border text-slate-400"><tr><th className="p-4">Business / WABA</th><th className="p-4">Número</th><th className="p-4">Qualidade</th><th className="p-4">Credencial</th><th className="p-4">Ações</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-6 text-slate-400">Carregando...</td></tr>:accounts.length===0?<tr><td colSpan={5} className="p-8 text-center text-slate-400">Nenhuma conta conectada. Use “Conectar com Meta” para começar.</td></tr>:accounts.map(account=><tr key={account.id} className="border-b ds-border last:border-0"><td className="p-4"><strong>{account.metaBusinessName||"Business Meta"}</strong><div className="text-slate-400">{account.name}</div><div className="text-xs text-slate-500">WABA {account.businessAccountId}</div></td><td className="p-4"><div>{account.displayPhoneNumber||account.phoneNumber}</div><div className="text-slate-400">{account.verifiedName||"Display name pendente"}</div><span className="mt-1 inline-flex items-center gap-1 text-xs text-green-300"><CheckCircle2 size={12}/>{statusLabels[account.status]}</span></td><td className="p-4">{account.qualityRating||"Não informada"}<div className="text-xs text-slate-500">Sync: {date(account.lastSyncAt)}</div></td><td className="p-4"><span className="rounded-full ds-surface-raised px-2 py-1 text-xs">{account.credentialType==="SYSTEM_USER"?"System User":"OAuth"}</span><div className="mt-2 text-xs text-slate-500">Expira: {account.credentialType==="SYSTEM_USER"?"não expira":date(account.tokenExpiresAt)}</div></td><td className="p-4"><div className="flex flex-wrap gap-2"><button disabled={!!busy} onClick={()=>void connect(account.id)} className="rounded border border-blue-700 px-3 py-2">Reconectar</button><button disabled={!!busy} onClick={()=>void connect(account.id)} className="rounded border border-violet-700 px-3 py-2">Atualizar permissões</button><button disabled={!!busy} onClick={()=>void sync(account)} className="rounded border ds-border p-2" aria-label="Sincronizar"><RefreshCw size={16}/></button></div></td></tr>)}</tbody></table></div></section>
 </main>;
}
