import assert from 'node:assert/strict';import test from 'node:test';import{createRequire}from'node:module';import{readFileSync}from'node:fs';import{resolve,dirname}from'node:path';
const require=createRequire(import.meta.url),ts=require('typescript'),Module=require('node:module'),root=resolve(dirname(new URL(import.meta.url).pathname),'..'),original=Module._resolveFilename;Module._resolveFilename=function(request,parent,isMain,options){if(request.startsWith('@/'))return original.call(this,resolve(root,request.slice(2)),parent,isMain,options);return original.call(this,request,parent,isMain,options)};for(const ext of['.ts','.tsx'])require.extensions[ext]=(module,filename)=>module._compile(ts.transpileModule(readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,target:ts.ScriptTarget.ES2020}}).outputText,filename);global.localStorage={getItem:()=>'token'};
const{leadService}=require('../services/lead.service.ts');function mock(handler){const calls=[];global.fetch=async(url,options={})=>{calls.push({url:String(url),options});const body=await handler(String(url),options);return{ok:true,json:async()=>body,text:async()=>JSON.stringify(body)}};return calls}
test('timeline client sends cursor filters and creates a private scheduled activity',async()=>{const calls=mock(url=>url.includes('timeline')?{leadId:'lead-1',items:[],pageInfo:{limit:30,hasMore:false,nextCursor:null},order:'desc'}:{});await leadService.getTimeline('lead-1',{cursor:'next',order:'asc',source:'ACTIVITIES',limit:30});await leadService.createCommercialActivity('lead-1',{type:'VISIT',title:'Visita',dueAt:'2026-08-01T12:00:00Z',visibility:'PRIVATE',responsibleUserId:'user-1'});const timeline=new URL(calls[0].url);assert.equal(timeline.searchParams.get('cursor'),'next');assert.equal(timeline.searchParams.get('order'),'asc');assert.deepEqual(JSON.parse(calls[1].options.body),{type:'VISIT',title:'Visita',dueAt:'2026-08-01T12:00:00Z',visibility:'PRIVATE',responsibleUserId:'user-1'})});
test('official commercial summary uses one lead detail route',async()=>{const calls=mock(()=>({lead:{id:'lead-1'},summary:{}}));await leadService.getCommercialSummary('lead-1');assert.equal(new URL(calls[0].url).pathname,'/leads/lead-1/commercial-summary')});
const React=require('react');
function flatten(node){if(!node||typeof node!=='object')return[];const children=React.Children.toArray(node.props?.children);return[node,...children.flatMap(flatten)]}
const detailPage=require('../app/leads/[id]/page.tsx');
test('official detail renders behavioral loading and error states',()=>{const loading=detailPage.LeadDetailLoading();assert.equal(loading.props['aria-busy'],'true');assert.equal(flatten(loading).filter(node=>String(node.props?.className??'').includes('animate-pulse')).length,5);const error=detailPage.LeadDetailError({message:'Falha segura'});const alert=flatten(error).find(node=>node.props?.role==='alert');assert.equal(alert.props.children,'Falha segura')});
test('timeline load-more merge does not repeat cursor boundary events',()=>{const current=[{id:'a',title:'A'}],incoming=[{id:'a',title:'A'},{id:'b',title:'B'}];assert.deepEqual(detailPage.mergeTimelineItems(current,incoming,false).map(item=>item.id),['a','b']);assert.deepEqual(detailPage.mergeTimelineItems(current,[],true),[])});
test('return navigation preserves pipeline and received-leads origins',()=>{assert.equal(detailPage.leadReturnHref('pipeline'),'/pipeline');assert.equal(detailPage.leadReturnHref('received'),'/leads/received');assert.equal(detailPage.leadReturnHref(null),'/leads')});
test('completion and cancellation use existing activity endpoint behavior',async()=>{const calls=mock(()=>({id:'activity-1'}));await leadService.updateActivity('lead-1','activity-1',{status:'COMPLETED'});await leadService.updateActivity('lead-1','activity-1',{status:'CANCELED'});assert.deepEqual(calls.map(call=>JSON.parse(call.options.body).status),['COMPLETED','CANCELED']);assert.ok(calls.every(call=>call.options.method==='PATCH'))});
test('API error is propagated for the detail error state',async()=>{global.fetch=async()=>({ok:false,text:async()=>JSON.stringify({message:'Lead não encontrado'})});await assert.rejects(()=>leadService.getCommercialSummary('foreign'),/Lead não encontrado/)});
