import { useEffect, useMemo, useRef, useState } from 'react';
import { pipelineService } from '@/services/pipeline.service';
import { Lead } from '@/types/lead';
import { Pipeline } from '@/types/pipeline';

type Props = { lead: Lead; pipelines: Pipeline[]; saving: boolean; message: string; onCancel: () => void; onConfirm: (pipelineId: string, stageId: string) => void };
export default function AddLeadToPipelineDialog({ lead, pipelines, saving, message, onCancel, onConfirm }: Props) {
  const [pipelineId, setPipelineId] = useState(pipelines[0]?.id ?? '');
  const [stageId, setStageId] = useState(pipelines[0]?.stages?.[0]?.id ?? '');
  const [stages, setStages] = useState<NonNullable<Pipeline['stages']>>(pipelines[0]?.stages ?? []);
  const selectRef = useRef<HTMLSelectElement>(null);
  const selectedPipeline = useMemo(() => pipelines.find((pipeline) => pipeline.id === pipelineId), [pipelineId, pipelines]);
  useEffect(() => { selectRef.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape' && !saving) onCancel(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [onCancel, saving]);
  useEffect(() => { let active = true; const timeoutId = window.setTimeout(() => { setStages(selectedPipeline?.stages ?? []); setStageId(selectedPipeline?.stages?.[0]?.id ?? ''); }, 0); if (pipelineId && !selectedPipeline?.stages?.length) void pipelineService.kanban(pipelineId).then((board) => { if (!active) return; setStages(board.stages); setStageId(board.stages[0]?.id ?? ''); }).catch(() => undefined); return () => { active = false; window.clearTimeout(timeoutId); }; }, [pipelineId, selectedPipeline]);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" role="dialog" aria-modal="true" aria-labelledby="pipeline-lead-title"><button aria-label="Fechar adição ao pipeline" className="absolute inset-0" disabled={saving} onClick={onCancel} /><div className="relative w-full max-w-lg space-y-4 rounded-xl border border-slate-800 bg-slate-950 p-6 shadow-2xl"><h2 id="pipeline-lead-title" className="text-xl font-bold">Adicionar ao Pipeline</h2><p className="text-sm text-slate-300">Escolha onde adicionar {lead.name || 'este lead'}.</p>{message && <p className="rounded-lg border border-amber-800 bg-amber-950/50 p-3 text-sm text-amber-100">{message}</p>}<label className="block text-sm font-medium" htmlFor="pipeline-id">Pipeline</label><select ref={selectRef} id="pipeline-id" className="w-full rounded-lg bg-slate-800 p-3" value={pipelineId} onChange={(e) => setPipelineId(e.target.value)}>{pipelines.map((pipeline) => <option key={pipeline.id} value={pipeline.id}>{pipeline.name}</option>)}</select><label className="block text-sm font-medium" htmlFor="stage-id">Etapa</label><select id="stage-id" className="w-full rounded-lg bg-slate-800 p-3" value={stageId} onChange={(e) => setStageId(e.target.value)}>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select><div className="flex justify-end gap-3"><button type="button" disabled={saving} onClick={onCancel} className="rounded-lg bg-slate-800 px-4 py-2 disabled:opacity-60">Cancelar</button><button type="button" disabled={saving || !pipelineId || !stageId} onClick={() => onConfirm(pipelineId, stageId)} className="rounded-lg bg-emerald-700 px-4 py-2 disabled:opacity-60">{saving ? 'Adicionando...' : 'Adicionar'}</button></div></div></div>;
}
