import { Lead, LeadStatus, LeadTemperature } from '@/types/lead';
import { User } from '@/types/user';
import { leadSourceLabels, leadStatusLabels, leadTemperatureLabels } from './lead-labels';

type Props = { leads: Lead[]; loading: boolean; users: User[]; busyLeadId?: string; onView: (lead: Lead) => void; onEdit: (lead: Lead) => void; onArchive: (lead: Lead) => void; onAddToPipeline: (lead: Lead) => void; onAssign: (lead: Lead, userId: string | null) => void; onStatus: (lead: Lead, status: LeadStatus) => void; onTemperature: (lead: Lead, temperature: LeadTemperature) => void };
const statuses = Object.keys(leadStatusLabels) as LeadStatus[];
const temperatures = Object.keys(leadTemperatureLabels) as LeadTemperature[];
const show = (value?: string | null) => value?.trim() || '—';

export default function LeadTable({ leads, loading, users, busyLeadId, onView, onEdit, onArchive, onAddToPipeline, onAssign, onStatus, onTemperature }: Props) {
  return <div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900"><table className="w-full min-w-[1180px]"><thead className="bg-slate-800"><tr>{['Nome','Telefone','E-mail','CPF','Origem','Status','Temperatura','Responsável','Cadastro','Atualização','Ações'].map((h) => <th key={h} className="p-3 text-left text-sm font-semibold">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={11} className="p-8 text-center text-slate-400">Carregando leads...</td></tr> : leads.length === 0 ? <tr><td colSpan={11} className="p-8 text-center text-slate-400">Nenhum lead encontrado.</td></tr> : leads.map((lead) => <tr key={lead.id} className="border-t border-slate-800 align-top"><td className="p-3 font-medium">{show(lead.name)}</td><td className="p-3">{show(lead.phone)}</td><td className="p-3">{show(lead.email)}</td><td className="p-3">{show(lead.document)}</td><td className="p-3">{leadSourceLabels[lead.source]}</td><td className="p-3"><select aria-label={`Status de ${lead.name ?? 'lead'}`} disabled={busyLeadId === lead.id} className="rounded bg-slate-800 p-2" value={lead.status} onChange={(e) => onStatus(lead, e.target.value as LeadStatus)}>{statuses.map((v) => <option key={v} value={v}>{leadStatusLabels[v]}</option>)}</select></td><td className="p-3"><select aria-label={`Temperatura de ${lead.name ?? 'lead'}`} disabled={busyLeadId === lead.id} className="rounded bg-slate-800 p-2" value={lead.temperature} onChange={(e) => onTemperature(lead, e.target.value as LeadTemperature)}>{temperatures.map((v) => <option key={v} value={v}>{leadTemperatureLabels[v]}</option>)}</select></td><td className="p-3"><select aria-label={`Responsável de ${lead.name ?? 'lead'}`} disabled={busyLeadId === lead.id} className="rounded bg-slate-800 p-2" value={lead.assignedUserId ?? ''} onChange={(e) => onAssign(lead, e.target.value || null)}><option value="">Sem corretor</option>{users.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</select></td><td className="p-3">{new Date(lead.createdAt).toLocaleDateString('pt-BR')}</td><td className="p-3">{new Date(lead.updatedAt).toLocaleDateString('pt-BR')}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button type="button" onClick={() => onView(lead)} className="rounded bg-slate-700 px-3 py-2">Lead 360°</button><button type="button" onClick={() => onEdit(lead)} className="rounded bg-blue-700 px-3 py-2">Editar</button><button type="button" onClick={() => onAddToPipeline(lead)} className="rounded bg-emerald-700 px-3 py-2">Pipeline</button><button type="button" disabled={busyLeadId === lead.id} onClick={() => onArchive(lead)} className="rounded bg-red-700 px-3 py-2 disabled:opacity-60">Arquivar</button></div></td></tr>)}</tbody></table></div>;
}
