"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Activity, RefreshCw, Search, ShieldCheck, Sparkles, UserCheck, UserPlus, UsersRound } from "lucide-react";
import Badge from "@/components/ui/Badge"; import Button from "@/components/ui/Button"; import Card from "@/components/ui/Card"; import Input from "@/components/ui/Input"; import Modal from "@/components/ui/Modal"; import Select from "@/components/ui/Select";
import UserForm from "./UserForm"; import UserTable from "./UserTable"; import BrokersEnterprise from "./BrokersEnterprise";
import { getCurrentUser, isGlobalAdmin } from "@/services/auth"; import { organizationService } from "@/services/organization.service"; import { userService } from "@/services/user.service";
import { Organization } from "@/types/organization"; import { User, UserFormData, UserMetrics, UserRole } from "@/types/user";
const PAGE_SIZE=10; const emptyMetrics:UserMetrics={total:0,active:0,inactive:0,administrators:0,managers:0,brokers:0};
export default function UsersPage({mode}:{mode:"users"|"corretores"}) { const brokers=mode==="corretores"; const current=useMemo(()=>getCurrentUser(),[]); const global=isGlobalAdmin(); const authorized=!!current&&!['CORRETOR','BROKER'].includes(current.role); const canManage=authorized; const roles:UserRole[]=global?["GLOBAL_ADMIN","ORG_ADMIN","MANAGER","BROKER"]:current?.role==="MANAGER"?["BROKER"]:["MANAGER","BROKER"];
 const [users,setUsers]=useState<User[]>([]),[organizations,setOrganizations]=useState<Organization[]>([]); const [metrics,setMetrics]=useState(emptyMetrics); const [search,setSearch]=useState(""),[debounced,setDebounced]=useState(""),[active,setActive]=useState(""),[role,setRole]=useState(""); const [page,setPage]=useState(1),[pages,setPages]=useState(1); const [loading,setLoading]=useState(authorized),[saving,setSaving]=useState(false); const [error,setError]=useState(""),[notice,setNotice]=useState(""); const [form,setForm]=useState<User|null|undefined>(undefined),[view,setView]=useState<User|null>(null),[reset,setReset]=useState<User|null>(null),[password,setPassword]=useState(""),[status,setStatus]=useState<User|null>(null),[archive,setArchive]=useState<User|null>(null);
 const requestSequence=useRef(0); const inFlight=useRef(false);
 useEffect(()=>{const id=window.setTimeout(()=>{setDebounced(search);setPage(1);setLoading(true)},350);return()=>window.clearTimeout(id)},[search]);
 const loadUsers=useCallback(async(force=false)=>{await Promise.resolve();if(!authorized||(!force&&inFlight.current))return;const requestId=++requestSequence.current;inFlight.current=true;try{setError("");const query={page,limit:PAGE_SIZE,search:debounced,active:active===""?"" as const:active==="true",role:(role||undefined) as UserRole|undefined};const [list,summary]=await Promise.all([userService.getAll(query),userService.getMetrics()]);if(requestId!==requestSequence.current)return;setUsers(brokers?list.items.filter(u=>["CORRETOR","BROKER"].includes(u.role)):list.items);setPages(list.meta.totalPages||1);setMetrics(summary)}catch(e){if(requestId===requestSequence.current)setError(e instanceof Error?e.message:"Não foi possível carregar os usuários.")}finally{if(requestId===requestSequence.current){inFlight.current=false;setLoading(false)}}},[active,authorized,brokers,debounced,page,role]);
 useEffect(()=>{let cancelled=false;async function synchronize(){await loadUsers(true);if(cancelled)requestSequence.current+=1}void synchronize();return()=>{cancelled=true;requestSequence.current+=1;inFlight.current=false}},[loadUsers]);
 useEffect(()=>{if(!brokers||!authorized)return;const intervalId=window.setInterval(() => void loadUsers(), 60_000);return()=>window.clearInterval(intervalId)},[authorized,brokers,loadUsers]);
 useEffect(()=>{if(!global)return;let cancelled=false;async function loadOrganizations(){const response=await organizationService.getAll({page:1,limit:100});if(!cancelled)setOrganizations(response.items.filter(o=>o.active))}void loadOrganizations().catch(()=>undefined);return()=>{cancelled=true}},[global]);
 function openCreateForm(){setForm(null)} function openEditForm(user:User){setForm(user)}
 async function handleSubmit(data:UserFormData){try{setSaving(true); if(form) await userService.update(form.id,data); else await userService.create(brokers?{...data,role:"BROKER"}:data); setForm(undefined);setNotice(form?"Usuário atualizado com sucesso.":"Usuário criado com sucesso.");await loadUsers()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o usuário.")}finally{setSaving(false)}}
 async function handleStatus(){if(!status)return;try{setSaving(true);await userService.updateStatus(status.id,!status.active);setNotice(status.active?"Usuário desativado com segurança.":"Usuário ativado com sucesso.");setStatus(null);await loadUsers()}catch(e){setError(e instanceof Error?e.message:"Não foi possível alterar o acesso.")}finally{setSaving(false)}}
 async function handleArchive(){if(!archive)return;try{setSaving(true);await userService.delete(archive.id);setArchive(null);setNotice("Usuário arquivado. Os dados históricos foram preservados.");await loadUsers(true)}catch(e){setError(e instanceof Error?e.message:"Não foi possível arquivar o usuário.")}finally{setSaving(false)}}
 async function handleResetPassword(){if(!reset||password.length<8){setError("A nova senha deve ter ao menos 8 caracteres.");return}try{setSaving(true);await userService.resetPassword(reset.id,password);setReset(null);setPassword("");setNotice("Senha redefinida e sessões persistidas revogadas.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível redefinir a senha.")}finally{setSaving(false)}}
 if(brokers)return <>{notice&&<p role="status" className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}<BrokersEnterprise users={users} loading={loading} error={error||(!authorized?"Seu perfil não possui acesso à Central de Usuários.":"")} canManage={canManage} onRetry={loadUsers} onCreate={openCreateForm} onEdit={openEditForm} onStatus={setStatus} onResetPassword={user=>{setReset(user);setPassword("")}}/><Modal isOpen={form!==undefined} title={form?"Editar corretor":"Novo corretor"} onClose={()=>setForm(undefined)} width="lg"><UserForm user={form} organizations={organizations} saving={saving} canAssignOrganizations={global} allowedRoles={["BROKER"]} onCancel={()=>setForm(undefined)} onSubmit={handleSubmit}/></Modal><StatusModal user={status} saving={saving} onClose={()=>setStatus(null)} onConfirm={handleStatus}/><PasswordModal user={reset} password={password} saving={saving} onPassword={setPassword} onClose={()=>setReset(null)} onConfirm={handleResetPassword}/></>;
 const cards=[["Total de usuários",metrics.total,UsersRound,"bg-blue-50 text-blue-600"],["Usuários ativos",metrics.active,UserCheck,"bg-emerald-50 text-emerald-600"],["Usuários inativos",metrics.inactive,Activity,"bg-slate-100 text-slate-600"],["Administradores",metrics.administrators,ShieldCheck,"bg-violet-50 text-violet-600"],["Gerentes",metrics.managers,UsersRound,"bg-amber-50 text-amber-600"],["Corretores",metrics.brokers,UserCheck,"bg-cyan-50 text-cyan-600"]] as const;
 return <main className="space-y-6 pb-12"><header className="relative overflow-hidden rounded-3xl border border-slate-200 bg-gradient-to-br from-white via-white to-blue-50/70 p-6 shadow-sm sm:p-8"><div className="pointer-events-none absolute right-8 top-5 h-24 w-24 rounded-full border border-blue-100"><span className="absolute -left-1 top-10 h-2 w-2 rounded-full bg-blue-500 shadow-[0_0_12px_#3b82f6]"/></div><p className="text-sm font-medium text-slate-500">Administração <span className="mx-2">/</span> <span className="text-blue-600">Usuários</span></p><div className="relative mt-5 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-blue-500"/><h1 className="text-3xl font-bold tracking-tight text-slate-900">Central de Usuários</h1></div><p className="mt-2 max-w-2xl text-slate-600">Gerencie acessos, equipes, funções e segurança da sua operação.</p></div><div className="flex gap-2"><Button variant="secondary" aria-label="Atualizar lista" onClick={()=>{setLoading(true);void loadUsers(true)}}><RefreshCw className="h-4 w-4"/>Atualizar</Button>{canManage&&<Button onClick={()=>setForm(null)}><UserPlus className="h-4 w-4"/>Novo usuário</Button>}</div></div></header>
 {notice&&<p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}
 <section aria-label="Indicadores de usuários" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label,value,Icon,color])=><Card key={label} padding="sm"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${color}`}><Icon className="h-5 w-5"/></div><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{loading?"—":value}</p></Card>)}</section>
 <Card><div className="grid gap-4 lg:grid-cols-[1fr_200px_220px_auto]"><div className="relative"><Search className="absolute left-3 top-10 h-4 w-4 text-slate-400"/><Input className="pl-10" label="Buscar por nome ou e-mail" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Digite para pesquisar"/></div><Select label="Status" value={active} onChange={e=>{setLoading(true);setActive(e.target.value);setPage(1)}} options={[{value:"",label:"Todos"},{value:"true",label:"Ativos"},{value:"false",label:"Inativos"}]}/><Select label="Função" value={role} onChange={e=>{setLoading(true);setRole(e.target.value);setPage(1)}} options={[{value:"",label:"Todas as funções"},...roles.map(r=>({value:r,label:r==="MANAGER"?"Gerente":r.includes("ADMIN")?"Administrador":"Corretor"}))]}/><Button className="self-end" variant="ghost" onClick={()=>{setLoading(true);setSearch("");setActive("");setRole("");setPage(1)}}>Limpar filtros</Button></div></Card>
 <UserTable users={users} loading={loading} error={error||(!authorized?"Seu perfil não possui acesso à Central de Usuários.":"")} canManage={canManage} onRetry={loadUsers} onCreate={openCreateForm} onView={setView} onEdit={openEditForm} onStatus={setStatus} onResetPassword={u=>{setReset(u);setPassword("")}} onArchive={setArchive}/>
 <div className="flex items-center justify-between text-sm text-slate-500"><span>Página {page} de {pages}</span><div className="flex gap-2"><Button variant="secondary" disabled={page<=1} onClick={()=>{setLoading(true);setPage(p=>p-1)}}>Anterior</Button><Button variant="secondary" disabled={page>=pages} onClick={()=>{setLoading(true);setPage(p=>p+1)}}>Próxima</Button></div></div>
 <Modal isOpen={form!==undefined} title={form?"Editar usuário":"Novo usuário"} onClose={()=>setForm(undefined)} width="lg"><UserForm user={form} organizations={organizations} saving={saving} canAssignOrganizations={global} allowedRoles={roles} onCancel={()=>setForm(undefined)} onSubmit={handleSubmit}/></Modal>
 <Modal isOpen={!!view} title="Detalhes do usuário" onClose={()=>setView(null)}><div className="space-y-4">{view&&<><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-blue-100 text-lg font-bold text-blue-700">{view.name[0]}</span><div><h3 className="font-semibold text-slate-900">{view.name}</h3><p className="text-sm text-slate-500">{view.email}</p></div></div><dl className="grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Telefone</dt><dd>{view.phone||"Não informado"}</dd></div><div><dt className="text-xs text-slate-500">Organização</dt><dd>{view.organization?.name||"Escopo global"}</dd></div><div><dt className="text-xs text-slate-500">Função</dt><dd>{view.role}</dd></div><div><dt className="text-xs text-slate-500">Status</dt><dd><Badge variant={view.active?"success":"neutral"}>{view.active?"Ativo":"Inativo"}</Badge></dd></div></dl></>}</div></Modal>
 <StatusModal user={status} saving={saving} onClose={()=>setStatus(null)} onConfirm={handleStatus}/>
 <PasswordModal user={reset} password={password} saving={saving} onPassword={setPassword} onClose={()=>setReset(null)} onConfirm={handleResetPassword}/>
 <Modal isOpen={!!archive} title="Arquivar usuário" onClose={()=>setArchive(null)}><p className="text-slate-600">O acesso será removido e o usuário sairá das listagens, mas todos os dados históricos serão preservados.</p><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={()=>setArchive(null)}>Cancelar</Button><Button variant="danger" loading={saving} onClick={handleArchive}>Arquivar usuário</Button></div></Modal>
 </main> }

function StatusModal({user,saving,onClose,onConfirm}:{user:User|null;saving:boolean;onClose:()=>void;onConfirm:()=>void}){return <Modal isOpen={!!user} title={user?.active?"Desativar usuário":"Ativar usuário"} onClose={onClose}><p className="text-slate-600">{user?.active?"O usuário perderá o acesso, mas seus dados históricos serão preservados.":"O usuário poderá voltar a acessar o sistema."}</p><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button variant={user?.active?"danger":"success"} loading={saving} onClick={onConfirm}>Confirmar</Button></div></Modal>}
function PasswordModal({user,password,saving,onPassword,onClose,onConfirm}:{user:User|null;password:string;saving:boolean;onPassword:(value:string)=>void;onClose:()=>void;onConfirm:()=>void}){return <Modal isOpen={!!user} title="Redefinir senha" onClose={onClose}><p className="mb-4 text-sm text-slate-600">Defina uma senha temporária forte para {user?.name}. A senha atual nunca é exibida.</p><Input label="Nova senha temporária" type="password" minLength={8} value={password} onChange={e=>onPassword(e.target.value)}/><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button loading={saving} onClick={onConfirm}>Redefinir com segurança</Button></div></Modal>}
