import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { CampaignFilterField, CampaignFilterOperator, CampaignStatus, Prisma } from '@prisma/client';
import { createHash } from 'crypto';
import { mkdir, readFile, writeFile } from 'fs/promises';
import { basename, join } from 'path';
import { PrismaService } from '../prisma/prisma.service';
import { CreateCampaignDto } from './dto/create-campaign.dto';
import { ListCampaignsDto } from './dto/list-campaigns.dto';
import { UpdateCampaignDto } from './dto/update-campaign.dto';
import { CampaignFilterDto } from './dto/campaign-filter.dto';
import { DestinationDto, ListMappingDto, ReviewDto, TemplateConfigurationDto } from './dto/prepare-campaign.dto';
import { CAMPAIGN_IMPORT_LIMITS, CAMPAIGN_MEDIA_LIMITS, classifyRows, detectMediaMime, escapeCsv, parseCsv } from './campaign-preparation';
import { parseMetaTemplateComponents } from '../whatsapp/templates/template-components';
import { AuditService } from '../audit/audit.service';
import { MessagingService } from '../messaging/messaging.service';

const finalCampaignStatuses = ['COMPLETED', 'COMPLETED_WITH_ERRORS', 'CANCELED'] as const;
const fieldMap: Record<string, CampaignFilterField> = { city:'CITY', source:'SOURCE', pipelineId:'PIPELINE', stageId:'STAGE', status:'STATUS', managerId:'MANAGER', brokerId:'BROKER', date:'DATE', temperature:'TEMPERATURE', archived:'ARCHIVED' };
const operatorMap: Record<string, CampaignFilterOperator> = { equals:'EQUALS', in:'IN', between:'BETWEEN', gte:'GTE', lte:'LTE', contains:'CONTAINS', is:'IS' };

const safeUserSelect = { id: true, name: true, email: true, phone: true, role: true, active: true, organizationId: true } satisfies Prisma.UserSelect;
const campaignInclude = { filters: { orderBy: { createdAt: 'asc' as const } }, createdBy: { select: safeUserSelect }, whatsappAccount: { select: { id:true,name:true,provider:true,status:true,tokenConfigured:true,deletedAt:true } }, whatsappTemplate:true, import:true, agents:{include:{user:{select:safeUserSelect}},orderBy:{position:'asc' as const}}, _count: { select: { recipients: true, filters: true } } } satisfies Prisma.CampaignInclude;

@Injectable()
export class CampaignsService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService,private readonly messaging:MessagingService) {}

  async validateOperational(userId:string,id:string){
    const c=await this.getCampaign(userId,id); const reasons:{code:string;message:string}[]=[];
    if(c.archivedAt) reasons.push({code:'CAMPAIGN_ARCHIVED',message:'A campanha está arquivada'});
    if(!['DRAFT','READY','SCHEDULED','PAUSED'].includes(c.status)) reasons.push({code:'STATUS_INVALID',message:'O status atual não permite esta operação'});
    const a=c.whatsappAccount;
    if(!a||a.provider!=='META_CLOUD') reasons.push({code:'META_ACCOUNT_REQUIRED',message:'Selecione uma conta oficial Meta Cloud'});
    else if(a.status!=='ACTIVE'||!a.tokenConfigured||a.deletedAt) reasons.push({code:'ACCOUNT_INACTIVE',message:'A conta oficial não está ativa e configurada'});
    const t=c.whatsappTemplate;
    if(!t||t.whatsappAccountId!==c.whatsappAccountId||t.status!=='APPROVED'||!t.isActive||t.archivedAt||t.deletedAt||!t.metaTemplateId) reasons.push({code:'TEMPLATE_UNAVAILABLE',message:'O template aprovado não está disponível para esta conta'});
    if(!c.listConfirmedAt||!c.reviewedAt||!c.import?.validRows) reasons.push({code:'LIST_NOT_READY',message:'Confirme e revise uma lista com destinatários válidos'});
    if(t){const parsed=parseMetaTemplateComponents(t.components);if(parsed.variables.length!==((c.variableMappings as unknown[]|null)?.length||0))reasons.push({code:'VARIABLE_MAPPING_INVALID',message:'Revise o mapeamento das variáveis'});if(['IMAGE','VIDEO','DOCUMENT'].includes(parsed.headerType)&&!c.mediaStorageKey)reasons.push({code:'MEDIA_REQUIRED',message:'O template exige mídia'});}
    if(!c.destinationConfig) reasons.push({code:'DESTINATION_REQUIRED',message:'Configure o destino da campanha'});
    const valid=await this.prisma.campaignRecipient.count({where:{campaignId:id,organizationId:c.organizationId,status:{in:['PENDING','QUEUED','FAILED_RETRYABLE']},externalMessageId:null}}); if(!valid) reasons.push({code:'NO_VALID_RECIPIENTS',message:'Não há destinatários válidos pendentes'});
    if(!reasons.length&&c.status==='DRAFT') await this.transition(c,userId,'READY','Validação operacional concluída');
    return {valid:!reasons.length,reasons,validRecipients:valid,status:reasons.length?c.status:'READY'};
  }

  async start(userId:string,id:string){const c=await this.getCampaign(userId,id);if(!['READY','SCHEDULED','PAUSED'].includes(c.status))throw new BadRequestException('A campanha não pode ser iniciada neste status');const validation=await this.validateOperational(userId,id);if(!validation.valid)throw new BadRequestException({message:'Campanha inválida para envio',reasons:validation.reasons});const claimed=await this.prisma.campaign.updateMany({where:{id,organizationId:c.organizationId,status:c.status},data:{status:'QUEUED',scheduledAt:null,startedAt:c.startedAt||new Date()}});if(!claimed.count)throw new BadRequestException('A campanha já foi iniciada por outro processo');await this.messaging.feedCampaign(id,c.organizationId);await this.auditTransition(c,userId,'QUEUED','Destinatários enfileirados');return this.findOne(userId,id);}
  async schedule(userId:string,id:string,scheduledAt:string){const c=await this.getCampaign(userId,id);if(!['READY','SCHEDULED'].includes(c.status))throw new BadRequestException('Apenas campanhas prontas ou agendadas podem ser agendadas');const when=new Date(scheduledAt);if(!Number.isFinite(when.getTime())||when<=new Date())throw new BadRequestException('A data deve estar no futuro');const v=await this.validateOperational(userId,id);if(!v.valid)throw new BadRequestException({message:'Campanha inválida para agendamento',reasons:v.reasons});await this.prisma.campaign.update({where:{id},data:{status:'SCHEDULED',scheduledAt:when,scheduledByUserId:userId}});await this.auditTransition(c,userId,'SCHEDULED','Campanha agendada');return this.findOne(userId,id);}
  async pause(userId:string,id:string){const c=await this.getCampaign(userId,id);if(!['QUEUED','RUNNING'].includes(c.status))throw new BadRequestException('Somente campanha em execução pode ser pausada');await this.prisma.$transaction([this.prisma.campaign.update({where:{id},data:{status:'PAUSED',pausedAt:new Date(),pausedByUserId:userId}}),this.prisma.messageQueue.updateMany({where:{campaignId:id,organizationId:c.organizationId,status:{in:['PENDING','RETRYING']}},data:{status:'WAITING'}})]);await this.auditTransition(c,userId,'PAUSED','Campanha pausada');return this.findOne(userId,id);}
  async resume(userId:string,id:string){const c=await this.getCampaign(userId,id);if(c.status!=='PAUSED')throw new BadRequestException('Somente campanha pausada pode ser retomada');const v=await this.validateOperational(userId,id);if(!v.valid)throw new BadRequestException({message:'Campanha inválida para retomada',reasons:v.reasons});await this.prisma.$transaction([this.prisma.campaign.update({where:{id},data:{status:'RUNNING',resumedAt:new Date(),resumedByUserId:userId}}),this.prisma.messageQueue.updateMany({where:{campaignId:id,organizationId:c.organizationId,status:'WAITING'},data:{status:'PENDING'}})]);await this.messaging.feedCampaign(id,c.organizationId);await this.auditTransition(c,userId,'RUNNING','Campanha retomada');return this.findOne(userId,id);}
  async progress(userId:string,id:string){const c=await this.getCampaign(userId,id);const grouped=await this.prisma.campaignRecipient.groupBy({by:['status'],where:{campaignId:id,organizationId:c.organizationId},_count:{_all:true}});const raw=Object.fromEntries(grouped.map(x=>[x.status,x._count._all]));const total=Object.values(raw).reduce((a,b)=>a+b,0),read=raw.READ||0,delivered=(raw.DELIVERED||0)+read,sent=(raw.SENT||0)+delivered,pending=raw.PENDING||0,queued=raw.QUEUED||0,processing=raw.PROCESSING||0,failedRetryable=raw.FAILED_RETRYABLE||0,failedPermanent=(raw.FAILED_PERMANENT||0)+(raw.FAILED||0),canceled=raw.CANCELED||0,unknown=raw.UNKNOWN||0;const completed=sent+failedPermanent+canceled+(raw.SKIPPED||0);const started=c.startedAt?.getTime(),elapsed=started?Math.max(1,(Date.now()-started)/1000):0,velocity=started?sent/elapsed:0;return {campaignId:id,status:c.status,total,valid:c.import?.validRows||c.totalContacts,queued,processing,sent,delivered,read,failedRetryable,failedPermanent,canceled,pending,unknown,completed,percentCompleted:total?Math.round(completed*10000/total)/100:0,averagePerSecond:Math.round(velocity*100)/100,estimatedCompletionAt:velocity&&pending+queued+processing?new Date(Date.now()+((pending+queued+processing)/velocity)*1000):null,updatedAt:c.updatedAt};}
  async recipientsPage(userId:string,id:string,q:{status?:string;search?:string;assignedUserId?:string;error?:string;attempt?:number;page?:number;limit?:number}){const c=await this.getCampaign(userId,id);const page=Math.max(1,Number(q.page)||1),take=Math.min(100,Math.max(1,Number(q.limit)||20));const where:Prisma.CampaignRecipientWhereInput={campaignId:id,organizationId:c.organizationId,...(q.status?{status:q.status as never}:{}),...(q.assignedUserId?{assignedUserId:q.assignedUserId}:{}),...(q.error?{OR:[{errorCategory:{contains:q.error,mode:'insensitive'}},{errorMessage:{contains:q.error,mode:'insensitive'}}]}:{}),...(q.attempt!==undefined?{attemptCount:Number(q.attempt)}:{}),...(q.search?{OR:[{name:{contains:q.search,mode:'insensitive'}},{phone:{contains:q.search}}]}:{})};const [items,total]=await this.prisma.$transaction([this.prisma.campaignRecipient.findMany({where,select:{id:true,name:true,phone:true,status:true,assignedUserId:true,assignedUser:{select:{id:true,name:true}},attemptCount:true,queuedAt:true,processingAt:true,sentAt:true,deliveredAt:true,readAt:true,failedAt:true,errorCategory:true,errorMessage:true},skip:(page-1)*take,take,orderBy:{createdAt:'asc'}}),this.prisma.campaignRecipient.count({where})]);return{items:items.map(x=>({...x,phone:x.phone.replace(/.(?=.{4})/g,'*')})),meta:{page,limit:take,total,totalPages:Math.ceil(total/take)}};}
  async report(userId:string,id:string){const c=await this.getCampaign(userId,id);const progress=await this.progress(userId,id);const [errors,agents,attempts]=await Promise.all([this.prisma.campaignRecipient.groupBy({by:['errorCategory'],where:{campaignId:id,organizationId:c.organizationId,errorCategory:{not:null}},orderBy:{errorCategory:'asc'},_count:{_all:true}}),this.prisma.campaignRecipient.groupBy({by:['assignedUserId'],where:{campaignId:id,organizationId:c.organizationId,assignedUserId:{not:null}},orderBy:{assignedUserId:'asc'},_count:{_all:true}}),this.prisma.campaignRecipient.aggregate({where:{campaignId:id,organizationId:c.organizationId},_sum:{attemptCount:true},_avg:{attemptCount:true}})]);return{...progress,startedAt:c.startedAt,finishedAt:c.finishedAt,durationSeconds:c.startedAt?Math.max(0,Math.round(((c.finishedAt||new Date()).getTime()-c.startedAt.getTime())/1000)):0,rates:{sent:progress.total?progress.sent/progress.total:0,delivered:progress.sent?progress.delivered/progress.sent:0,read:progress.delivered?progress.read/progress.delivered:0},errorsByCategory:errors.map(x=>({category:x.errorCategory,count:x._count._all})),distributionByAgent:agents.map(x=>({assignedUserId:x.assignedUserId,count:x._count._all})),attempts};}
  async exportResults(userId:string,id:string){const c=await this.getCampaign(userId,id);const rows=await this.prisma.campaignRecipient.findMany({where:{campaignId:id,organizationId:c.organizationId},select:{name:true,phone:true,status:true,assignedUser:{select:{name:true}},attemptCount:true,sentAt:true,deliveredAt:true,readAt:true,errorCategory:true,errorMessage:true},orderBy:{createdAt:'asc'}});const header=['nome','telefone','status','corretor','tentativas','enviado_em','entregue_em','lido_em','categoria_erro','erro'];return [header.map(escapeCsv).join(','),...rows.map(r=>[r.name,r.phone.replace(/.(?=.{4})/g,'*'),r.status,r.assignedUser?.name,r.attemptCount,r.sentAt?.toISOString(),r.deliveredAt?.toISOString(),r.readAt?.toISOString(),r.errorCategory,r.errorMessage].map(escapeCsv).join(','))].join('\r\n');}
  async events(userId:string,id:string){const c=await this.getCampaign(userId,id);return this.prisma.messageLog.findMany({where:{campaignId:id,queue:{organizationId:c.organizationId}},orderBy:{createdAt:'desc'},take:100});}
  async retryRecipient(userId:string,id:string,recipientId:string){const c=await this.getCampaign(userId,id);const r=await this.prisma.campaignRecipient.findFirst({where:{id:recipientId,campaignId:id,organizationId:c.organizationId,status:{in:['FAILED_RETRYABLE','FAILED_PERMANENT','UNKNOWN']}}});if(!r||r.externalMessageId)throw new BadRequestException('Destinatário não é elegível para retentativa segura');await this.prisma.$transaction([this.prisma.campaignRecipient.update({where:{id:r.id},data:{status:'QUEUED',nextRetryAt:null,errorMessage:null}}),this.prisma.messageQueue.update({where:{campaignId_recipientId:{campaignId:id,recipientId:r.id}},data:{status:'RETRYING',scheduledAt:new Date(),lastError:null}})]);return{success:true};}

  private async transition(c:any,userId:string,status:CampaignStatus,reason:string){await this.prisma.campaign.update({where:{id:c.id},data:{status}});await this.auditTransition(c,userId,status,reason);}
  private async auditTransition(c:any,userId:string,status:CampaignStatus,reason:string){await this.audit.record({organizationId:c.organizationId,actorUserId:userId,module:'campaigns',entityType:'Campaign',entityId:c.id,action:'campaign.status.changed',before:{status:c.status},after:{status},metadata:{reason}});}

  async findAll(userId: string, query: ListCampaignsDto) {
    const organizationId = await this.getOrganizationId(userId);
    const page = query.page ?? 1;
    const limit = query.limit ?? 10;
    const where: Prisma.CampaignWhereInput = {
      organizationId,
      deletedAt: query.deleted ? { not: null } : null,
      ...(query.archived ? { archivedAt: { not: null } } : { archivedAt: null }),
      ...(query.search ? { OR: [{ name: { contains: query.search, mode: 'insensitive' } }, { description: { contains: query.search, mode: 'insensitive' } }] } : {}),
      ...(query.status ? { status: query.status } : {}),
      ...(query.campaignType ? { campaignType: query.campaignType } : {}),
      ...(query.from || query.to ? { createdAt: { ...(query.from ? { gte: new Date(query.from) } : {}), ...(query.to ? { lte: new Date(query.to) } : {}) } } : {}),
    };
    const [items, total] = await this.prisma.$transaction([
      this.prisma.campaign.findMany({ where, include: campaignInclude, orderBy: { createdAt: 'desc' }, skip: (page - 1) * limit, take: limit }),
      this.prisma.campaign.count({ where }),
    ]);
    return { items, meta: { total, page, limit, totalPages: Math.ceil(total / limit) } };
  }

  async findOne(userId: string, id: string) { return this.getCampaign(userId, id, true); }

  async create(userId: string, data: CreateCampaignDto) {
    const organizationId = await this.getOrganizationId(userId);
    this.validateName(data.name);
    this.validateFilters(data.filters ?? []);
    if (data.whatsappAccountId) await this.assertMetaAccount(organizationId,data.whatsappAccountId);
    return this.prisma.campaign.create({ data: { organizationId, createdById: userId, updatedById:userId, name: data.name.trim(), description: data.description?.trim() || null, internalNotes:data.internalNotes?.trim()||null, campaignType: data.campaignType, category:data.campaignType, whatsappAccountId:data.whatsappAccountId, status: 'DRAFT', filters: { create: this.mapFilters(data.filters ?? []) } }, include: campaignInclude });
  }

  async saveStep(userId:string,id:string,currentStep:number) { await this.getCampaign(userId,id); return this.prisma.campaign.update({where:{id},data:{currentStep,updatedById:userId},include:campaignInclude}); }
  async uploadList(userId:string,id:string,file:{buffer:Buffer;originalname:string;mimetype:string;size:number}) {
    const campaign=await this.getCampaign(userId,id); if(campaign.status!=='DRAFT') throw new BadRequestException('A lista só pode ser alterada enquanto a campanha estiver em rascunho');
    if(!file?.buffer?.length) throw new BadRequestException('Selecione um arquivo não vazio'); if(file.size>CAMPAIGN_IMPORT_LIMITS.maxBytes) throw new BadRequestException('O arquivo excede o limite de 10 MB');
    const magic=file.buffer.subarray(0,4).toString('hex'); const isCsv=!file.buffer.includes(0) && /[,;\n\r]/.test(file.buffer.subarray(0,1024).toString('utf8')); const isExcel=magic==='504b0304'||magic==='d0cf11e0';
    if(isExcel) throw new BadRequestException('Nesta versão, a importação aceita somente arquivos CSV'); if(!isCsv) throw new BadRequestException('Selecione um arquivo CSV válido');
    const parsed=parseCsv(file.buffer); const sha256=createHash('sha256').update(file.buffer).digest('hex'); const safeName=basename(file.originalname).replace(/[^\p{L}\p{N}._-]/gu,'_').slice(0,180)||'lista.csv';
    const dir=join(process.cwd(),'data','campaign-imports',campaign.organizationId); await mkdir(dir,{recursive:true}); const storageKey=join(dir,`${id}-${sha256}.csv`); await writeFile(storageKey,file.buffer,{flag:'wx'}).catch(async(e:NodeJS.ErrnoException)=>{if(e.code!=='EEXIST') throw e;});
    const imported=await this.prisma.campaignImport.upsert({where:{campaignId:id},create:{campaignId:id,organizationId:campaign.organizationId,storageKey,originalName:safeName,mimeType:'text/csv',size:file.size,sha256,headers:parsed.headers,sample:parsed.rows.slice(0,CAMPAIGN_IMPORT_LIMITS.sampleRows),totalRows:parsed.rows.length,createdById:userId},update:{storageKey,originalName:safeName,mimeType:'text/csv',size:file.size,sha256,headers:parsed.headers,sample:parsed.rows.slice(0,CAMPAIGN_IMPORT_LIMITS.sampleRows),totalRows:parsed.rows.length,status:'UPLOADED',errorReason:null}});
    return {...imported,phoneCandidates:parsed.headers.filter(h=>/telefone|phone|celular|whats/i.test(h.name)).map(h=>h.id),nameCandidates:parsed.headers.filter(h=>/nome|name|cliente/i.test(h.name)).map(h=>h.id)};
  }
  async mapAndAnalyze(userId:string,id:string,data:ListMappingDto){ const campaign=await this.getCampaign(userId,id); const imp=campaign.import; if(!imp) throw new BadRequestException('Envie uma planilha antes de higienizar'); const parsed=parseCsv(await readFile(imp.storageKey)); const ids=new Set(parsed.headers.map(h=>h.id)); if(!ids.has(data.phoneColumn)||data.includedColumns.some(c=>!ids.has(c))||(data.nameColumn&&!ids.has(data.nameColumn))) throw new BadRequestException('Mapeamento contém uma coluna inexistente');
    const classified=classifyRows(parsed.rows,data.phoneColumn,data.nameColumn); await this.prisma.$transaction(async tx=>{await tx.campaignRecipient.deleteMany({where:{campaignId:id}}); for(let start=0;start<classified.length;start+=CAMPAIGN_IMPORT_LIMITS.batchSize){const batch=classified.slice(start,start+CAMPAIGN_IMPORT_LIMITS.batchSize);await tx.campaignRecipient.createMany({data:batch.map(r=>({campaignId:id,organizationId:campaign.organizationId,originalRowNumber:r.index,originalData:Object.fromEntries(data.includedColumns.map(c=>[c,r.data[c]])),phoneOriginal:r.data[data.phoneColumn]||null,phone:r.phone||'',name:'name'in r?r.name:null,status:r.status==='VALID'?'PENDING':r.status==='DUPLICATE'?'SKIPPED':'FAILED',invalidReason:r.reason}))});}}
    ); const valid=classified.filter(r=>r.status==='VALID').length, invalid=classified.filter(r=>r.status==='INVALID').length, duplicate=classified.filter(r=>r.status==='DUPLICATE').length;
    await this.prisma.campaignImport.update({where:{campaignId:id},data:{status:'READY',columnMapping:data as unknown as Prisma.InputJsonValue,validRows:valid,invalidRows:invalid,duplicateRows:duplicate,ddiCorrectedRows:classified.filter(r=>r.ddiCorrected).length,missingNameRows:data.nameColumn?classified.filter(r=>!r.data[data.nameColumn!]?.trim()).length:classified.length}}); await this.prisma.campaign.update({where:{id},data:{totalContacts:valid,listConfirmedAt:data.confirmed?new Date():null,currentStep:2,updatedById:userId}}); return this.listSummary(userId,id); }
  async listSummary(userId:string,id:string){const c=await this.getCampaign(userId,id);if(!c.import)throw new BadRequestException('Lista ainda não enviada');return {status:c.import.status,total:c.import.totalRows,valid:c.import.validRows,invalid:c.import.invalidRows,duplicate:c.import.duplicateRows,ddiCorrected:c.import.ddiCorrectedRows,withoutName:c.import.missingNameRows,ready:c.import.validRows};}
  async recipientSample(userId:string,id:string,kind:'valid'|'invalid'|'duplicates',page=1,limit=10){const campaign=await this.getCampaign(userId,id);const status=kind==='valid'?'PENDING':kind==='duplicates'?'SKIPPED':'FAILED';const take=Math.min(Math.max(limit,1),50),where={campaignId:id,organizationId:campaign.organizationId,status} as const;const [items,total]=await this.prisma.$transaction([this.prisma.campaignRecipient.findMany({where,select:{id:true,originalRowNumber:true,originalData:true,phoneOriginal:true,phone:true,name:true,status:true,invalidReason:true},orderBy:{originalRowNumber:'asc'},skip:(Math.max(page,1)-1)*take,take}),this.prisma.campaignRecipient.count({where})]);return{items,meta:{page:Math.max(page,1),limit:take,total,totalPages:Math.ceil(total/take)}};}
  async exportList(userId:string,id:string,kind:'invalid'|'duplicates'|'clean'){await this.getCampaign(userId,id);const status=kind==='clean'?'PENDING':kind==='duplicates'?'SKIPPED':'FAILED';const rows=await this.prisma.campaignRecipient.findMany({where:{campaignId:id,status},orderBy:{originalRowNumber:'asc'},take:CAMPAIGN_IMPORT_LIMITS.maxRows});const originalKeys=[...new Set(rows.flatMap(r=>Object.keys((r.originalData||{}) as object)))];const header=[...originalKeys,'telefone_normalizado','status','motivo'];return [header.map(escapeCsv).join(','),...rows.map(r=>[...originalKeys.map(k=>((r.originalData||{}) as Record<string,unknown>)[k]),r.phone,status==='PENDING'?'VALID':status==='SKIPPED'?'DUPLICATE':'INVALID',r.invalidReason].map(escapeCsv).join(','))].join('\r\n');}
  async configureTemplate(userId:string,id:string,data:TemplateConfigurationDto){const c=await this.getCampaign(userId,id);if(!c.whatsappAccountId)throw new BadRequestException('Selecione uma conta oficial primeiro');const template=await this.prisma.whatsappTemplate.findFirst({where:{id:data.whatsappTemplateId,organizationId:c.organizationId,whatsappAccountId:c.whatsappAccountId,status:'APPROVED',isActive:true,archivedAt:null,deletedAt:null,metaTemplateId:{not:null}}});if(!template||template.category!==c.category)throw new BadRequestException('Template indisponível ou incompatível com a campanha');const normalized=parseMetaTemplateComponents(template.components),variables=normalized.variables,keys=new Set<string>();const included=new Set(((c.import?.columnMapping as {includedColumns?:string[]}|null)?.includedColumns)||[]);for(const m of data.variableMappings){const key=`${m.component}:${m.position}:${m.buttonIndex??''}`;if(keys.has(key))throw new BadRequestException('Variável duplicada');keys.add(key);if(m.component==='BUTTON'&&m.buttonIndex===undefined)throw new BadRequestException('Variáveis de botão exigem buttonIndex');if(m.sourceType==='FIXED'&&!m.fixedValue?.trim())throw new BadRequestException('Valor fixo não pode ficar vazio');if(m.sourceType==='COLUMN'&&(!m.sourceColumn||!included.has(m.sourceColumn)))throw new BadRequestException('A coluna mapeada não existe ou foi excluída');if(m.sourceType==='SYSTEM_FIELD')throw new BadRequestException('Nenhum campo de sistema está disponível para este template');}for(const v of variables){if(!keys.has(`${v.component}:${v.position}:${v.buttonIndex??''}`))throw new BadRequestException('Todas as variáveis obrigatórias devem possuir um único mapeamento');}await this.prisma.campaign.update({where:{id},data:{whatsappTemplateId:template.id,variableMappings:data.variableMappings as unknown as Prisma.InputJsonValue,currentStep:3,updatedById:userId}});return this.findOne(userId,id);}
  async uploadMedia(userId:string,id:string,file:{buffer:Buffer;originalname:string;size:number}){const c=await this.getCampaign(userId,id);if(!c.whatsappTemplate)throw new BadRequestException('Selecione o template antes de anexar mídia');const headerType=parseMetaTemplateComponents(c.whatsappTemplate.components).headerType as keyof typeof CAMPAIGN_MEDIA_LIMITS;if(!CAMPAIGN_MEDIA_LIMITS[headerType])throw new BadRequestException('Este template não permite mídia no cabeçalho');if(!file?.buffer?.length)throw new BadRequestException('Selecione um arquivo de mídia não vazio');const mime=detectMediaMime(file.buffer),limits=CAMPAIGN_MEDIA_LIMITS[headerType];if(!mime||!(limits.mimeTypes as readonly string[]).includes(mime))throw new BadRequestException(`A mídia é incompatível com o cabeçalho ${headerType}`);if(file.size>limits.maxBytes)throw new BadRequestException(`A mídia excede o limite para ${headerType}`);const sha256=createHash('sha256').update(file.buffer).digest('hex'),name=basename(file.originalname).replace(/[^\p{L}\p{N}._-]/gu,'_').slice(0,180)||'midia',dir=join(process.cwd(),'data','campaign-media',c.organizationId),storageKey=join(dir,`${id}-${sha256}`);await mkdir(dir,{recursive:true});await writeFile(storageKey,file.buffer,{flag:'wx'}).catch((e:NodeJS.ErrnoException)=>{if(e.code!=='EEXIST')throw e;});return this.prisma.campaign.update({where:{id},data:{mediaStorageKey:storageKey,mediaOriginalName:name,mediaMimeType:mime,mediaSize:file.size,mediaSha256:sha256,mediaMetaId:c.mediaSha256===sha256?undefined:null,mediaUploadedAt:c.mediaSha256===sha256?undefined:null,mediaExpiresAt:c.mediaSha256===sha256?undefined:null,mediaUploadStatus:c.mediaSha256===sha256?undefined:null,mediaUploadError:c.mediaSha256===sha256?undefined:null,updatedById:userId},include:campaignInclude});}
  async configureDestination(userId:string,id:string,data:DestinationDto){const c=await this.getCampaign(userId,id);if(data.mode==='FIXED_URL'&&!data.fixedUrl?.startsWith('https://'))throw new BadRequestException('Informe uma URL HTTPS válida');const ids=data.mode==='ROUND_ROBIN'?data.agents?.map(a=>a.userId)||[]:data.mode==='AGENT_FIXED'&&data.agentId?[data.agentId]:[];if(data.mode!=='FIXED_URL'&&!ids.length)throw new BadRequestException('Selecione ao menos um corretor');if(ids.length){const count=await this.prisma.user.count({where:{id:{in:[...new Set(ids)]},organizationId:c.organizationId,active:true,status:'ACTIVE',deletedAt:null,role:{in:['CORRETOR','BROKER']}}});if(count!==new Set(ids).size)throw new NotFoundException('Corretor não encontrado');}await this.prisma.$transaction(async tx=>{await tx.campaignAgent.deleteMany({where:{campaignId:id}});if(data.agents?.length)await tx.campaignAgent.createMany({data:data.agents.map(a=>({campaignId:id,userId:a.userId,position:a.position,weight:a.weight||1,active:a.active??true}))});await tx.campaign.update({where:{id},data:{destinationConfig:{...data,strategy:data.mode==='ROUND_ROBIN'?'ROUND_ROBIN':undefined,initialIndex:data.initialIndex??0,configuredAt:new Date().toISOString()} as unknown as Prisma.InputJsonValue,updatedById:userId}});});return this.findOne(userId,id);}
  async review(userId:string,id:string,data:ReviewDto){const c=await this.getCampaign(userId,id);if(!data.confirmed||!c.listConfirmedAt||!c.import?.validRows||!c.whatsappTemplateId)throw new BadRequestException('Confirme a lista, configure o template e revise os dados');await this.assertMetaAccount(c.organizationId,c.whatsappAccountId!);const headerType=parseMetaTemplateComponents(c.whatsappTemplate!.components).headerType;if(['IMAGE','VIDEO','DOCUMENT'].includes(headerType)&&!c.mediaStorageKey)throw new BadRequestException(`O template exige mídia ${headerType}`);await this.configureTemplate(userId,id,{whatsappTemplateId:c.whatsappTemplateId,variableMappings:(c.variableMappings||[]) as never[]});return this.prisma.campaign.update({where:{id},data:{status:'DRAFT',currentStep:4,reviewedAt:new Date(),updatedById:userId},include:campaignInclude});}

  async update(userId: string, id: string, data: UpdateCampaignDto) {
    const current = await this.getCampaign(userId, id);
    if (finalCampaignStatuses.includes(current.status as (typeof finalCampaignStatuses)[number])) throw new BadRequestException('Campanhas concluídas ou canceladas não podem ser editadas livremente');
    if (data.name !== undefined) this.validateName(data.name);
    if (data.filters) this.validateFilters(data.filters);
    if (data.whatsappAccountId) await this.assertMetaAccount(current.organizationId,data.whatsappAccountId);
    await this.prisma.$transaction(async (tx) => {
      await tx.campaign.update({ where: { id }, data: { name: data.name?.trim(), description: data.description === undefined ? undefined : data.description?.trim() || null, internalNotes:data.internalNotes===undefined?undefined:data.internalNotes?.trim()||null, campaignType: data.campaignType, category:data.campaignType, whatsappAccountId:data.whatsappAccountId===undefined?undefined:data.whatsappAccountId||null, status: data.status, scheduledAt: data.scheduledAt === undefined ? undefined : data.scheduledAt ? new Date(data.scheduledAt) : null } });
      if (data.filters) { await tx.campaignFilter.deleteMany({ where: { campaignId: id } }); if (data.filters.length) await tx.campaignFilter.createMany({ data: this.mapFilters(data.filters).map((f) => ({ ...f, campaignId: id })) }); }
    });
    return this.findOne(userId, id);
  }

  async remove(userId: string, id: string) { await this.getCampaign(userId, id); await this.prisma.campaign.update({ where: { id }, data: { deletedAt: new Date() } }); return { success: true }; }
  async restore(userId: string, id: string) { const organizationId = await this.getOrganizationId(userId); const campaign = await this.prisma.campaign.findFirst({ where: { id, organizationId, deletedAt: { not: null } } }); if (!campaign) throw new NotFoundException('Campanha excluída não encontrada'); await this.prisma.campaign.update({ where: { id }, data: { deletedAt: null } }); return this.findOne(userId, id); }
  async archive(userId: string, id: string, archived: boolean) { await this.getCampaign(userId, id); await this.prisma.campaign.update({ where: { id }, data: { archivedAt: archived ? new Date() : null } }); return this.findOne(userId, id); }
  async cancel(userId: string, id: string, reason?:string) { const campaign = await this.getCampaign(userId, id); if (finalCampaignStatuses.includes(campaign.status as (typeof finalCampaignStatuses)[number])) throw new BadRequestException('Campanha não pode ser cancelada neste status'); const now=new Date();await this.prisma.$transaction([this.prisma.campaign.update({ where: { id }, data: { status: 'CANCELED', finishedAt:now,canceledAt:now,canceledByUserId:userId } }),this.prisma.messageQueue.updateMany({where:{campaignId:id,organizationId:campaign.organizationId,status:{in:['PENDING','WAITING','RETRYING']}},data:{status:'CANCELED',finishedAt:now}}),this.prisma.campaignRecipient.updateMany({where:{campaignId:id,organizationId:campaign.organizationId,status:{in:['PENDING','QUEUED','FAILED_RETRYABLE']}},data:{status:'CANCELED',canceledAt:now}})]);await this.auditTransition(campaign,userId,'CANCELED',reason||'Campanha cancelada'); return this.findOne(userId, id); }
  async estimate(userId: string, filters: CampaignFilterDto[] = []) { await this.getOrganizationId(userId); this.validateFilters(filters); return { estimatedContacts: Math.max(12, filters.length * 37) }; }

  private async getOrganizationId(userId: string) { const user = await this.prisma.user.findFirst({ where: { id: userId, active: true, deletedAt: null } }); if (!user?.organizationId) throw new ForbiddenException('Usuário sem organização ativa'); return user.organizationId; }
  private async assertMetaAccount(organizationId:string,id:string){const account=await this.prisma.whatsappAccount.findFirst({where:{id,organizationId,provider:'META_CLOUD',status:'ACTIVE',tokenConfigured:true,deletedAt:null}});if(!account)throw new NotFoundException('Conta oficial ativa não encontrada');return account;}
  private async getCampaign(userId: string, id: string, withDeleted = false) { const organizationId = await this.getOrganizationId(userId); const campaign = await this.prisma.campaign.findFirst({ where: { id, organizationId, ...(withDeleted ? {} : { deletedAt: null }) }, include: campaignInclude }); if (!campaign) throw new NotFoundException('Campanha não encontrada'); return campaign; }
  private validateName(name?: string) { if (!name?.trim()) throw new BadRequestException('Nome da campanha é obrigatório'); }
  private validateFilters(filters: CampaignFilterDto[]) { for (const filter of filters) { if (!fieldMap[filter.field] || !operatorMap[filter.operator]) throw new BadRequestException('Filtro de campanha inválido'); if (filter.value === undefined || filter.value === null || filter.value === '') throw new BadRequestException('Valor do filtro é obrigatório'); } }
  private mapFilters(filters: CampaignFilterDto[]) { return filters.map((filter) => ({ field: fieldMap[filter.field], operator: operatorMap[filter.operator], value: filter.value as Prisma.InputJsonValue })); }
}
