import { PipelineBoard, PipelineStage } from "@/types/pipeline-board";
import { LeadCard } from "./LeadCard";

export type DropTarget = { cardId: string; stageId: string; index: number };

function KeyboardMoveControls({ cardId, stages, currentStageId, onMove }: { cardId: string; stages: PipelineStage[]; currentStageId: string; onMove: (target: DropTarget) => void }) {
  return <label className="mt-2 grid gap-1 text-xs text-slate-400"><span>Mover lead sem mouse</span><select aria-label="Mover lead para etapa" defaultValue="" className="rounded-lg border border-slate-700 bg-slate-900 p-2 text-slate-100 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/40" onChange={(event) => { const stageId = event.target.value; if (!stageId) return; const stage = stages.find((item) => item.id === stageId); if (stage) onMove({ cardId, stageId, index: stage.cards.length }); event.currentTarget.value = ""; }}><option value="">Escolha uma etapa</option>{stages.filter((stage) => stage.id !== currentStageId).map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select></label>;
}

function KanbanColumn({ stage, stages, activeCardId, onDragStart, onDropCard, onOpenCard }: { stage: PipelineStage; stages: PipelineStage[]; activeCardId: string; onDragStart: (cardId: string) => void; onDropCard: (target: DropTarget) => void; onOpenCard: (cardId: string) => void }) {
  const markerStyle = stage.color ? { borderTopColor: stage.color } : undefined;
  return <section aria-label={`Etapa ${stage.name}`} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const cardId = event.dataTransfer.getData("text/pipeline-card"); if (cardId) onDropCard({ cardId, stageId: stage.id, index: stage.cards.length }); }} className="flex min-h-[28rem] w-[20rem] shrink-0 flex-col rounded-2xl border border-slate-800 bg-slate-900/80 p-4"><div className="border-t-4 pt-3" style={markerStyle}><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-white">{stage.name}</h2><span className="rounded-full bg-slate-800 px-3 py-1 text-xs text-slate-200">{stage.cards.length}</span></div></div><div className="mt-4 flex flex-1 flex-col gap-3">{stage.cards.length === 0 ? <div className="rounded-xl border border-dashed border-slate-700 p-6 text-center text-sm text-slate-500">Etapa sem cards. Arraste leads para cá.</div> : stage.cards.map((card, index) => <div key={card.id} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); event.stopPropagation(); const cardId = event.dataTransfer.getData("text/pipeline-card"); if (cardId) onDropCard({ cardId, stageId: stage.id, index }); }} onDragStart={(event) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/pipeline-card", card.id); onDragStart(card.id); }} onDragEnd={() => onDragStart("")}><LeadCard card={{ ...card, stageId: stage.id }} dragging={activeCardId === card.id} onOpen={() => onOpenCard(card.id)} /><KeyboardMoveControls cardId={card.id} stages={stages} currentStageId={stage.id} onMove={onDropCard} /></div>)}</div></section>;
}

export function KanbanBoard({ board, activeCardId, moving, onDragStart, onDropCard, onOpenCard }: { board: PipelineBoard; activeCardId: string; moving: boolean; onDragStart: (cardId: string) => void; onDropCard: (target: DropTarget) => void; onOpenCard: (cardId: string) => void }) {
  return <div aria-busy={moving} className="relative"><div className="flex gap-4 overflow-x-auto pb-4" role="list" aria-label="Kanban do pipeline">{board.stages.map((stage) => <KanbanColumn key={stage.id} stage={stage} stages={board.stages} activeCardId={activeCardId} onDragStart={onDragStart} onDropCard={onDropCard} onOpenCard={onOpenCard} />)}</div>{moving && <div className="absolute right-4 top-4 rounded-full border border-blue-800 bg-blue-950 px-3 py-1 text-sm text-blue-100">Salvando movimentação...</div>}</div>;
}
