import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { DealActivityStatus, DealStatus, Prisma } from '@prisma/client';
import { AccessContext, AccessContextService, AuthenticatedUserRef } from '../auth/access-context.service';
import { PrismaService } from '../prisma/prisma.service';
import { ActivityDto, AssignDto, ChangePipelineDto, ChecklistDto, DealDto, ListDto, LossReasonDto, MoveDto, PipelineDto, ReopenDto, ReorderStagesDto, StageDto, TagDto, UpdateDealDto } from './dto/pipeline.dto';

const userSelect = { id: true, name: true, email: true, role: true, organizationId: true } satisfies Prisma.UserSelect;
const dealInclude = { lead: { select: { id: true, name: true, phone: true, email: true } }, pipeline: true, stage: true, owner: { select: userSelect }, lossReason: true, tags: { include: { tag: true } }, activities: true, _count: { select: { events: true, movements: true, assignments: true } } } satisfies Prisma.DealInclude;

type UserRef = AuthenticatedUserRef;

@Injectable()
export class PipelineService {
  constructor(private readonly prisma: PrismaService, private readonly access: AccessContextService) {}

  private scope(ctx: AccessContext, requested?: string) { if (!ctx.global) return ctx.organizationId!; if (!requested) throw new BadRequestException('Organização é obrigatória'); return requested; }
  private whereScope(ctx: AccessContext, requested?: string) { return ctx.global && requested ? { organizationId: requested } : ctx.global ? {} : { organizationId: ctx.organizationId! }; }
  private slug(v: string) { return v.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
  private money(v?: number | null) { if (v === undefined) return undefined; if (v === null) return null; if (v < 0) throw new BadRequestException('Valor não pode ser negativo'); return new Prisma.Decimal(v); }
  private prob(v?: number | null) { if (v === undefined) return undefined; if (v === null) return null; if (v < 0 || v > 100) throw new BadRequestException('Probabilidade deve estar entre 0 e 100'); return v; }
  private async org(id: string) { const o = await this.prisma.organization.findFirst({ where: { id, active: true, deletedAt: null } }); if (!o) throw new NotFoundException('Organização ativa não encontrada'); }
  private async userInOrg(id: string | null | undefined, orgId: string) { if (!id) return; const u = await this.prisma.user.findFirst({ where: { id, active: true, deletedAt: null }, select: { organizationId: true, role: true } }); if (!u) throw new NotFoundException('Usuário ativo não encontrado'); if (u.organizationId && u.organizationId !== orgId) throw new BadRequestException('Usuário deve pertencer à mesma organização'); }
  private async leadInOrg(id: string, orgId: string) { const lead = await this.prisma.lead.findFirst({ where: { id, organizationId: orgId, deletedAt: null } }); if (!lead) throw new NotFoundException('Lead não encontrado na organização'); return lead; }
  private async pipeInOrg(id: string, orgId: string) { const p = await this.prisma.pipeline.findFirst({ where: { id, organizationId: orgId, archivedAt: null } }); if (!p) throw new NotFoundException('Pipeline não encontrado'); return p; }
  private async stageInPipe(id: string, pipeId: string, orgId: string, active = false) { const s = await this.prisma.pipelineStage.findFirst({ where: { id, pipelineId: pipeId, organizationId: orgId, archivedAt: null, ...(active ? { isActive: true } : {}) } }); if (!s) throw new NotFoundException('Stage não encontrada no pipeline'); return s; }
  private async audit(tx: Prisma.TransactionClient, orgId: string, module: string, entityType: string, entityId: string, action: string, actor?: string, before?: unknown, after?: unknown) { await tx.auditLog.create({ data: { organizationId: orgId, module, entityType, entityId, action, actorUserId: actor, before: before as Prisma.InputJsonValue, after: after as Prisma.InputJsonValue } }); }
  private async event(tx: Prisma.TransactionClient, orgId: string, dealId: string | null, eventType: string, actor: string | undefined, payload: object) { await tx.dealEvent.create({ data: { organizationId: orgId, dealId, eventType, actorUserId: actor, payload: payload as Prisma.InputJsonObject } }); }

  async listPipelines(q: ListDto, user: UserRef) { const ctx = await this.access.resolve(user); return this.prisma.pipeline.findMany({ where: { archivedAt: null, ...this.whereScope(ctx, q.organizationId) }, include: { stages: { where: { archivedAt: null }, orderBy: { position: 'asc' } } }, orderBy: [{ isDefault: 'desc' }, { createdAt: 'asc' }] }); }
  async createPipeline(d: PipelineDto, user: UserRef) { const ctx = await this.access.resolve(user); const orgId = this.scope(ctx, d.organizationId); await this.org(orgId); return this.prisma.$transaction(async tx => { if (d.isDefault) await tx.pipeline.updateMany({ where: { organizationId: orgId, isDefault: true }, data: { isDefault: false } }); const p = await tx.pipeline.create({ data: { organizationId: orgId, name: d.name.trim(), description: d.description, isDefault: !!d.isDefault, isActive: d.isActive ?? true, currency: d.currency ?? 'BRL' } }); await this.audit(tx, orgId, 'pipeline', 'Pipeline', p.id, 'pipeline.created', user.id, null, p); return p; }); }
  async updatePipeline(id: string, d: Partial<PipelineDto>, user: UserRef) { const ctx = await this.access.resolve(user); const cur = await this.prisma.pipeline.findFirst({ where: { id, archivedAt: null, ...this.whereScope(ctx, d.organizationId) } }); if (!cur) throw new NotFoundException('Pipeline não encontrado'); return this.prisma.$transaction(async tx => { if (d.isDefault) await tx.pipeline.updateMany({ where: { organizationId: cur.organizationId, isDefault: true, id: { not: id } }, data: { isDefault: false } }); const p = await tx.pipeline.update({ where: { id }, data: { name: d.name?.trim(), description: d.description, isDefault: d.isDefault, isActive: d.isActive, currency: d.currency } }); await this.audit(tx, cur.organizationId, 'pipeline', 'Pipeline', id, 'pipeline.updated', user.id, cur, p); return p; }); }
  async archivePipeline(id: string, user: UserRef) { const cur = await this.getPipeline(id, user); await this.prisma.$transaction(async tx => { const updated = await tx.pipeline.update({ where: { id }, data: { archivedAt: new Date(), isActive: false } }); await this.audit(tx, cur.organizationId, 'pipeline', 'Pipeline', id, 'pipeline.archived', user.id, cur, updated); }); return { success: true, id: cur.id }; }
  async getPipeline(id: string, user: UserRef) { const ctx = await this.access.resolve(user); const p = await this.prisma.pipeline.findFirst({ where: { id, archivedAt: null, ...this.whereScope(ctx) }, include: { stages: { where: { archivedAt: null }, orderBy: { position: 'asc' }, include: { checklists: { where: { archivedAt: null }, orderBy: { position: 'asc' } } } } } }); if (!p) throw new NotFoundException('Pipeline não encontrado'); return p; }

  async createStage(pid: string, d: StageDto, user: UserRef) { const p = await this.getPipeline(pid, user); this.prob(d.probability); return this.prisma.$transaction(async tx => { if (d.isInitial) await tx.pipelineStage.updateMany({ where: { pipelineId: pid, organizationId: p.organizationId, isInitial: true, isActive: true }, data: { isInitial: false } }); const s = await tx.pipelineStage.create({ data: { organizationId: p.organizationId, pipelineId: pid, name: d.name.trim(), description: d.description, position: d.position ?? 1000, probability: d.probability ?? 0, slaHours: d.slaHours, isInitial: !!d.isInitial, isActive: d.isActive ?? true, color: d.color } }); await this.audit(tx, p.organizationId, 'pipeline', 'PipelineStage', s.id, 'stage.created', user.id, null, s); return s; }); }
  async updateStage(id: string, d: StageDto, user: UserRef) { const ctx = await this.access.resolve(user); const cur = await this.prisma.pipelineStage.findFirst({ where: { id, archivedAt: null, ...this.whereScope(ctx) } }); if (!cur) throw new NotFoundException('Stage não encontrada'); this.prob(d.probability); return this.prisma.$transaction(async tx => { if (d.isInitial) await tx.pipelineStage.updateMany({ where: { pipelineId: cur.pipelineId, organizationId: cur.organizationId, isInitial: true, isActive: true, id: { not: id } }, data: { isInitial: false } }); const s = await tx.pipelineStage.update({ where: { id }, data: { name: d.name?.trim(), description: d.description, position: d.position, probability: d.probability, slaHours: d.slaHours, isInitial: d.isInitial, isActive: d.isActive, color: d.color } }); await this.audit(tx, cur.organizationId, 'pipeline', 'PipelineStage', id, 'stage.updated', user.id, cur, s); return s; }); }
  async reorderStages(pid: string, d: ReorderStagesDto, user: UserRef) { const p = await this.getPipeline(pid, user); return this.prisma.$transaction(async tx => { if (d.stages.filter(s => s.isInitial).length > 1) throw new BadRequestException('Apenas uma stage inicial é permitida'); for (const item of d.stages) await tx.pipelineStage.update({ where: { id: item.id }, data: { position: item.position, ...(item.isInitial !== undefined ? { isInitial: item.isInitial } : {}) } }); await this.audit(tx, p.organizationId, 'pipeline', 'Pipeline', pid, 'stage.reordered', user.id, null, d); return { success: true }; }); }
  async archiveStage(id: string, user: UserRef) { const ctx = await this.access.resolve(user); const cur = await this.prisma.pipelineStage.findFirst({ where: { id, archivedAt: null, ...this.whereScope(ctx) } }); if (!cur) throw new NotFoundException('Stage não encontrada'); await this.prisma.$transaction(async tx => { const updated = await tx.pipelineStage.update({ where: { id }, data: { archivedAt: new Date(), isActive: false } }); await this.audit(tx, cur.organizationId, 'pipeline', 'PipelineStage', id, 'stage.archived', user.id, cur, updated); }); return { success: true, id }; }

  async createChecklist(stageId: string, d: ChecklistDto, user: UserRef) { const ctx = await this.access.resolve(user); const s = await this.prisma.pipelineStage.findFirst({ where: { id: stageId, archivedAt: null, ...this.whereScope(ctx) } }); if (!s) throw new NotFoundException('Stage não encontrada'); return this.prisma.$transaction(async tx => { const created = await tx.stageChecklist.create({ data: { organizationId: s.organizationId, stageId, title: d.title.trim(), description: d.description, type: d.type ?? 'CUSTOM', isRequired: d.isRequired ?? true, position: d.position ?? 0, isActive: d.isActive ?? true, metadata: d.metadata as Prisma.InputJsonObject } }); await this.audit(tx, s.organizationId, 'pipeline', 'StageChecklist', created.id, 'stage_checklist.created', user.id, null, created); return created; }); }
  async updateChecklist(id: string, d: Partial<ChecklistDto>, user: UserRef) { const ctx = await this.access.resolve(user); const c = await this.prisma.stageChecklist.findFirst({ where: { id, archivedAt: null, ...this.whereScope(ctx) } }); if (!c) throw new NotFoundException('Checklist não encontrado'); return this.prisma.$transaction(async tx => { const updated = await tx.stageChecklist.update({ where: { id }, data: { title: d.title?.trim(), description: d.description, type: d.type, isRequired: d.isRequired, position: d.position, isActive: d.isActive, metadata: d.metadata as Prisma.InputJsonObject } }); await this.audit(tx, c.organizationId, 'pipeline', 'StageChecklist', id, 'stage_checklist.updated', user.id, c, updated); return updated; }); }
  async archiveChecklist(id: string, user: UserRef) { const ctx = await this.access.resolve(user); const cur = await this.prisma.stageChecklist.findFirst({ where: { id, archivedAt: null, ...this.whereScope(ctx) } }); if (!cur) throw new NotFoundException('Checklist não encontrado'); await this.prisma.$transaction(async tx => { const updated = await tx.stageChecklist.update({ where: { id }, data: { archivedAt: new Date(), isActive: false } }); await this.audit(tx, cur.organizationId, 'pipeline', 'StageChecklist', id, 'stage_checklist.archived', user.id, cur, updated); }); return { success: true }; }

  async listLossReasons(q: ListDto, user: UserRef) { const ctx = await this.access.resolve(user); return this.prisma.pipelineLossReason.findMany({ where: { archivedAt: null, ...this.whereScope(ctx, q.organizationId), ...(q.pipelineId ? { OR: [{ pipelineId: q.pipelineId }, { pipelineId: null }] } : {}) }, orderBy: { position: 'asc' } }); }
  async createLossReason(d: LossReasonDto, user: UserRef) { const ctx = await this.access.resolve(user); const orgId = this.scope(ctx, d.organizationId); await this.org(orgId); if (d.pipelineId) await this.pipeInOrg(d.pipelineId, orgId); return this.prisma.pipelineLossReason.create({ data: { organizationId: orgId, pipelineId: d.pipelineId, name: d.name.trim(), description: d.description, isActive: d.isActive ?? true, position: d.position ?? 0 } }); }
  async updateLossReason(id: string, d: Partial<LossReasonDto>, user: UserRef) { const ctx = await this.access.resolve(user); const cur = await this.prisma.pipelineLossReason.findFirst({ where: { id, archivedAt: null, ...this.whereScope(ctx) } }); if (!cur) throw new NotFoundException('Motivo não encontrado'); return this.prisma.pipelineLossReason.update({ where: { id }, data: { name: d.name?.trim(), description: d.description, isActive: d.isActive, position: d.position } }); }
  async archiveLossReason(id: string, user: UserRef) { await this.updateLossReason(id, { isActive: false }, user); await this.prisma.pipelineLossReason.update({ where: { id }, data: { archivedAt: new Date() } }); return { success: true }; }

  async listTags(q: ListDto, user: UserRef) { const ctx = await this.access.resolve(user); return this.prisma.tag.findMany({ where: { archivedAt: null, ...this.whereScope(ctx, q.organizationId) }, orderBy: { name: 'asc' } }); }
  async createTag(d: TagDto, user: UserRef) { const ctx = await this.access.resolve(user); const orgId = this.scope(ctx, d.organizationId); return this.prisma.tag.create({ data: { organizationId: orgId, name: d.name.trim(), slug: this.slug(d.name), color: d.color, description: d.description, isActive: d.isActive ?? true } }); }
  async updateTag(id: string, d: Partial<TagDto>, user: UserRef) { const ctx = await this.access.resolve(user); const cur = await this.prisma.tag.findFirst({ where: { id, archivedAt: null, ...this.whereScope(ctx) } }); if (!cur) throw new NotFoundException('Tag não encontrada'); return this.prisma.tag.update({ where: { id }, data: { name: d.name?.trim(), slug: d.name ? this.slug(d.name) : undefined, color: d.color, description: d.description, isActive: d.isActive } }); }
  async archiveTag(id: string, user: UserRef) { await this.updateTag(id, { isActive: false }, user); await this.prisma.tag.update({ where: { id }, data: { archivedAt: new Date() } }); return { success: true }; }

  async createDeal(d: DealDto, user: UserRef) { const ctx = await this.access.resolve(user); const orgId = this.scope(ctx, d.organizationId); await this.leadInOrg(d.leadId, orgId); await this.pipeInOrg(d.pipelineId, orgId); await this.stageInPipe(d.stageId, d.pipelineId, orgId, true); await this.userInOrg(d.ownerId, orgId); return this.prisma.$transaction(async tx => { const deal = await tx.deal.create({ data: { organizationId: orgId, leadId: d.leadId, pipelineId: d.pipelineId, stageId: d.stageId, ownerId: d.ownerId || null, title: d.title.trim(), description: d.description, estimatedValue: this.money(d.estimatedValue) ?? new Prisma.Decimal(0), currency: d.currency ?? 'BRL', expectedCloseDate: d.expectedCloseDate ? new Date(d.expectedCloseDate) : undefined, probabilityOverride: this.prob(d.probabilityOverride), source: d.source, metadata: d.metadata as Prisma.InputJsonObject } }); await tx.dealStageMovement.create({ data: { organizationId: orgId, dealId: deal.id, pipelineId: d.pipelineId, fromStageId: null, toStageId: d.stageId, movedByUserId: user.id, movementType: 'CREATED' } }); if (deal.ownerId) await tx.dealAssignment.create({ data: { organizationId: orgId, dealId: deal.id, fromUserId: null, toUserId: deal.ownerId, assignedByUserId: user.id } }); await this.event(tx, orgId, deal.id, 'DEAL_CREATED', user.id, { dealId: deal.id }); await this.audit(tx, orgId, 'pipeline', 'Deal', deal.id, 'deal.created', user.id, null, deal); return deal; }); }
  async listDeals(q: ListDto, user: UserRef) { const ctx = await this.access.resolve(user); const page = q.page ?? 1, limit = q.limit ?? 20; const where: Prisma.DealWhereInput = { archivedAt: null, ...this.whereScope(ctx, q.organizationId), ...(q.pipelineId ? { pipelineId: q.pipelineId } : {}), ...(q.stageId ? { stageId: q.stageId } : {}), ...(q.status ? { status: q.status } : {}), ...(q.ownerId ? { ownerId: q.ownerId } : {}), ...(q.tagId ? { tags: { some: { tagId: q.tagId } } } : {}), ...(q.search ? { OR: [{ title: { contains: q.search, mode: 'insensitive' } }, { lead: { name: { contains: q.search, mode: 'insensitive' } } }] } : {}) }; const [items, total] = await this.prisma.$transaction([this.prisma.deal.findMany({ where, include: dealInclude, orderBy: { updatedAt: 'desc' }, skip: (page - 1) * limit, take: limit }), this.prisma.deal.count({ where })]); return { items, meta: { total, page, limit, totalPages: Math.max(1, Math.ceil(total / limit)) } }; }
  async getDeal(id: string, user: UserRef) { const ctx = await this.access.resolve(user); const d = await this.prisma.deal.findFirst({ where: { id, ...this.whereScope(ctx) }, include: { ...dealInclude, movements: { orderBy: { occurredAt: 'desc' }, include: { fromStage: true, toStage: true, movedByUser: { select: userSelect } } }, assignments: { orderBy: { occurredAt: 'desc' }, include: { fromUser: { select: userSelect }, toUser: { select: userSelect }, assignedByUser: { select: userSelect } } } } }); if (!d) throw new NotFoundException('Deal não encontrado'); return d; }
  async updateDeal(id: string, d: UpdateDealDto, user: UserRef) { const cur = await this.getDeal(id, user); const updated = await this.prisma.$transaction(async tx => { const up = await tx.deal.update({ where: { id }, data: { title: d.title?.trim(), description: d.description, estimatedValue: this.money(d.estimatedValue) ?? undefined, expectedCloseDate: d.expectedCloseDate === null ? null : d.expectedCloseDate ? new Date(d.expectedCloseDate) : undefined, probabilityOverride: this.prob(d.probabilityOverride), metadata: d.metadata as Prisma.InputJsonObject } }); await this.event(tx, cur.organizationId, id, 'DEAL_UPDATED', user.id, d); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.updated', user.id, cur, up); return up; }); return updated; }
  private assertOpen(deal: { status: DealStatus }) { if (deal.status !== DealStatus.OPEN && deal.status !== DealStatus.REOPENED) throw new BadRequestException('Deals WON ou LOST precisam ser reabertos antes de voltar ao fluxo'); }
  async moveDeal(id: string, d: MoveDto, user: UserRef) { const cur = await this.getDeal(id, user); this.assertOpen(cur); await this.stageInPipe(d.toStageId, cur.pipelineId, cur.organizationId, true); return this.prisma.$transaction(async tx => { const now = new Date(); await tx.dealStageMovement.create({ data: { organizationId: cur.organizationId, dealId: id, pipelineId: cur.pipelineId, fromStageId: cur.stageId, toStageId: d.toStageId, movedByUserId: user.id, movementType: 'STAGE_CHANGED', reason: d.reason } }); const up = await tx.deal.update({ where: { id }, data: { stageId: d.toStageId, currentStageEnteredAt: now, lastMovementAt: now } }); await this.event(tx, cur.organizationId, id, 'DEAL_STAGE_CHANGED', user.id, { fromStageId: cur.stageId, toStageId: d.toStageId, reason: d.reason }); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.stage_changed', user.id, cur, up); return up; }); }
  async changePipeline(id: string, d: ChangePipelineDto, user: UserRef) { const cur = await this.getDeal(id, user); this.assertOpen(cur); await this.pipeInOrg(d.pipelineId, cur.organizationId); await this.stageInPipe(d.stageId, d.pipelineId, cur.organizationId, true); return this.prisma.$transaction(async tx => { const now = new Date(); await tx.dealStageMovement.create({ data: { organizationId: cur.organizationId, dealId: id, pipelineId: d.pipelineId, fromStageId: cur.stageId, toStageId: d.stageId, movedByUserId: user.id, movementType: 'PIPELINE_CHANGED', reason: d.reason } }); const up = await tx.deal.update({ where: { id }, data: { pipelineId: d.pipelineId, stageId: d.stageId, currentStageEnteredAt: now, lastMovementAt: now } }); await this.event(tx, cur.organizationId, id, 'DEAL_PIPELINE_CHANGED', user.id, d); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.pipeline_changed', user.id, cur, up); return up; }); }
  async assignDeal(id: string, d: AssignDto, user: UserRef) { const cur = await this.getDeal(id, user); await this.userInOrg(d.ownerId, cur.organizationId); return this.prisma.$transaction(async tx => { const up = await tx.deal.update({ where: { id }, data: { ownerId: d.ownerId || null } }); await tx.dealAssignment.create({ data: { organizationId: cur.organizationId, dealId: id, fromUserId: cur.ownerId, toUserId: d.ownerId || null, assignedByUserId: user.id, reason: d.reason } }); await this.event(tx, cur.organizationId, id, 'DEAL_OWNER_CHANGED', user.id, { fromUserId: cur.ownerId, toUserId: d.ownerId }); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.owner_changed', user.id, cur, up); return up; }); }
  async addTag(id: string, tagId: string, user: UserRef) { const cur = await this.getDeal(id, user); const tag = await this.prisma.tag.findFirst({ where: { id: tagId, organizationId: cur.organizationId, isActive: true, archivedAt: null } }); if (!tag) throw new NotFoundException('Tag não encontrada'); return this.prisma.$transaction(async tx => { const r = await tx.dealTag.upsert({ where: { dealId_tagId: { dealId: id, tagId } }, update: {}, create: { organizationId: cur.organizationId, dealId: id, tagId, createdByUserId: user.id } }); await this.event(tx, cur.organizationId, id, 'DEAL_TAG_ADDED', user.id, { tagId }); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.tag_added', user.id, null, r); return r; }); }
  async removeTag(id: string, tagId: string, user: UserRef) { const cur = await this.getDeal(id, user); await this.prisma.$transaction(async tx => { await tx.dealTag.deleteMany({ where: { dealId: id, tagId, organizationId: cur.organizationId } }); await this.event(tx, cur.organizationId, id, 'DEAL_TAG_REMOVED', user.id, { tagId }); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.tag_removed', user.id); }); return { success: true }; }
  async won(id: string, amount: number, wonAt: string | undefined, notes: string | undefined, user: UserRef) { const cur = await this.getDeal(id, user); this.assertOpen(cur); const at = wonAt ? new Date(wonAt) : new Date(); return this.prisma.$transaction(async tx => { const up = await tx.deal.update({ where: { id }, data: { status: 'WON', closedAt: at, wonAt: at, lostAt: null, lossReasonId: null, closedValue: this.money(amount) } }); await this.event(tx, cur.organizationId, id, 'DEAL_WON', user.id, { previousStatus: cur.status, newStatus: 'WON', amount, currency: cur.currency, wonAt: at, notes }); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.won', user.id, cur, up); return up; }); }
  async lost(id: string, lossReasonId: string, lostAt: string | undefined, notes: string | undefined, user: UserRef) { const cur = await this.getDeal(id, user); this.assertOpen(cur); const reason = await this.prisma.pipelineLossReason.findFirst({ where: { id: lossReasonId, organizationId: cur.organizationId, isActive: true, archivedAt: null, OR: [{ pipelineId: null }, { pipelineId: cur.pipelineId }] } }); if (!reason) throw new NotFoundException('Motivo de perda obrigatório e válido não encontrado'); const at = lostAt ? new Date(lostAt) : new Date(); return this.prisma.$transaction(async tx => { const up = await tx.deal.update({ where: { id }, data: { status: 'LOST', closedAt: at, lostAt: at, wonAt: null, lossReasonId } }); await this.event(tx, cur.organizationId, id, 'DEAL_LOST', user.id, { previousStatus: cur.status, newStatus: 'LOST', lossReasonId, lostAt: at, notes }); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.lost', user.id, cur, up); return up; }); }
  async reopen(id: string, d: ReopenDto, user: UserRef) { const cur = await this.getDeal(id, user); if (cur.status !== DealStatus.WON && cur.status !== DealStatus.LOST) throw new BadRequestException('Apenas Deals ganhos ou perdidos podem ser reabertos'); await this.stageInPipe(d.toStageId, cur.pipelineId, cur.organizationId, true); return this.prisma.$transaction(async tx => { const now = new Date(); await tx.dealStageMovement.create({ data: { organizationId: cur.organizationId, dealId: id, pipelineId: cur.pipelineId, fromStageId: cur.stageId, toStageId: d.toStageId, movedByUserId: user.id, movementType: 'REOPENED', reason: d.reason } }); const up = await tx.deal.update({ where: { id }, data: { status: 'REOPENED', closedAt: null, wonAt: null, lostAt: null, lossReasonId: null, closedValue: null, stageId: d.toStageId, currentStageEnteredAt: now, lastMovementAt: now } }); await this.event(tx, cur.organizationId, id, 'DEAL_REOPENED', user.id, { previousStatus: cur.status, newStatus: 'REOPENED', toStageId: d.toStageId, reason: d.reason, reopenedAt: now }); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.reopened', user.id, cur, up); return up; }); }
  async archiveDeal(id: string, user: UserRef) { const cur = await this.getDeal(id, user); await this.prisma.$transaction(async tx => { const up = await tx.deal.update({ where: { id }, data: { status: 'ARCHIVED', archivedAt: new Date() } }); await this.event(tx, cur.organizationId, id, 'DEAL_ARCHIVED', user.id, { }); await this.audit(tx, cur.organizationId, 'pipeline', 'Deal', id, 'deal.archived', user.id, cur, up); }); return { success: true }; }
  async createActivity(id: string, d: ActivityDto, user: UserRef) { const cur = await this.getDeal(id, user); await this.userInOrg(d.assignedToUserId, cur.organizationId); return this.prisma.$transaction(async tx => { const a = await tx.dealActivity.create({ data: { organizationId: cur.organizationId, dealId: id, leadId: cur.leadId, title: d.title.trim(), type: d.type, status: d.status ?? 'OPEN', description: d.description, dueAt: d.dueAt ? new Date(d.dueAt) : undefined, assignedToUserId: d.assignedToUserId, createdByUserId: user.id, metadata: d.metadata as Prisma.InputJsonObject } }); await this.event(tx, cur.organizationId, id, 'DEAL_ACTIVITY_CREATED', user.id, { activityId: a.id }); return a; }); }
  async updateActivity(id: string, activityId: string, d: Partial<ActivityDto>, user: UserRef) { const cur = await this.getDeal(id, user); const a = await this.prisma.dealActivity.findFirst({ where: { id: activityId, dealId: id, organizationId: cur.organizationId } }); if (!a) throw new NotFoundException('Atividade não encontrada'); return this.prisma.$transaction(async tx => { const up = await tx.dealActivity.update({ where: { id: activityId }, data: { title: d.title?.trim(), type: d.type, status: d.status, description: d.description, dueAt: d.dueAt ? new Date(d.dueAt) : undefined, assignedToUserId: d.assignedToUserId, completedAt: d.status === DealActivityStatus.DONE ? new Date() : undefined, metadata: d.metadata as Prisma.InputJsonObject } }); await this.event(tx, cur.organizationId, id, up.status === DealActivityStatus.DONE ? 'DEAL_ACTIVITY_COMPLETED' : 'DEAL_ACTIVITY_UPDATED', user.id, { activityId }); return up; }); }
  async cancelActivity(id: string, activityId: string, user: UserRef) { return this.updateActivity(id, activityId, { status: DealActivityStatus.CANCELED }, user); }
  async movements(id: string, user: UserRef) { const d = await this.getDeal(id, user); return this.prisma.dealStageMovement.findMany({ where: { dealId: id, organizationId: d.organizationId }, orderBy: { occurredAt: 'desc' }, include: { fromStage: true, toStage: true, movedByUser: { select: userSelect } } }); }
  async timeline(id: string, user: UserRef) { const d = await this.getDeal(id, user); return this.prisma.dealEvent.findMany({ where: { dealId: id, organizationId: d.organizationId }, orderBy: { occurredAt: 'desc' }, include: { actorUser: { select: userSelect } } }); }
  async kanban(pipelineId: string, q: ListDto, user: UserRef) { const p = await this.getPipeline(pipelineId, user); const take = q.limit ?? 20; const stages = await this.prisma.pipelineStage.findMany({ where: { pipelineId, organizationId: p.organizationId, isActive: true, archivedAt: null }, orderBy: { position: 'asc' } }); return { pipeline: p, stages: await Promise.all(stages.map(async stage => { const where = { organizationId: p.organizationId, pipelineId, stageId: stage.id, status: { in: [DealStatus.OPEN, DealStatus.REOPENED] }, archivedAt: null } satisfies Prisma.DealWhereInput; const [deals, total] = await this.prisma.$transaction([this.prisma.deal.findMany({ where, include: dealInclude, take, orderBy: { updatedAt: 'desc' } }), this.prisma.deal.count({ where })]); return { ...stage, deals, meta: { total, limit: take } }; })) }; }
}
