"use client";

import { useMemo, useReducer } from "react";
import { CheckCheck, Copy, FileText, Image as ImageIcon, Maximize2, Minus, Monitor, Phone, RotateCcw, Smartphone, Video } from "lucide-react";
import Button from "@/components/ui/Button";
import Modal from "@/components/ui/Modal";
import CampaignSurface from "@/components/ui/crm/CampaignSurface";
import SmartphoneMockup from "@/components/ui/crm/SmartphoneMockup";
import { VariableMapping } from "@/services/campaigns.service";
import { WhatsappTemplate } from "@/types/templates";
import { initialPreviewState, previewReducer } from "./campaign-preview-state";

export type PreviewRecipient={phone:string;name:string;row:Record<string,unknown>};
function valueFor(mapping:VariableMapping|undefined,row:Record<string,unknown>,phone:string,name:string,position:number){if(!mapping)return`{{${position}}}`;if(mapping.sourceType==="FIXED")return mapping.fixedValue?.trim()||`{{${position}}}`;if(mapping.sourceType==="COLUMN")return String(row[mapping.sourceColumn||""]||`{{${position}}}`);if(mapping.sourceType==="LEAD_NAME")return name||`{{${position}}}`;if(mapping.sourceType==="LEAD_PHONE")return phone||`{{${position}}}`;return`{{${position}}}`}
export function renderTemplateText(text:string|undefined,component:string,mappings:VariableMapping[],recipient:PreviewRecipient){return(text||"").replace(/{{\s*(\d+)\s*}}/g,(_,position)=>valueFor(mappings.find(item=>item.component===component&&item.position===Number(position)),recipient.row,recipient.phone,recipient.name,Number(position)))}

function MediaHeader({type,name}:{type:string;name:string}){const cls="mb-3 grid min-h-32 place-items-center rounded-xl border border-black/5 bg-slate-200/80 text-slate-600";if(type==="IMAGE")return <div className={cls}><ImageIcon/><span className="text-xs">{name||"Imagem indisponível"}</span></div>;if(type==="VIDEO")return <div className={cls}><Video/><span className="text-xs">{name||"Vídeo indisponível"}</span></div>;if(type==="DOCUMENT")return <div className={cls}><FileText/><span className="text-xs">{name||"Documento indisponível"}</span></div>;return null}

export default function CampaignMessagePreview({template,mappings,row,phone,name,mediaName,accountName="Conta oficial",large=false,onSendTest}:{template?:WhatsappTemplate;mappings:VariableMapping[];row:Record<string,unknown>;phone:string;name:string;mediaName:string;accountName?:string;large?:boolean;onSendTest?:()=>void}){
 const[{device,theme,zoom,fullscreen},dispatch]=useReducer(previewReducer,initialPreviewState);const recipient=useMemo(()=>({phone,name,row}),[phone,name,row]);
 const summary=template?`${template.displayName} (${template.language}) — ${renderTemplateText(template.body,"BODY",mappings,recipient)}`:"Nenhum template selecionado";
 const controls=<div className="flex flex-wrap gap-1" aria-label="Controles da prévia"><Button size="sm" variant={device==="mobile"?"secondary":"ghost"} aria-pressed={device==="mobile"} onClick={()=>dispatch({type:"device",value:"mobile"})}><Smartphone size={15}/>Mobile</Button><Button size="sm" variant={device==="desktop"?"secondary":"ghost"} aria-pressed={device==="desktop"} onClick={()=>dispatch({type:"device",value:"desktop"})}><Monitor size={15}/>Desktop</Button><Button size="sm" variant={theme==="light"?"secondary":"ghost"} aria-pressed={theme==="light"} onClick={()=>dispatch({type:"theme",value:"light"})}>Claro</Button><Button size="sm" variant={theme==="dark"?"secondary":"ghost"} aria-pressed={theme==="dark"} onClick={()=>dispatch({type:"theme",value:"dark"})}>Escuro</Button><Button size="sm" variant="ghost" aria-label="Diminuir zoom" onClick={()=>dispatch({type:"zoom",value:-10})}><Minus size={15}/></Button><Button size="sm" variant="ghost" aria-label="Restaurar zoom" onClick={()=>dispatch({type:"resetZoom"})}><RotateCcw size={15}/>{zoom}%</Button><Button size="sm" variant="ghost" aria-label="Aumentar zoom" onClick={()=>dispatch({type:"zoom",value:10})}>＋</Button><Button size="sm" variant="ghost" onClick={()=>dispatch({type:"fullscreen",value:true})}><Maximize2 size={15}/>Abrir visualização</Button></div>;
 const preview=<div className="mx-auto origin-top transition-transform duration-200 motion-reduce:transition-none" style={{transform:`scale(${zoom/100})`}}><SmartphoneMockup compact={device==="mobile"}><div className={`h-full transition-colors duration-200 ${theme==="dark"?"bg-[#0b141a]":"bg-[#efeae2]"}`}><div className={`flex h-8 items-center justify-between px-6 pt-1 text-[10px] font-semibold ${theme==="dark"?"text-white":"text-slate-800"}`}><span>10:30</span><span aria-hidden="true">●●●</span></div><header className={`flex items-center gap-3 px-4 py-3 transition-colors duration-200 ${theme==="dark"?"bg-[#202c33] text-white":"bg-white text-slate-900"}`}><div className="grid h-10 w-10 place-items-center rounded-full bg-blue-100 font-bold text-blue-700">{accountName.slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><strong className="block truncate">{accountName}</strong><span className="block truncate text-xs opacity-70">{name||phone||"Destinatário de exemplo"}</span></div></header><div className="min-h-[500px] p-5"><div className={`ml-auto max-w-[92%] rounded-xl p-3 text-sm shadow transition-colors duration-200 ${theme==="dark"?"bg-[#005c4b] text-white":"bg-[#d9fdd3] text-slate-900"}`}>{!template?<div className="py-12 text-center opacity-70">Selecione um template para visualizar a mensagem.</div>:<><MediaHeader type={template.headerType} name={mediaName}/>{template.headerText&&<strong className="mb-1 block">{renderTemplateText(template.headerText,"HEADER",mappings,recipient)}</strong>}<p className="whitespace-pre-wrap break-words">{renderTemplateText(template.body,"BODY",mappings,recipient)}</p>{template.footer&&<small className="mt-2 block opacity-60">{template.footer}</small>}{template.buttons?.map((button,index)=><div className="mt-2 border-t border-current/10 pt-2 text-center font-medium text-blue-600" key={`${button.type}-${index}`}>{button.type==="PHONE_NUMBER"&&<Phone className="mr-1 inline" size={14}/>} {renderTemplateText(button.text||button.url||button.phoneNumber||button.type,"BUTTON",mappings.filter(m=>m.buttonIndex===index),recipient)}</div>)}<span className="mt-1 flex justify-end gap-1 text-[10px] opacity-60">10:30 <CheckCheck size={13}/></span></>}</div></div></div></SmartphoneMockup></div>;
 return <CampaignSurface aria-label="Pré-visualização completa do WhatsApp" className={large?"lg:p-6":""}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold text-slate-900">Prévia da mensagem</h3><p className="text-xs text-slate-500">Atualizada em tempo real com os dados do rascunho.</p></div>{controls}</div><div className="overflow-auto py-3">{preview}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-2"><p className="max-w-xl text-xs text-slate-500">Prévia aproximada. A aparência final pode variar conforme o aparelho e a versão do WhatsApp.</p><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={()=>void navigator.clipboard?.writeText(summary)}><Copy size={14}/>Copiar resumo</Button>{onSendTest&&<Button size="sm" variant="secondary" onClick={onSendTest}>Enviar mensagem de teste</Button>}</div></div><Modal isOpen={fullscreen} onClose={()=>dispatch({type:"fullscreen",value:false})} title="Visualização ampliada da mensagem" width="xl"><div className="mb-4 flex flex-wrap justify-between gap-3">{controls}<Button variant="ghost" onClick={()=>dispatch({type:"fullscreen",value:false})}>Voltar à edição</Button></div><div className="min-h-[60vh] overflow-auto py-4">{preview}</div><p className="mt-4 text-xs text-slate-500">Prévia aproximada. A aparência final pode variar conforme o aparelho e a versão do WhatsApp.</p></Modal></CampaignSurface>
}
