'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Bell, Building2, Check, ChevronRight, CircleUserRound, Fingerprint, Gauge, Cable, LoaderCircle, LockKeyhole, Palette, Save, ScrollText, Settings2, ShieldCheck, Users } from 'lucide-react';
import Badge from '@/components/ui/Badge'; import Button from '@/components/ui/Button'; import Card from '@/components/ui/Card'; import EmptyState from '@/components/ui/EmptyState'; import Input from '@/components/ui/Input'; import PageHeader from '@/components/ui/PageHeader'; import Select from '@/components/ui/Select';
import { Table,TableBody,TableCell,TableContainer,TableHead,TableHeader,TableRow } from '@/components/ui/Table';
import { settingsService } from '@/services/settings.service'; import type { AuditEntry,IntegrationStatus,OrganizationSettings,PermissionMatrix,SettingsMe,SettingsSection } from '@/types/settings';
const NAV:{id:SettingsSection;label:string;icon:typeof Settings2}[]=[['account','Minha conta',CircleUserRound],['organization','Organização',Building2],['users','Usuários e equipes',Users],['roles','Funções e permissões',ShieldCheck],['security','Segurança',LockKeyhole],['notifications','Notificações',Bell],['branding','Identidade visual',Palette],['operations','Preferências operacionais',Gauge],['integrations','Integrações',Cable],['audit','Auditoria',ScrollText],['system','Sistema global',Settings2]].map(([id,label,icon])=>({id:id as SettingsSection,label:label as string,icon:icon as typeof Settings2}));
const ROLE_LABEL:Record<string,string>={GLOBAL_ADMIN:'Administrador global',ORG_ADMIN:'Superintendente',MANAGER:'Gerente',BROKER:'Corretor'};
function Field({label,value,onChange,type='text'}:{label:string;value:string|number;onChange:(v:string)=>void;type?:string}){return <Input label={label} type={type} value={value} onChange={e=>onChange(e.target.value)}/>}
export default function SettingsCenter(){const[me,setMe]=useState<SettingsMe|null>(null),[active,setActive]=useState<SettingsSection>('account'),[data,setData]=useState<unknown>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{settingsService.me().then(setMe).catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar')).finally(()=>setLoading(false))},[]);
 const allowed=useMemo(()=>NAV.filter(n=>me?.capabilities.sections.includes(n.id)),[me]);
 useEffect(()=>{if(!me||active==='account'||active==='users')return;const loaders:Partial<Record<SettingsSection,()=>Promise<unknown>>>={organization:settingsService.organization,roles:settingsService.permissions,security:settingsService.security,notifications:settingsService.notifications,branding:settingsService.branding,operations:settingsService.operations,integrations:settingsService.integrations,audit:settingsService.audit,system:settingsService.system};loaders[active]?.().then(setData).catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar')).finally(()=>setLoading(false))},[active,me]);
 if(loading&&!me)return <Skeleton/>; if(!me)return <ErrorBox message={error}/>;
 return <main className="space-y-6 pb-12"><PageHeader title="Configurações" description="Gerencie sua conta, organização, equipe, segurança e preferências do Impulse CRM." action={<Badge variant="primary"><Fingerprint className="mr-1 h-3.5 w-3.5"/>{ROLE_LABEL[me.businessRole]}</Badge>}/>
 <div className="lg:hidden"><Select aria-label="Seção de configurações" value={active} onChange={e=>{setLoading(true);setError('');setActive(e.target.value as SettingsSection)}} options={allowed.map(n=>({value:n.id,label:n.label}))}/></div>
 <div className="grid gap-6 lg:grid-cols-[260px_minmax(0,1fr)]"><Card padding="sm" className="hidden h-fit lg:block"><nav aria-label="Configurações" className="space-y-1">{allowed.map(n=><button key={n.id} onClick={()=>{setLoading(!['account','users'].includes(n.id));setError('');setActive(n.id);setNotice('')}} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-sm font-semibold ${active===n.id?'bg-blue-50 text-blue-700':'text-slate-600 hover:bg-slate-50'}`}><n.icon className="h-4 w-4"/>{n.label}<ChevronRight className="ml-auto h-4 w-4"/></button>)}</nav></Card>
 <section aria-live="polite">{notice&&<div className="mb-4 flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-800"><Check className="h-4 w-4"/>{notice}</div>}{error&&<ErrorBox message={error}/>} {loading?<Skeleton/>:<Section id={active} me={me} data={data} onMe={setMe} saved={()=>setNotice('Alterações salvas e registradas na auditoria.')} fail={setError}/>}</section></div></main>}
function Section({id,me,data,onMe,saved,fail}:{id:SettingsSection;me:SettingsMe;data:unknown;onMe:(m:SettingsMe)=>void;saved:()=>void;fail:(s:string)=>void}){
 if(id==='account')return <Account me={me} onMe={onMe} saved={saved} fail={fail}/>; if(id==='organization')return <Organization data={data as OrganizationSettings} saved={saved} fail={fail}/>; if(id==='roles')return <Permissions data={data as PermissionMatrix}/>; if(id==='integrations')return <Integration data={data as IntegrationStatus}/>; if(id==='audit')return <Audit data={data as AuditEntry[]}/>; if(id==='users')return <Unavailable title="Usuários e equipes" text="A administração segura de usuários permanece no módulo Corretores; equipes exigem um vínculo de equipe persistido antes de serem configuráveis aqui." href="/corretores"/>;
 if(id==='notifications')return <ToggleForm title="Notificações" description="Preferências pessoais por canal e evento." initial={(data as SettingsMe).settings??{}} fields={['notifyInApp','notifyEmail','notifyWhatsapp','notifyNewLeads','notifySla','notifyCampaigns','notifySecurity']} submit={settingsService.updateNotifications} saved={saved} fail={fail}/>;
 if(id==='branding')return <GenericForm title="Identidade visual" initial={data as Record<string,unknown>} fields={[['displayName','Nome exibido'],['logoUrl','URL do logo'],['faviconUrl','URL do ícone'],['primaryColor','Cor principal'],['secondaryColor','Cor secundária'],['signature','Assinatura'],['footer','Rodapé']]} submit={settingsService.updateBranding} saved={saved} fail={fail}/>;
 if(id==='operations')return <GenericForm title="Preferências operacionais" initial={data as Record<string,unknown>} fields={[['businessStartsAt','Início do atendimento'],['businessEndsAt','Fim do atendimento'],['dailyLeadLimit','Limite diário'],['slaMinutes','SLA (minutos)'],['contactAttempts','Tentativas de contato'],['redistributionMinutes','Redistribuição (minutos)']]} submit={settingsService.updateOperations} saved={saved} fail={fail}/>;
 if(id==='security')return <GenericForm title="Segurança" initial={data as Record<string,unknown>} fields={[['sessionTtlMinutes','Expiração da sessão (minutos)'],['maxLoginAttempts','Limite de tentativas']]} submit={settingsService.updateSecurity} saved={saved} fail={fail}/>;
 return <ToggleForm title="Sistema global" description="Políticas padrão, manutenção e recursos disponíveis." initial={data as Record<string,unknown>} fields={['maintenanceMode','allowOrganizationBranding']} submit={settingsService.updateSystem} saved={saved} fail={fail}/>}
function Account({me,onMe,saved,fail}:{me:SettingsMe;onMe:(m:SettingsMe)=>void;saved:()=>void;fail:(s:string)=>void}){const[f,setF]=useState({name:me.name,phone:me.phone??'',language:me.settings?.language??'pt-BR',timezone:me.settings?.timezone??'America/Sao_Paulo',dateFormat:me.settings?.dateFormat??'DD/MM/YYYY'});const save=()=>settingsService.updateMe(f).then(x=>{onMe(x);saved()}).catch(e=>fail(String(e)));return <Card><Heading title="Minha conta" text="Dados pessoais, preferências regionais e sessões ativas."/><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Nome" value={f.name} onChange={v=>setF({...f,name:v})}/><Input label="E-mail" value={me.email} disabled/><Field label="Telefone" value={f.phone} onChange={v=>setF({...f,phone:v})}/><Select label="Idioma" value={f.language} onChange={e=>setF({...f,language:e.target.value})} options={[{value:'pt-BR',label:'Português (Brasil)'},{value:'en-US',label:'English'},{value:'es',label:'Español'}]}/><Field label="Fuso horário" value={f.timezone} onChange={v=>setF({...f,timezone:v})}/><Select label="Formato de data" value={f.dateFormat} onChange={e=>setF({...f,dateFormat:e.target.value})} options={['DD/MM/YYYY','MM/DD/YYYY','YYYY-MM-DD'].map(v=>({value:v,label:v}))}/></div><div className="mt-5 flex justify-end"><Button onClick={save}><Save className="h-4 w-4"/>Salvar perfil</Button></div><div className="mt-7 border-t border-slate-200 pt-6"><h3 className="font-semibold text-slate-900">Contexto de acesso</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><Info label="Função" value={ROLE_LABEL[me.businessRole]}/><Info label="Organização" value={me.organization?.name??'Escopo global'}/><Info label="Conta criada" value={new Date(me.createdAt).toLocaleDateString('pt-BR')}/></div><h3 className="mt-6 font-semibold text-slate-900">Sessões ativas</h3><p className="mt-1 text-sm text-slate-500">{me.authSessions.length} sessão(ões). Tokens e credenciais nunca são exibidos.</p></div></Card>}
function Organization({data,saved,fail}:{data:OrganizationSettings;saved:()=>void;fail:(s:string)=>void}){const[f,setF]=useState({...data});return <GenericForm title="Organização" initial={f as unknown as Record<string,unknown>} fields={[['name','Nome'],['legalName','Razão social'],['document','Documento'],['email','E-mail'],['phone','Telefone'],['timezone','Fuso horário']]} submit={async d=>{const x=await settingsService.updateOrganization(d);setF(x);return x}} saved={saved} fail={fail}/>}
function GenericForm({title,initial,fields,submit,saved,fail}:{title:string;initial:Record<string,unknown>;fields:string[][];submit:(d:unknown)=>Promise<unknown>;saved:()=>void;fail:(s:string)=>void}){const[f,setF]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(([k])=>[k,String(initial?.[k]??'')])));return <Card><Heading title={title} text="Somente campos persistidos e validados pelo backend são apresentados."/><div className="mt-6 grid gap-4 sm:grid-cols-2">{fields.map(([k,l])=><Field key={k} label={l} value={f[k]} onChange={v=>setF({...f,[k]:v})}/>)}</div><div className="mt-5 flex justify-end"><Button onClick={()=>submit(Object.fromEntries(Object.entries(f).map(([k,v])=>[k,/Minutes$|Limit$|Attempts$/.test(k)&&v?Number(v):v]))).then(saved).catch(e=>fail(String(e)))}><Save className="h-4 w-4"/>Salvar</Button></div></Card>}
function ToggleForm({title,description,initial,fields,submit,saved,fail}:{title:string;description:string;initial:Record<string,unknown>;fields:string[];submit:(d:unknown)=>Promise<unknown>;saved:()=>void;fail:(s:string)=>void}){const[f,setF]=useState<Record<string,boolean>>(()=>Object.fromEntries(fields.map(k=>[k,Boolean(initial?.[k])])));return <Card><Heading title={title} text={description}/><div className="mt-5 divide-y divide-slate-100">{fields.map(k=><label key={k} className="flex min-h-14 items-center justify-between gap-4"><span className="text-sm font-medium text-slate-700">{k.replace(/([A-Z])/g,' $1')}</span><input className="h-5 w-5 accent-blue-600" type="checkbox" checked={f[k]} onChange={e=>setF({...f,[k]:e.target.checked})}/></label>)}</div><div className="mt-5 flex justify-end"><Button onClick={()=>submit(f).then(saved).catch(e=>fail(String(e)))}><Save className="h-4 w-4"/>Salvar</Button></div></Card>}
function Permissions({data}:{data:PermissionMatrix}){const codes=[...new Set(data.roles.flatMap(r=>r.permissions.map(p=>p.permission.code)))].filter(c=>c.startsWith('settings:'));return <Card padding="none"><div className="p-6"><Heading title="Funções e permissões" text="ORG_ADMIN é mantido internamente por compatibilidade e exibido como Superintendente."/></div><TableContainer className="rounded-none border-x-0 border-b-0 shadow-none"><Table><TableHeader><TableRow><TableHead>Permissão</TableHead>{data.roles.map(r=><TableHead key={r.code} align="center">{data.businessLabels[r.code]}</TableHead>)}</TableRow></TableHeader><TableBody>{codes.map(c=><TableRow key={c}><TableCell className="font-mono text-xs">{c}</TableCell>{data.roles.map(r=><TableCell key={r.code} align="center">{r.permissions.some(p=>p.permission.code===c)?<Check className="mx-auto h-4 w-4 text-emerald-600"/>:<span className="text-slate-300">—</span>}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer></Card>}
function Integration({data}:{data:IntegrationStatus}){return <Card><Heading title="Integrações" text="Central de status e atalhos; nenhum segredo é retornado pela API."/><div className="mt-5 space-y-3">{data.items.map(i=><Link key={i.id} href={i.href} className="flex items-center gap-4 rounded-xl border border-slate-200 p-4 hover:border-blue-300"><div className="rounded-lg bg-blue-50 p-2 text-blue-600"><Cable className="h-5 w-5"/></div><div><p className="font-semibold text-slate-900">{i.name}</p><p className="text-sm text-slate-500">{i.health}</p></div><Badge className="ml-auto" variant="success">Operacional</Badge></Link>)}</div></Card>}
function Audit({data}:{data:AuditEntry[]}){return <Card padding="none"><div className="p-6"><Heading title="Auditoria" text="Alterações sanitizadas no escopo autorizado."/></div>{data.length?<TableContainer className="rounded-none border-x-0 border-b-0 shadow-none"><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Usuário</TableHead><TableHead>Ação</TableHead><TableHead>Entidade</TableHead></TableRow></TableHeader><TableBody>{data.map(x=><TableRow key={x.id}><TableCell>{new Date(x.occurredAt).toLocaleString('pt-BR')}</TableCell><TableCell>{x.actorUser?.name??'Sistema'}</TableCell><TableCell><Badge>{x.action}</Badge></TableCell><TableCell>{x.entityType}</TableCell></TableRow>)}</TableBody></Table></TableContainer>:<div className="p-8"><EmptyState title="Sem eventos" description="Ações auditáveis aparecerão aqui."/></div>}</Card>}
function Unavailable({title,text,href}:{title:string;text:string;href:string}){return <Card><EmptyState title={title} description={text} action={<Link className="font-semibold text-blue-600" href={href}>Abrir módulo responsável</Link>}/></Card>}
function Heading({title,text}:{title:string;text:string}){return <div><h2 className="text-xl font-bold text-slate-950">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div>} function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-slate-900">{value}</p></div>} function ErrorBox({message}:{message:string}){return <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{message}</div>} function Skeleton(){return <div className="flex min-h-48 items-center justify-center text-slate-500"><LoaderCircle className="mr-2 h-5 w-5 animate-spin"/>Carregando configurações…</div>}
