import { BadRequestException, ForbiddenException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { createHash, createHmac, randomBytes, timingSafeEqual } from 'crypto';
import { Prisma, Role } from '@prisma/client';
import { AccessContextService, AuthenticatedUserRef } from '../auth/access-context.service';
import { AuditService } from '../audit/audit.service';
import { PrismaService } from '../prisma/prisma.service';
import { AssignConversationDto, UpdateConversationDto } from './dto/conversations.dto';
import { CreateWhatsappAccountDto } from './dto/create-whatsapp-account.dto';
import { ListWhatsappDto } from './dto/list-whatsapp.dto';
import { SendMediaMessageDto, SendTemplateMessageDto, SendTextMessageDto } from './dto/messages.dto';
import { SyncWhatsappTemplatesDto } from './dto/sync-whatsapp-templates.dto';
import { UpdateWhatsappAccountDto, UpdateWhatsappAccountStatusDto } from './dto/update-whatsapp-account.dto';
import { MetaWhatsappClient } from './meta/meta-whatsapp.client';
import { WhatsappWindowPolicy } from './policies/whatsapp-window.policy';
import { WhatsappCredentialCryptoService } from './security/credential-crypto.service';
import { redactSecrets, sanitizeError } from './security/redact';

const selectAccount = { id: true, organizationId: true, name: true, phoneNumber: true, normalizedPhone: true, displayPhoneNumber: true, verifiedName: true, phoneNumberId: true, businessAccountId: true, appId: true, apiVersion: true, status: true, isDefault: true, qualityRating: true, messagingLimitTier: true, connectedAt: true, lastSyncAt: true, lastConnectionTestAt: true, lastConnectionError: true, createdByUserId: true, createdAt: true, updatedAt: true, deletedAt: true };
function randomVerifyToken() { return randomBytes(24).toString('hex'); }
const statusRank: Record<string, number> = { SENT: 1, DELIVERED: 2, READ: 3, FAILED: 4 };

@Injectable()
export class WhatsappService {
  constructor(private readonly prisma: PrismaService, private readonly access: AccessContextService, private readonly audit: AuditService, private readonly crypto: WhatsappCredentialCryptoService, private readonly meta: MetaWhatsappClient, private readonly windowPolicy: WhatsappWindowPolicy) {}
  normalizePhone(phone: string) { const digits = (phone || '').replace(/\D/g, ''); if (digits.length < 10 || digits.length > 15) throw new BadRequestException('WHATSAPP_INVALID_PHONE'); return digits.startsWith('55') || digits.length > 11 ? `+${digits}` : `+55${digits}`; }
  private scope(ctx: { global: boolean; organizationId: string | null }) { if (ctx.global) throw new BadRequestException('WHATSAPP_ORGANIZATION_CONTEXT_REQUIRED'); if (!ctx.organizationId) throw new ForbiddenException('Organização obrigatória'); return ctx.organizationId; }
    private async accountInOrg(id: string, org: string, withSecrets = false) { const a = await this.prisma.whatsappAccount.findFirst({ where: { id, organizationId: org, deletedAt: null }, ...(withSecrets ? {} : { select: selectAccount }) }); if (!a) throw new NotFoundException('Conta WhatsApp não encontrada'); return a as any; }
  private async auditSafe(org: string, action: string, entityType: string, entityId: string, actor: string | null, before?: unknown, after?: unknown) { await this.audit.record({ organizationId: org, actorUserId: actor, module: 'whatsapp', entityType, entityId, action, before: redactSecrets(before) as Prisma.InputJsonValue, after: redactSecrets(after) as Prisma.InputJsonValue }); }

  async findAccounts(q: ListWhatsappDto, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const page = Math.max(1, q.page ?? 1), pageSize = Math.min(100, q.pageSize ?? q.limit ?? 20); const includeArchived = q.state === 'archived' || q.state === 'all' || q.archived === 'true'; const where: Prisma.WhatsappAccountWhereInput = { organizationId: org, ...(includeArchived ? {} : { deletedAt: null }), ...(q.state === 'archived' ? { deletedAt: { not: null } } : {}), ...(q.state === 'active' ? { status: 'ACTIVE' as never } : {}), ...(q.state === 'inactive' ? { status: 'INACTIVE' as never } : {}), ...(q.status ? { status: q.status as never } : {}), ...(q.search ? { OR: [{ name: { contains: q.search, mode: 'insensitive' } }, { phoneNumber: { contains: q.search } }, { displayPhoneNumber: { contains: q.search } }, { verifiedName: { contains: q.search, mode: 'insensitive' } }, { businessAccountId: { contains: q.search } }, { phoneNumberId: { contains: q.search } }] } : {}) }; const [items,total] = await this.prisma.$transaction([this.prisma.whatsappAccount.findMany({ where, select: selectAccount, orderBy: [{ isDefault: 'desc' }, { createdAt: 'desc' }, { id: 'asc' }], skip: (page-1)*pageSize, take: pageSize }), this.prisma.whatsappAccount.count({ where })]); return { items, page, pageSize, total, totalPages: Math.max(1, Math.ceil(total/pageSize)) }; }
  async getAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); return this.accountInOrg(id, this.scope(ctx)); }
  async createAccount(d: CreateWhatsappAccountDto, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const normalizedPhone = this.normalizePhone(d.phoneNumber || d.phoneNumberId); const phoneNumberId = d.phoneNumberId.trim(); const businessAccountId = d.businessAccountId.trim(); const dup = await this.prisma.whatsappAccount.findFirst({ where: { organizationId: org, deletedAt: null, OR: [{ phoneNumberId }, { businessAccountId, phoneNumberId }, { normalizedPhone }] } }); if (dup) throw new BadRequestException('WHATSAPP_ACCOUNT_DUPLICATE_PHONE'); const data = { organizationId: org, name: d.name.trim(), phoneNumber: (d.phoneNumber || d.phoneNumberId).trim(), normalizedPhone, phoneNumberId, businessAccountId, appId: d.appId?.trim(), apiVersion: d.apiVersion?.trim(), accessToken: this.crypto.encrypt(d.accessToken.trim()), verifyToken: this.crypto.encrypt((d.verifyToken || randomVerifyToken()).trim()), appSecret: d.appSecret ? this.crypto.encrypt(d.appSecret) : undefined, webhookSecret: d.webhookSecret ? this.crypto.encrypt(d.webhookSecret) : undefined, status: (d.status || (d.active === false ? 'INACTIVE' : 'PENDING')) as never, createdByUserId: ctx.id }; const created = await this.prisma.whatsappAccount.create({ data, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.created', 'WhatsappAccount', created.id, ctx.id, null, created); return created; }
  async updateAccount(id: string, d: UpdateWhatsappAccountDto, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const cur = await this.accountInOrg(id, org, true); const normalizedPhone = d.phoneNumber ? this.normalizePhone(d.phoneNumber) : undefined; if (normalizedPhone && normalizedPhone !== cur.normalizedPhone) { const dup = await this.prisma.whatsappAccount.findFirst({ where: { organizationId: org, normalizedPhone, deletedAt: null, id: { not: id } } }); if (dup) throw new BadRequestException('WHATSAPP_ACCOUNT_DUPLICATE_PHONE'); } const updated = await this.prisma.whatsappAccount.update({ where: { id }, data: { name: d.name?.trim(), phoneNumber: d.phoneNumber, normalizedPhone, phoneNumberId: d.phoneNumberId?.trim(), businessAccountId: d.businessAccountId?.trim(), appId: d.appId?.trim(), apiVersion: d.apiVersion?.trim(), status: d.status as never, accessToken: d.accessToken ? this.crypto.encrypt(d.accessToken) : undefined, verifyToken: d.verifyToken ? this.crypto.encrypt(d.verifyToken) : undefined, appSecret: d.appSecret ? this.crypto.encrypt(d.appSecret) : undefined, webhookSecret: d.webhookSecret ? this.crypto.encrypt(d.webhookSecret) : undefined }, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.updated', 'WhatsappAccount', id, ctx.id, cur, updated); return updated; }
  async archiveAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const cur = await this.accountInOrg(id, org); const activeCampaign = await this.prisma.campaign.findFirst({ where: { organizationId: org, whatsappAccountId: id, deletedAt: null, archivedAt: null, status: { in: ['RUNNING', 'SCHEDULED'] as never } } }); if (activeCampaign) throw new BadRequestException('WHATSAPP_ACCOUNT_HAS_ACTIVE_CAMPAIGN'); await this.prisma.whatsappAccount.update({ where: { id }, data: { deletedAt: new Date(), status: 'DISCONNECTED' as never, isDefault: false } }); await this.auditSafe(org, 'whatsapp.account.archived', 'WhatsappAccount', id, ctx.id, cur, { id, deletedAt: true }); return { success: true }; }
  async restoreAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const cur = await this.prisma.whatsappAccount.findFirst({ where: { id, organizationId: org } }); if (!cur) throw new NotFoundException('Conta WhatsApp não encontrada'); const dup = await this.prisma.whatsappAccount.findFirst({ where: { organizationId: org, deletedAt: null, id: { not: id }, OR: [{ phoneNumberId: cur.phoneNumberId }, { normalizedPhone: cur.normalizedPhone }] } }); if (dup) throw new BadRequestException('WHATSAPP_ACCOUNT_DUPLICATE_PHONE'); const up = await this.prisma.whatsappAccount.update({ where: { id }, data: { deletedAt: null, status: 'INACTIVE' as never, isDefault: false }, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.restored', 'WhatsappAccount', id, ctx.id, cur, up); return up; }
  async testAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const a = await this.accountInOrg(id, org, true); try { const r = await this.meta.testConnection({ accessToken: this.crypto.decrypt(a.accessToken), phoneNumberId: a.phoneNumberId, apiVersion: a.apiVersion }); const up = await this.prisma.whatsappAccount.update({ where: { id }, data: { status: r.ok ? 'ACTIVE' as never : 'ERROR' as never, connectedAt: r.ok ? new Date() : a.connectedAt, displayPhoneNumber: r.displayPhoneNumber, verifiedName: r.verifiedName, qualityRating: r.qualityRating, messagingLimitTier: r.messagingLimitTier, lastConnectionTestAt: new Date(), lastConnectionError: null }, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.tested', 'WhatsappAccount', id, ctx.id, null, { ok: r.ok }); return up; } catch(e) { const err = sanitizeError(e); await this.prisma.whatsappAccount.update({ where: { id }, data: { status: 'ERROR' as never, lastConnectionTestAt: new Date(), lastConnectionError: err } }); throw new BadRequestException({ code: 'WHATSAPP_META_CONNECTION_FAILED', message: err }); } }


  async updateAccountStatus(id: string, d: UpdateWhatsappAccountStatusDto, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const cur = await this.accountInOrg(id, org); const up = await this.prisma.whatsappAccount.update({ where: { id }, data: { status: d.status as never, isDefault: d.status === 'INACTIVE' ? false : undefined }, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.status_updated', 'WhatsappAccount', id, ctx.id, cur, up); return up; }
  async setDefaultAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); await this.accountInOrg(id, org); const [, up] = await this.prisma.$transaction([this.prisma.whatsappAccount.updateMany({ where: { organizationId: org, deletedAt: null, isDefault: true }, data: { isDefault: false } }), this.prisma.whatsappAccount.update({ where: { id }, data: { isDefault: true, status: 'ACTIVE' as never }, select: selectAccount })]); await this.auditSafe(org, 'whatsapp.account.default_set', 'WhatsappAccount', id, ctx.id, null, { id }); return up; }
  async syncAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const a = await this.accountInOrg(id, org, true); try { const r = await this.meta.syncAccount({ accessToken: this.crypto.decrypt(a.accessToken), phoneNumberId: a.phoneNumberId, apiVersion: a.apiVersion }); const up = await this.prisma.whatsappAccount.update({ where: { id }, data: { displayPhoneNumber: r.displayPhoneNumber, verifiedName: r.verifiedName, qualityRating: r.qualityRating, messagingLimitTier: r.messagingLimitTier, status: 'ACTIVE' as never, lastSyncAt: new Date(), lastConnectionError: null }, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.synced', 'WhatsappAccount', id, ctx.id, null, { id }); return up; } catch(e) { const err = sanitizeError(e); const up = await this.prisma.whatsappAccount.update({ where: { id }, data: { status: 'ERROR' as never, lastConnectionError: err }, select: selectAccount }); throw new BadRequestException({ code: 'WHATSAPP_META_SYNC_FAILED', message: err, account: up }); } }

  async listConversations(q: ListWhatsappDto, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const page=q.page??1, limit=q.limit??20; const brokerOnly = ctx.role === Role.BROKER && !ctx.permissions.includes('whatsapp:conversations:read-all'); const where:any = { organizationId: org, deletedAt: null, ...(q.status ? { status: q.status } : {}), ...(brokerOnly ? { assignedUserId: ctx.id } : {}) }; const [items,total] = await this.prisma.$transaction([this.prisma.whatsappConversation.findMany({ where, orderBy:{ lastMessageAt:'desc'}, skip:(page-1)*limit, take:limit }), this.prisma.whatsappConversation.count({ where })]); return { items, meta:{total,page,limit,totalPages:Math.max(1,Math.ceil(total/limit))} }; }
  async getConversation(id:string,user:AuthenticatedUserRef){ const ctx=await this.access.resolve(user); const org=this.scope(ctx); const c=await this.prisma.whatsappConversation.findFirst({where:{id,organizationId:org,deletedAt:null}}); if(!c) throw new NotFoundException('Conversa não encontrada'); if(ctx.role===Role.BROKER && c.assignedUserId!==ctx.id && !ctx.permissions.includes('whatsapp:conversations:read-all')) throw new ForbiddenException('WHATSAPP_CONVERSATION_FORBIDDEN'); return c; }
  async updateConversation(id:string,d:UpdateConversationDto,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); return this.prisma.whatsappConversation.update({where:{id},data:{status:d.status as never,contactName:d.contactName}}); }
  async assignConversation(id:string,d:AssignConversationDto,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); if(d.assignedUserId) await this.ensureUser(c.organizationId,d.assignedUserId); if(d.managerUserId) await this.ensureUser(c.organizationId,d.managerUserId); const up=await this.prisma.whatsappConversation.update({where:{id},data:{assignedUserId:d.assignedUserId??null,managerUserId:d.managerUserId??null}}); await this.auditSafe(c.organizationId,'whatsapp.conversation.assigned','WhatsappConversation',id,user.id,c,up); return up; }
  async closeConversation(id:string,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); const up=await this.prisma.whatsappConversation.update({where:{id},data:{status:'CLOSED' as never,unreadCount:0}}); await this.auditSafe(c.organizationId,'whatsapp.conversation.closed','WhatsappConversation',id,user.id,c,up); return up; }
  async reopenConversation(id:string,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); const up=await this.prisma.whatsappConversation.update({where:{id},data:{status:'OPEN' as never}}); await this.auditSafe(c.organizationId,'whatsapp.conversation.reopened','WhatsappConversation',id,user.id,c,up); return up; }
  async messages(id:string,q:ListWhatsappDto,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); const page=q.page??1, limit=q.limit??20; return this.prisma.whatsappMessage.findMany({where:{organizationId:c.organizationId,conversationId:id},orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit}); }
  async sendText(id:string,d:SendTextMessageDto,user:AuthenticatedUserRef){ const c:any=await this.getConversation(id,user); if(!this.windowPolicy.canSendFreeMessage(c.customerServiceWindowEndsAt)) throw new BadRequestException('WHATSAPP_CUSTOMER_SERVICE_WINDOW_CLOSED'); return this.sendOutbound(c,d,user,'TEXT'); }
  async sendMedia(id:string,d:SendMediaMessageDto,user:AuthenticatedUserRef){ const c:any=await this.getConversation(id,user); if(!this.windowPolicy.canSendFreeMessage(c.customerServiceWindowEndsAt)) throw new BadRequestException('WHATSAPP_CUSTOMER_SERVICE_WINDOW_CLOSED'); return this.sendOutbound(c,d,user,'MEDIA'); }
  async sendTemplate(id:string,d:SendTemplateMessageDto,user:AuthenticatedUserRef){ const c:any=await this.getConversation(id,user); const t:any=await this.prisma.whatsappTemplate.findFirst({where:{id:d.templateId,organizationId:c.organizationId,whatsappAccountId:c.whatsappAccountId,deletedAt:null}}); if(!t||t.status!=='APPROVED') throw new BadRequestException('WHATSAPP_TEMPLATE_NOT_APPROVED'); return this.sendOutbound(c,{...d,template:t},user,'TEMPLATE'); }
  private async sendOutbound(c:any,d:any,user:AuthenticatedUserRef,kind:'TEXT'|'TEMPLATE'|'MEDIA'){ const a:any=await this.accountInOrg(c.whatsappAccountId,c.organizationId,true); const msg=await this.prisma.whatsappMessage.create({data:{organizationId:c.organizationId,whatsappAccountId:a.id,conversationId:c.id,leadId:c.leadId,direction:'OUTBOUND' as never,type:(kind==='MEDIA'?d.type.toUpperCase():kind) as never,status:'PENDING' as never,senderPhone:a.normalizedPhone,recipientPhone:c.normalizedPhone,text:d.text,mediaId:d.mediaId,templateName:d.template?.name,templateLanguage:d.template?.language,replyToExternalMessageId:d.replyToExternalMessageId,createdByUserId:user.id}}); try{ const accessToken=this.crypto.decrypt(a.accessToken); const r=kind==='TEXT'?await this.meta.sendText({accessToken,phoneNumberId:a.phoneNumberId,to:c.normalizedPhone.replace('+',''),text:d.text,replyToExternalMessageId:d.replyToExternalMessageId}):kind==='TEMPLATE'?await this.meta.sendTemplate({accessToken,phoneNumberId:a.phoneNumberId,to:c.normalizedPhone.replace('+',''),name:d.template.name,language:d.template.language,components:d.components}):await this.meta.sendMedia({accessToken,phoneNumberId:a.phoneNumberId,to:c.normalizedPhone.replace('+',''),type:d.type,mediaId:d.mediaId,caption:d.caption}); const up=await this.prisma.whatsappMessage.update({where:{id:msg.id},data:{externalMessageId:r.externalMessageId,status:'SENT' as never,sentAt:new Date()}}); await this.prisma.whatsappConversation.update({where:{id:c.id},data:{lastMessageAt:new Date(),lastOutboundAt:new Date()}}); await this.auditSafe(c.organizationId,'whatsapp.message.sent','WhatsappMessage',msg.id,user.id,null,{id:msg.id,status:'SENT'}); return up; }catch(e){ const err=sanitizeError(e); await this.prisma.whatsappMessage.update({where:{id:msg.id},data:{status:'FAILED' as never,errorMessage:err,failedAt:new Date()}}); await this.auditSafe(c.organizationId,'whatsapp.message.failed','WhatsappMessage',msg.id,user.id,null,{id:msg.id,errorMessage:err}); throw new BadRequestException({code:'WHATSAPP_META_SEND_FAILED',message:err}); }}

  async findTemplates(q: ListWhatsappDto, user: AuthenticatedUserRef) { const ctx=await this.access.resolve(user); const org=this.scope(ctx); return this.prisma.whatsappTemplate.findMany({where:{organizationId:org,deletedAt:null,...(q.status?{status:q.status as never}:{})},orderBy:{updatedAt:'desc'}}); }
  async getTemplate(id:string,user:AuthenticatedUserRef){ const ctx=await this.access.resolve(user); const t=await this.prisma.whatsappTemplate.findFirst({where:{id,organizationId:this.scope(ctx),deletedAt:null}}); if(!t) throw new NotFoundException('Template não encontrado'); return t; }
  async syncTemplates(d: SyncWhatsappTemplatesDto, user: AuthenticatedUserRef) { const ctx=await this.access.resolve(user); const org=this.scope(ctx); const a:any=await this.accountInOrg(d.accountId,org,true); const templates=await this.meta.syncTemplates({accessToken:this.crypto.decrypt(a.accessToken),businessAccountId:a.businessAccountId}); for(const t of templates) await this.prisma.whatsappTemplate.upsert({where:{organizationId_whatsappAccountId_name_language:{organizationId:org,whatsappAccountId:a.id,name:t.name,language:t.language}},update:{externalTemplateId:t.id,category:t.category,status:t.status as never,components:t.components as Prisma.InputJsonValue,lastSyncedAt:new Date()},create:{organizationId:org,whatsappAccountId:a.id,externalTemplateId:t.id,name:t.name,language:t.language,category:t.category,status:t.status as never,components:t.components as Prisma.InputJsonValue,lastSyncedAt:new Date()}}); await this.prisma.whatsappAccount.update({where:{id:a.id},data:{lastSyncAt:new Date()}}); await this.auditSafe(org,'whatsapp.templates.synced','WhatsappAccount',a.id,ctx.id,null,{count:templates.length}); return {success:true,count:templates.length}; }

  async verifyWebhook(mode?: string, verifyToken?: string, challenge?: string) { if (mode !== 'subscribe' || !verifyToken || !challenge) throw new BadRequestException('WHATSAPP_WEBHOOK_VERIFY_INVALID'); const accounts=await this.prisma.whatsappAccount.findMany({where:{deletedAt:null}}) as any[]; const found=accounts.find(a=>this.crypto.decrypt(a.verifyToken)===verifyToken); if(!found) throw new UnauthorizedException('WHATSAPP_WEBHOOK_VERIFY_TOKEN_INVALID'); return challenge; }
  validateSignature(raw: Buffer, signature: string|undefined, appSecret: string|undefined){ if(!appSecret) return; if(!signature?.startsWith('sha256=')) throw new UnauthorizedException('WHATSAPP_WEBHOOK_SIGNATURE_INVALID'); const expected='sha256='+createHmac('sha256',appSecret).update(raw).digest('hex'); if(!timingSafeEqual(Buffer.from(expected),Buffer.from(signature))) throw new UnauthorizedException('WHATSAPP_WEBHOOK_SIGNATURE_INVALID'); }
  async receiveWebhook(payload:any, raw:Buffer, signature?:string){ const changes=payload?.entry?.flatMap((e:any)=>e.changes||[])||[]; for(const change of changes){ const value=change.value||{}; const phoneNumberId=value.metadata?.phone_number_id; const account:any=await this.prisma.whatsappAccount.findFirst({where:{deletedAt:null,OR:[{phoneNumberId},{businessAccountId:value.metadata?.business_account_id||''}]}}); if(!account) continue; this.validateSignature(raw,signature,account.appSecret?this.crypto.decrypt(account.appSecret):undefined); await this.processValue(account,value); } return {success:true}; }
  private async processValue(account:any,value:any){ for(const m of value.messages||[]) await this.processInbound(account,value,m); for(const s of value.statuses||[]) await this.processStatus(account,s); }
  private async createEvent(account:any,type:string,key:string,externalMessageId?:string,payload?:unknown){ try{return await this.prisma.whatsappWebhookEvent.create({data:{organizationId:account.organizationId,whatsappAccountId:account.id,eventType:type,deduplicationKey:key,externalMessageId,sanitizedPayload:redactSecrets(payload) as Prisma.InputJsonValue}});}catch{return null;} }
  private async processInbound(account:any,value:any,m:any){ const key=m.id||createHash('sha256').update(JSON.stringify(m)).digest('hex'); const ev=await this.createEvent(account,'message',key,m.id,{id:m.id,type:m.type}); if(!ev) return; const phone=this.normalizePhone(m.from); const contact=value.contacts?.find((c:any)=>c.wa_id===m.from); const lead=await this.findOrCreateLead(account.organizationId,phone,contact?.profile?.name); const now=new Date(Number(m.timestamp||Date.now()/1000)*1000); const ends=this.windowPolicy.windowEndsAt(now); let conv:any=await this.prisma.whatsappConversation.findFirst({where:{whatsappAccountId:account.id,normalizedPhone:phone,deletedAt:null}}); if(conv) conv=await this.prisma.whatsappConversation.update({where:{id:conv.id},data:{leadId:lead.id,contactName:contact?.profile?.name,lastMessageAt:now,lastInboundAt:now,customerServiceWindowEndsAt:ends,status:'OPEN' as never,unreadCount:{increment:1}}}); else conv=await this.prisma.whatsappConversation.create({data:{organizationId:account.organizationId,whatsappAccountId:account.id,leadId:lead.id,contactPhone:m.from,normalizedPhone:phone,contactName:contact?.profile?.name,lastMessageAt:now,lastInboundAt:now,customerServiceWindowEndsAt:ends,unreadCount:1}}); await this.prisma.whatsappMessage.upsert({where:{organizationId_externalMessageId:{organizationId:account.organizationId,externalMessageId:m.id}},update:{},create:{organizationId:account.organizationId,whatsappAccountId:account.id,conversationId:conv.id,leadId:lead.id,externalMessageId:m.id,direction:'INBOUND' as never,type:this.mapType(m.type) as never,status:'RECEIVED' as never,senderPhone:phone,recipientPhone:account.normalizedPhone,text:m.text?.body,mediaId:m.image?.id||m.document?.id||m.audio?.id||m.video?.id,mimeType:m.image?.mime_type||m.document?.mime_type||m.audio?.mime_type||m.video?.mime_type,fileName:m.document?.filename,metadata:redactSecrets({location:m.location,interactive:m.interactive,contacts:m.contacts,unknown:m.type&&!['text','image','document','audio','video','location','interactive','contacts'].includes(m.type)?m:undefined}) as Prisma.InputJsonValue,createdAt:now}}); await this.prisma.whatsappWebhookEvent.update({where:{id:ev.id},data:{status:'PROCESSED' as never,processedAt:new Date()}}); }
  private async processStatus(account: any, s: any) {
    const key = `${s.id}:${s.status}:${s.timestamp || ''}`;
    const ev = await this.createEvent(account, 'status', key, s.id, {
      id: s.id,
      status: s.status,
      errors: s.errors,
    });
    if (!ev) return;

    const msg: any = await this.prisma.whatsappMessage.findFirst({
      where: { organizationId: account.organizationId, externalMessageId: s.id },
    });

    if (msg) {
      const status = this.mapStatus(s.status);
      if (statusRank[status] >= statusRank[msg.status] || status === 'FAILED') {
        await this.prisma.whatsappMessage.update({
          where: { id: msg.id },
          data: {
            status: status as never,
            deliveredAt: status === 'DELIVERED' ? new Date() : undefined,
            readAt: status === 'READ' ? new Date() : undefined,
            failedAt: status === 'FAILED' ? new Date() : undefined,
            errorCode: s.errors?.[0]?.code?.toString(),
            errorMessage: s.errors?.[0]?.title?.slice(0, 500),
          },
        });
        await this.updateDistributionFromWhatsappMessage(msg, status, s.errors?.[0]?.title);
      }
    }

    await this.prisma.whatsappWebhookEvent.update({
      where: { id: ev.id },
      data: { status: 'PROCESSED' as never, processedAt: new Date() },
    });
  }
  private async updateDistributionFromWhatsappMessage(msg:any,status:string,errorMessage?:string){ const distributionId=msg.metadata?.distributionId; if(!distributionId) return; await this.prisma.leadDistribution.update({where:{id:distributionId},data:{status:status==='FAILED'?'FAILED' as never:status==='DELIVERED'?'DELIVERED' as never:status==='READ'?'READ' as never:'CONTACT_SENT' as never,errorMessage:errorMessage?.slice(0,500)??null}}).catch(()=>undefined); }
  private mapType(t:string){ return ({text:'TEXT',image:'IMAGE',document:'DOCUMENT',audio:'AUDIO',video:'VIDEO',location:'LOCATION',interactive:'INTERACTIVE',contacts:'CONTACTS'} as any)[t]||'UNKNOWN'; }
  private mapStatus(s:string){ return ({sent:'SENT',delivered:'DELIVERED',read:'READ',failed:'FAILED'} as any)[s]||'SENT'; }
  private async findOrCreateLead(org:string,phone:string,name?:string){ const existing=await this.prisma.lead.findFirst({where:{organizationId:org,normalizedPhone:phone,deletedAt:null}}); if(existing) return existing; const lead=await this.prisma.lead.create({data:{organizationId:org,phone,normalizedPhone:phone,name:name||null,source:'WHATSAPP' as never,createdByUserId:null,lastInteractionAt:new Date()}}); await this.prisma.leadEvent.create({data:{organizationId:org,leadId:lead.id,eventType:'LEAD_CREATED' as never,description:'Lead criado automaticamente por mensagem WhatsApp oficial',idempotencyKey:`whatsapp-auto-lead:${org}:${phone}`,payload:{source:'WHATSAPP'}}}).catch(()=>undefined); return lead; }
  private async ensureUser(org:string,userId:string){ const u=await this.prisma.user.findFirst({where:{id:userId,organizationId:org,status:'ACTIVE',deletedAt:null}}); if(!u) throw new BadRequestException('WHATSAPP_USER_NOT_IN_ORGANIZATION'); }
}
