import { BadRequestException, ForbiddenException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { createHash, createHmac, randomBytes, timingSafeEqual } from 'crypto';
import { Prisma, Role } from '@prisma/client';
import { AccessContextService, AuthenticatedUserRef } from '../auth/access-context.service';
import { AuditService } from '../audit/audit.service';
import { PrismaService } from '../prisma/prisma.service';
import { AssignConversationDto, UpdateConversationDto } from './dto/conversations.dto';
import { CreateWhatsappAccountDto } from './dto/create-whatsapp-account.dto';
import { CreateManualWhatsappAccountDto } from './dto/create-manual-whatsapp-account.dto';
import { CreateWhatsappTemplateDto } from './dto/create-whatsapp-template.dto';
import { ListWhatsappDto } from './dto/list-whatsapp.dto';
import { ListWhatsappTemplatesDto } from './dto/list-whatsapp-templates.dto';
import { SendMediaMessageDto, SendTemplateMessageDto, SendTextMessageDto } from './dto/messages.dto';
import { SyncWhatsappTemplatesDto } from './dto/sync-whatsapp-templates.dto';
import { UpdateWhatsappAccountDto, UpdateWhatsappAccountStatusDto } from './dto/update-whatsapp-account.dto';
import { UpdateWhatsappTemplateDto } from './dto/update-whatsapp-template.dto';
import { MetaWhatsappClient } from './meta/meta-whatsapp.client';
import { WhatsappWindowPolicy } from './policies/whatsapp-window.policy';
import { WhatsappCredentialCryptoService } from './security/credential-crypto.service';
import { redactSecrets, sanitizeError } from './security/redact';
import { parseMetaTemplateComponents, toSafeTemplate } from './templates/template-components';
import { classifyMetaError } from '../messaging/meta-error-classifier';

const selectAccount = { id: true, organizationId: true, name: true, provider: true, wabaId: true, phoneNumber: true, normalizedPhone: true, displayPhoneNumber: true, verifiedName: true, phoneNumberId: true, businessAccountId: true, appId: true, apiVersion: true, status: true, isDefault: true, qualityRating: true, messagingLimitTier: true, connectedAt: true, lastSyncAt: true, lastConnectionTestAt: true, lastConnectionError: true, webhookSubscribedAt: true, tokenConfigured: true, tokenLast4: true, createdByUserId: true, createdAt: true, updatedAt: true, deletedAt: true };
function randomVerifyToken() { return randomBytes(24).toString('hex'); }
const statusRank: Record<string, number> = { SENT: 1, DELIVERED: 2, READ: 3, FAILED: 4 };

@Injectable()
export class WhatsappService {
  constructor(private readonly prisma: PrismaService, private readonly access: AccessContextService, private readonly audit: AuditService, private readonly crypto: WhatsappCredentialCryptoService, private readonly meta: MetaWhatsappClient, private readonly windowPolicy: WhatsappWindowPolicy) {}
  normalizePhone(phone: string) { const digits = (phone || '').replace(/\D/g, ''); if (digits.length < 10 || digits.length > 15) throw new BadRequestException('WHATSAPP_INVALID_PHONE'); return digits.startsWith('55') || digits.length > 11 ? `+${digits}` : `+55${digits}`; }
  private scope(ctx: { global: boolean; organizationId: string | null }) { if (ctx.global) throw new BadRequestException('WHATSAPP_ORGANIZATION_CONTEXT_REQUIRED'); if (!ctx.organizationId) throw new ForbiddenException('Organização obrigatória'); return ctx.organizationId; }
    private async accountInOrg(id: string, org: string, withSecrets = false) { const a = await this.prisma.whatsappAccount.findFirst({ where: { id, organizationId: org, deletedAt: null }, ...(withSecrets ? {} : { select: selectAccount }) }); if (!a) throw new NotFoundException('Conta WhatsApp não encontrada'); return a as any; }
  private async auditSafe(org: string, action: string, entityType: string, entityId: string, actor: string | null, before?: unknown, after?: unknown) { await this.audit.record({ organizationId: org, actorUserId: actor, module: 'whatsapp', entityType, entityId, action, before: redactSecrets(before) as Prisma.InputJsonValue, after: redactSecrets(after) as Prisma.InputJsonValue }); }

  async findAccounts(q: ListWhatsappDto, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const page = Math.max(1, q.page ?? 1), pageSize = Math.min(100, q.pageSize ?? q.limit ?? 20); const includeArchived = q.state === 'archived' || q.state === 'all' || q.archived === 'true'; const where: Prisma.WhatsappAccountWhereInput = { organizationId: org, ...(includeArchived ? {} : { deletedAt: null }), ...(q.state === 'archived' ? { deletedAt: { not: null } } : {}), ...(q.state === 'active' ? { status: 'ACTIVE' as never } : {}), ...(q.state === 'inactive' ? { status: 'INACTIVE' as never } : {}), ...(q.status ? { status: q.status as never } : {}), ...(q.search ? { OR: [{ name: { contains: q.search, mode: 'insensitive' } }, { phoneNumber: { contains: q.search } }, { displayPhoneNumber: { contains: q.search } }, { verifiedName: { contains: q.search, mode: 'insensitive' } }, { wabaId: { contains: q.search } }, { businessAccountId: { contains: q.search } }, { phoneNumberId: { contains: q.search } }] } : {}) }; const [items,total] = await this.prisma.$transaction([this.prisma.whatsappAccount.findMany({ where, select: selectAccount, orderBy: [{ isDefault: 'desc' }, { createdAt: 'desc' }, { id: 'asc' }], skip: (page-1)*pageSize, take: pageSize }), this.prisma.whatsappAccount.count({ where })]); return { items, page, pageSize, total, totalPages: Math.max(1, Math.ceil(total/pageSize)) }; }
  async getAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); return this.accountInOrg(id, this.scope(ctx)); }
  async createAccount(d: CreateWhatsappAccountDto, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const phoneNumber=d.phoneNumber?.trim()||''; const phoneDigits=phoneNumber.replace(/\D/g,''); const normalizedPhone=phoneDigits?`+${phoneDigits}`:''; const phoneNumberId = d.phoneNumberId.trim(); const wabaId = d.wabaId.trim(); const businessAccountId = d.businessAccountId?.trim() || wabaId; const verifyToken=(d.verifyToken || randomVerifyToken()).trim(); const dup = await this.prisma.whatsappAccount.findFirst({ where: { organizationId: org, deletedAt: null, OR: [{ phoneNumberId }, { wabaId }, ...(normalizedPhone?[{normalizedPhone}]:[])] } }); if (dup) throw new BadRequestException('WHATSAPP_ACCOUNT_DUPLICATE_PHONE'); const data = { organizationId: org, name: d.name.trim(), phoneNumber, normalizedPhone, provider: 'META_CLOUD' as never, phoneNumberId, wabaId, businessAccountId, appId: d.appId?.trim(), apiVersion: d.apiVersion?.trim(), accessToken: this.crypto.encrypt(d.accessToken.trim()), tokenLast4: d.accessToken.trim().slice(-4), verifyToken: this.crypto.encrypt(verifyToken), verifyTokenHash:createHash('sha256').update(verifyToken).digest('hex'), appSecret: d.appSecret ? this.crypto.encrypt(d.appSecret) : undefined, webhookSecret: d.webhookSecret ? this.crypto.encrypt(d.webhookSecret) : undefined, status: (d.status || (d.active === false ? 'INACTIVE' : 'PENDING')) as never, createdByUserId: ctx.id }; const created = await this.prisma.whatsappAccount.create({ data, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.created', 'WhatsappAccount', created.id, ctx.id, null, created); return created; }
  async createManualAccount(d: CreateManualWhatsappAccountDto, user: AuthenticatedUserRef) {
    const ctx = await this.access.resolve(user);
    if (!ctx.roles.includes('GLOBAL_ADMIN')) throw new ForbiddenException('WHATSAPP_MANUAL_ACCOUNT_GLOBAL_ADMIN_ONLY');
    const organizationId = d.organizationId.trim();
    const organization = await this.prisma.organization.findFirst({ where: { id: organizationId, deletedAt: null, active: true }, select: { id: true } });
    if (!organization) throw new NotFoundException('WHATSAPP_ORGANIZATION_NOT_FOUND');
    const phoneNumberId = d.phoneNumberId.trim(), wabaId = d.wabaId.trim();
    const businessAccountId = d.businessAccountId?.trim() || wabaId;
    const accessToken = d.accessToken.trim();
    let connection;
    try {
      connection = await this.meta.testConnection({ accessToken, phoneNumberId, wabaId, businessAccountId, apiVersion: d.apiVersion?.trim() });
    } catch (error) {
      throw new BadRequestException({ code: this.connectionErrorCode(error, 'WHATSAPP_META_CONNECTION_FAILED'), message: sanitizeError(error, [accessToken]) });
    }
    const normalizedPhone = connection.displayPhoneNumber ? this.normalizePhone(connection.displayPhoneNumber) : '';
    const verifyToken = randomVerifyToken();
    const now = new Date();
    let created;
    try {
      created = await this.prisma.$transaction(async tx => {
        // PostgreSQL transaction-scoped locks close the find/create race without changing the schema.
        await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtext(${`whatsapp:phone:${phoneNumberId}`}))`);
        await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtext(${`whatsapp:waba:${wabaId}`}))`);
        await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtext(${`whatsapp:default:${organizationId}`}))`);
        const duplicate = await tx.whatsappAccount.findFirst({ where: { deletedAt: null, OR: [{ phoneNumberId }, { wabaId }, ...(normalizedPhone ? [{ normalizedPhone }] : [])] }, select: { organizationId: true } });
        if (duplicate) throw new BadRequestException(duplicate.organizationId === organizationId ? 'WHATSAPP_ACCOUNT_DUPLICATE_PHONE' : 'WHATSAPP_ACCOUNT_ALREADY_LINKED');
        const shouldBeDefault = d.isDefault === true || await tx.whatsappAccount.count({ where: { organizationId, deletedAt: null } }) === 0;
        if (shouldBeDefault) await tx.whatsappAccount.updateMany({ where: { organizationId, deletedAt: null, isDefault: true }, data: { isDefault: false } });
        return tx.whatsappAccount.create({ data: { organizationId, name: d.name.trim(), provider: 'META_CLOUD' as never, wabaId, phoneNumberId, businessAccountId, phoneNumber: connection.displayPhoneNumber || '', normalizedPhone, displayPhoneNumber: connection.displayPhoneNumber, verifiedName: connection.verifiedName, qualityRating: connection.qualityRating, apiVersion: d.apiVersion?.trim(), accessToken: this.crypto.encrypt(accessToken), tokenLast4: accessToken.slice(-4), verifyToken: this.crypto.encrypt(verifyToken), verifyTokenHash: createHash('sha256').update(verifyToken).digest('hex'), status: 'ACTIVE' as never, isDefault: shouldBeDefault, connectedAt: now, lastConnectionTestAt: now, createdByUserId: ctx.id }, select: selectAccount });
      });
    } catch (error) {
      if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new BadRequestException('WHATSAPP_ACCOUNT_ALREADY_LINKED');
      throw error;
    }
    await this.auditSafe(organizationId, 'whatsapp.account.manual_created', 'WhatsappAccount', created.id, ctx.id, null, created);
    return created;
  }
  async updateAccount(id: string, d: UpdateWhatsappAccountDto, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const cur = await this.accountInOrg(id, org, true); const phoneDigits=d.phoneNumber?.replace(/\D/g,''); const normalizedPhone=d.phoneNumber===undefined?undefined:phoneDigits?`+${phoneDigits}`:''; if (normalizedPhone && normalizedPhone !== cur.normalizedPhone) { const dup = await this.prisma.whatsappAccount.findFirst({ where: { organizationId: org, normalizedPhone, deletedAt: null, id: { not: id } } }); if (dup) throw new BadRequestException('WHATSAPP_ACCOUNT_DUPLICATE_PHONE'); } const updated = await this.prisma.whatsappAccount.update({ where: { id }, data: { name: d.name?.trim(), phoneNumber: d.phoneNumber, normalizedPhone, phoneNumberId: d.phoneNumberId?.trim(), wabaId: d.wabaId?.trim(), businessAccountId: d.businessAccountId?.trim(), appId: d.appId?.trim(), apiVersion: d.apiVersion?.trim(), status: d.status as never, accessToken: d.accessToken ? this.crypto.encrypt(d.accessToken) : undefined, tokenLast4: d.accessToken ? d.accessToken.slice(-4) : undefined, verifyToken: d.verifyToken ? this.crypto.encrypt(d.verifyToken) : undefined, verifyTokenHash:d.verifyToken?createHash('sha256').update(d.verifyToken).digest('hex'):undefined, appSecret: d.appSecret ? this.crypto.encrypt(d.appSecret) : undefined, webhookSecret: d.webhookSecret ? this.crypto.encrypt(d.webhookSecret) : undefined }, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.updated', 'WhatsappAccount', id, ctx.id, cur, updated); return updated; }
  async archiveAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const cur = await this.accountInOrg(id, org); const activeCampaign = await this.prisma.campaign.findFirst({ where: { organizationId: org, whatsappAccountId: id, deletedAt: null, archivedAt: null, status: { in: ['RUNNING', 'SCHEDULED'] as never } } }); if (activeCampaign) throw new BadRequestException('WHATSAPP_ACCOUNT_HAS_ACTIVE_CAMPAIGN'); await this.prisma.whatsappAccount.update({ where: { id }, data: { deletedAt: new Date(), status: 'DISCONNECTED' as never, isDefault: false } }); await this.auditSafe(org, 'whatsapp.account.archived', 'WhatsappAccount', id, ctx.id, cur, { id, deletedAt: true }); return { success: true }; }
  async restoreAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const cur = await this.prisma.whatsappAccount.findFirst({ where: { id, organizationId: org } }); if (!cur) throw new NotFoundException('Conta WhatsApp não encontrada'); const dup = await this.prisma.whatsappAccount.findFirst({ where: { organizationId: org, deletedAt: null, id: { not: id }, OR: [{ phoneNumberId: cur.phoneNumberId }, { normalizedPhone: cur.normalizedPhone }] } }); if (dup) throw new BadRequestException('WHATSAPP_ACCOUNT_DUPLICATE_PHONE'); const up = await this.prisma.whatsappAccount.update({ where: { id }, data: { deletedAt: null, status: 'INACTIVE' as never, isDefault: false }, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.restored', 'WhatsappAccount', id, ctx.id, cur, up); return up; }
  async testAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const a = await this.accountInOrg(id, org, true); try { const r = await this.meta.testConnection({ accessToken: this.crypto.decrypt(a.accessToken), wabaId:a.wabaId, phoneNumberId:a.phoneNumberId, businessAccountId:a.businessAccountId, apiVersion:a.apiVersion }); const now=new Date(); const officialDigits=r.displayPhoneNumber?.replace(/\D/g,''); const up = await this.prisma.whatsappAccount.update({ where: { id }, data: { status:'ACTIVE' as never, connectedAt:a.connectedAt||now, phoneNumber:r.displayPhoneNumber||a.phoneNumber, normalizedPhone:officialDigits?`+${officialDigits}`:a.normalizedPhone, displayPhoneNumber:r.displayPhoneNumber, verifiedName:r.verifiedName, qualityRating:r.qualityRating, lastConnectionTestAt:now, lastConnectionError:null }, select:selectAccount }); await this.auditSafe(org, 'whatsapp.account.tested', 'WhatsappAccount', id, ctx.id, null, {ok:true}); return up; } catch(e) { const err=sanitizeError(e); const code=this.connectionErrorCode(e,'WHATSAPP_META_CONNECTION_FAILED'); await this.prisma.whatsappAccount.update({where:{id},data:{status:'ERROR' as never,lastConnectionTestAt:new Date(),lastConnectionError:err}}); throw new BadRequestException({code,message:err}); } }


  async updateAccountStatus(id: string, d: UpdateWhatsappAccountStatusDto, user: AuthenticatedUserRef) { if(d.status==='ACTIVE') return this.testAccount(id,user); const ctx = await this.access.resolve(user); const org = this.scope(ctx); const cur = await this.accountInOrg(id, org); const up = await this.prisma.whatsappAccount.update({ where: { id }, data: { status: d.status as never, isDefault: d.status === 'INACTIVE' ? false : undefined }, select: selectAccount }); await this.auditSafe(org, 'whatsapp.account.status_updated', 'WhatsappAccount', id, ctx.id, cur, up); return up; }
  async setDefaultAccount(id: string, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); await this.accountInOrg(id, org); const [, up] = await this.prisma.$transaction([this.prisma.whatsappAccount.updateMany({ where: { organizationId: org, deletedAt: null, isDefault: true }, data: { isDefault: false } }), this.prisma.whatsappAccount.update({ where: { id }, data: { isDefault: true, status: 'ACTIVE' as never }, select: selectAccount })]); await this.auditSafe(org, 'whatsapp.account.default_set', 'WhatsappAccount', id, ctx.id, null, { id }); return up; }
  async syncAccount(id: string, user: AuthenticatedUserRef) { const ctx=await this.access.resolve(user); const org=this.scope(ctx); const a=await this.accountInOrg(id,org,true); try { const r=await this.meta.syncAccount({accessToken:this.crypto.decrypt(a.accessToken),wabaId:a.wabaId,phoneNumberId:a.phoneNumberId,businessAccountId:a.businessAccountId,apiVersion:a.apiVersion}); const now=new Date(); const officialDigits=r.displayPhoneNumber?.replace(/\D/g,''); const up=await this.prisma.whatsappAccount.update({where:{id},data:{phoneNumber:r.displayPhoneNumber||a.phoneNumber,normalizedPhone:officialDigits?`+${officialDigits}`:a.normalizedPhone,displayPhoneNumber:r.displayPhoneNumber,verifiedName:r.verifiedName,qualityRating:r.qualityRating,status:'ACTIVE' as never,connectedAt:a.connectedAt||now,lastSyncAt:now,lastConnectionTestAt:now,lastConnectionError:null},select:selectAccount}); await this.auditSafe(org,'whatsapp.account.synced','WhatsappAccount',id,ctx.id,null,{id}); return up; } catch(e) { const err=sanitizeError(e); const code=this.connectionErrorCode(e,'WHATSAPP_META_SYNC_FAILED'); const up=await this.prisma.whatsappAccount.update({where:{id},data:{status:'ERROR' as never,lastConnectionTestAt:new Date(),lastConnectionError:err},select:selectAccount}); throw new BadRequestException({code,message:err,account:up}); } }
  private connectionErrorCode(error:unknown,fallback:string){ const code=error&&typeof error==='object'&&'code' in error?String((error as {code:unknown}).code):fallback; return ['WHATSAPP_PHONE_NOT_FOUND_IN_WABA','WHATSAPP_INVALID_ACCESS_TOKEN','WHATSAPP_INSUFFICIENT_PERMISSION','WHATSAPP_WABA_NOT_OWNED_BY_BUSINESS'].includes(code)?code:fallback; }

  async listConversations(q: ListWhatsappDto, user: AuthenticatedUserRef) { const ctx = await this.access.resolve(user); const org = this.scope(ctx); const page=q.page??1, limit=q.limit??20; const brokerOnly = ctx.role === Role.BROKER && !ctx.permissions.includes('whatsapp:conversations:read-all'); const where:any = { organizationId: org, deletedAt: null, ...(q.status ? { status: q.status } : {}), ...(brokerOnly ? { assignedUserId: ctx.id } : {}) }; const [items,total] = await this.prisma.$transaction([this.prisma.whatsappConversation.findMany({ where, orderBy:{ lastMessageAt:'desc'}, skip:(page-1)*limit, take:limit }), this.prisma.whatsappConversation.count({ where })]); return { items, meta:{total,page,limit,totalPages:Math.max(1,Math.ceil(total/limit))} }; }
  async getConversation(id:string,user:AuthenticatedUserRef){ const ctx=await this.access.resolve(user); const org=this.scope(ctx); const c=await this.prisma.whatsappConversation.findFirst({where:{id,organizationId:org,deletedAt:null}}); if(!c) throw new NotFoundException('Conversa não encontrada'); if(ctx.role===Role.BROKER && c.assignedUserId!==ctx.id && !ctx.permissions.includes('whatsapp:conversations:read-all')) throw new ForbiddenException('WHATSAPP_CONVERSATION_FORBIDDEN'); return c; }
  async updateConversation(id:string,d:UpdateConversationDto,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); return this.prisma.whatsappConversation.update({where:{id},data:{status:d.status as never,contactName:d.contactName}}); }
  async assignConversation(id:string,d:AssignConversationDto,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); if(d.assignedUserId) await this.ensureUser(c.organizationId,d.assignedUserId); if(d.managerUserId) await this.ensureUser(c.organizationId,d.managerUserId); const up=await this.prisma.whatsappConversation.update({where:{id},data:{assignedUserId:d.assignedUserId??null,managerUserId:d.managerUserId??null}}); await this.auditSafe(c.organizationId,'whatsapp.conversation.assigned','WhatsappConversation',id,user.id,c,up); return up; }
  async closeConversation(id:string,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); const up=await this.prisma.whatsappConversation.update({where:{id},data:{status:'CLOSED' as never,unreadCount:0}}); await this.auditSafe(c.organizationId,'whatsapp.conversation.closed','WhatsappConversation',id,user.id,c,up); return up; }
  async reopenConversation(id:string,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); const up=await this.prisma.whatsappConversation.update({where:{id},data:{status:'OPEN' as never}}); await this.auditSafe(c.organizationId,'whatsapp.conversation.reopened','WhatsappConversation',id,user.id,c,up); return up; }
  async messages(id:string,q:ListWhatsappDto,user:AuthenticatedUserRef){ const c=await this.getConversation(id,user); const page=q.page??1, limit=q.limit??20; return this.prisma.whatsappMessage.findMany({where:{organizationId:c.organizationId,conversationId:id},orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit}); }
  async sendText(id:string,d:SendTextMessageDto,user:AuthenticatedUserRef){ const c:any=await this.getConversation(id,user); if(!this.windowPolicy.canSendFreeMessage(c.customerServiceWindowEndsAt)) throw new BadRequestException('WHATSAPP_CUSTOMER_SERVICE_WINDOW_CLOSED'); return this.sendOutbound(c,d,user,'TEXT'); }
  async sendMedia(id:string,d:SendMediaMessageDto,user:AuthenticatedUserRef){ const c:any=await this.getConversation(id,user); if(!this.windowPolicy.canSendFreeMessage(c.customerServiceWindowEndsAt)) throw new BadRequestException('WHATSAPP_CUSTOMER_SERVICE_WINDOW_CLOSED'); return this.sendOutbound(c,d,user,'MEDIA'); }
  async sendTemplate(id:string,d:SendTemplateMessageDto,user:AuthenticatedUserRef){ const c:any=await this.getConversation(id,user); const t:any=await this.prisma.whatsappTemplate.findFirst({where:{id:d.templateId,organizationId:c.organizationId,whatsappAccountId:c.whatsappAccountId,deletedAt:null}}); if(!t||t.status!=='APPROVED') throw new BadRequestException('WHATSAPP_TEMPLATE_NOT_APPROVED'); return this.sendOutbound(c,{...d,template:t},user,'TEMPLATE'); }
  private async sendOutbound(c:any,d:any,user:AuthenticatedUserRef,kind:'TEXT'|'TEMPLATE'|'MEDIA'){ const a:any=await this.accountInOrg(c.whatsappAccountId,c.organizationId,true); const msg=await this.prisma.whatsappMessage.create({data:{organizationId:c.organizationId,whatsappAccountId:a.id,conversationId:c.id,leadId:c.leadId,direction:'OUTBOUND' as never,type:(kind==='MEDIA'?d.type.toUpperCase():kind) as never,status:'PENDING' as never,senderPhone:a.normalizedPhone,recipientPhone:c.normalizedPhone,text:d.text,mediaId:d.mediaId,templateName:d.template?.name,templateLanguage:d.template?.language,replyToExternalMessageId:d.replyToExternalMessageId,createdByUserId:user.id}}); try{ const accessToken=this.crypto.decrypt(a.accessToken); const r=kind==='TEXT'?await this.meta.sendText({accessToken,phoneNumberId:a.phoneNumberId,to:c.normalizedPhone.replace('+',''),text:d.text,replyToExternalMessageId:d.replyToExternalMessageId}):kind==='TEMPLATE'?await this.meta.sendTemplate({accessToken,phoneNumberId:a.phoneNumberId,to:c.normalizedPhone.replace('+',''),name:d.template.name,language:d.template.language,components:d.components}):await this.meta.sendMedia({accessToken,phoneNumberId:a.phoneNumberId,to:c.normalizedPhone.replace('+',''),type:d.type,mediaId:d.mediaId,caption:d.caption}); const up=await this.prisma.whatsappMessage.update({where:{id:msg.id},data:{externalMessageId:r.externalMessageId,status:'SENT' as never,sentAt:new Date()}}); await this.prisma.whatsappConversation.update({where:{id:c.id},data:{lastMessageAt:new Date(),lastOutboundAt:new Date()}}); await this.auditSafe(c.organizationId,'whatsapp.message.sent','WhatsappMessage',msg.id,user.id,null,{id:msg.id,status:'SENT'}); return up; }catch(e){ const err=sanitizeError(e); await this.prisma.whatsappMessage.update({where:{id:msg.id},data:{status:'FAILED' as never,errorMessage:err,failedAt:new Date()}}); await this.auditSafe(c.organizationId,'whatsapp.message.failed','WhatsappMessage',msg.id,user.id,null,{id:msg.id,errorMessage:err}); throw new BadRequestException({code:'WHATSAPP_META_SEND_FAILED',message:err}); }}

  async findTemplates(q: ListWhatsappTemplatesDto, user: AuthenticatedUserRef) { const ctx=await this.access.resolve(user); const org=this.scope(ctx); const page=Math.max(1,q.page??1), pageSize=Math.min(100,q.pageSize??q.limit??20); const includeArchived=q.state==='archived'||q.state==='all'||q.archived==='true'; const where: Prisma.WhatsappTemplateWhereInput={ organizationId:org, ...(includeArchived?{}:{deletedAt:null,archivedAt:null}), ...(q.state==='archived'?{ OR:[{deletedAt:{not:null}},{archivedAt:{not:null}}] }:{}) , ...(q.state==='active'?{isActive:true}:{}) , ...(q.state==='inactive'?{isActive:false}:{}) , ...(q.whatsappAccountId?{whatsappAccountId:q.whatsappAccountId}:{}), ...(q.status?{status:q.status as never}:{}), ...(q.category?{category:q.category}:{}), ...(q.language?{language:q.language}:{}), ...(q.search?{OR:[{name:{contains:q.search,mode:'insensitive'}},{displayName:{contains:q.search,mode:'insensitive'}},{metaName:{contains:q.search,mode:'insensitive'}},{body:{contains:q.search,mode:'insensitive'}}]}:{}) }; const accountSelect={id:true,name:true,displayPhoneNumber:true,provider:true,status:true,lastSyncAt:true}; const [rows,total]=await this.prisma.$transaction([this.prisma.whatsappTemplate.findMany({where,include:{whatsappAccount:{select:accountSelect}},orderBy:{updatedAt:'desc'},skip:(page-1)*pageSize,take:pageSize}),this.prisma.whatsappTemplate.count({where})]); const items=rows.map(toSafeTemplate); const selectedAccount=q.whatsappAccountId?await this.prisma.whatsappAccount.findFirst({where:{id:q.whatsappAccountId,organizationId:org},select:{id:true,lastSyncAt:true}}):null; return {items,page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize)),lastSyncedAt:selectedAccount?.lastSyncAt??null}; }
  async getTemplate(id:string,user:AuthenticatedUserRef, withDeleted=false){ const ctx=await this.access.resolve(user); const t=await this.prisma.whatsappTemplate.findFirst({where:{id,organizationId:this.scope(ctx),...(withDeleted?{}:{deletedAt:null})},include:{whatsappAccount:{select:{id:true,name:true,displayPhoneNumber:true,provider:true,status:true,lastSyncAt:true}}}}); if(!t) throw new NotFoundException('Template não encontrado'); return toSafeTemplate(t); }
  async createTemplate(d:CreateWhatsappTemplateDto,user:AuthenticatedUserRef){ const ctx=await this.access.resolve(user); const org=this.scope(ctx); await this.validateTemplateAccount(org,d.whatsappAccountId); this.validateTemplate(d.name,d.metaName,d.body,d.headerType,d.headerText); const created=await this.prisma.whatsappTemplate.create({data:{organizationId:org,whatsappAccountId:d.whatsappAccountId||null,name:d.name.trim(),displayName:d.displayName.trim(),metaName:d.metaName.trim(),language:d.language,category:d.category,status:(d.status||'DRAFT') as never,headerType:d.headerType||'NONE',headerText:d.headerText?.trim()||null,body:d.body.trim(),footer:d.footer?.trim()||null,buttons:(d.buttons??[]) as Prisma.InputJsonValue,components:this.toComponents(d) as Prisma.InputJsonValue,externalTemplateId:d.metaTemplateId?.trim()||null,metaTemplateId:d.metaTemplateId?.trim()||null,isActive:d.isActive??true}}); await this.auditSafe(org,'whatsapp.template.created','WhatsappTemplate',created.id,ctx.id,null,created); return created; }
  async updateTemplate(id:string,d:UpdateWhatsappTemplateDto,user:AuthenticatedUserRef){ const ctx=await this.access.resolve(user); const org=this.scope(ctx); const cur=await this.getTemplate(id,user); await this.validateTemplateAccount(org,d.whatsappAccountId===undefined?undefined:d.whatsappAccountId||undefined); this.validateTemplate(d.name??cur.name,d.metaName??(cur as any).metaName,d.body??(cur as any).body,d.headerType??(cur as any).headerType,d.headerText===undefined?(cur as any).headerText:d.headerText||undefined); const merged={headerType:d.headerType??(cur as any).headerType,headerText:d.headerText===undefined?(cur as any).headerText:d.headerText,body:d.body??(cur as any).body,footer:d.footer===undefined?(cur as any).footer:d.footer,buttons:d.buttons===undefined?(cur as any).buttons:d.buttons}; const up=await this.prisma.whatsappTemplate.update({where:{id},data:{whatsappAccountId:d.whatsappAccountId===undefined?undefined:d.whatsappAccountId||null,name:d.name?.trim(),displayName:d.displayName?.trim(),metaName:d.metaName?.trim(),language:d.language,category:d.category,status:d.status as never,headerType:d.headerType,headerText:d.headerText===undefined?undefined:d.headerText?.trim()||null,body:d.body?.trim(),footer:d.footer===undefined?undefined:d.footer?.trim()||null,buttons:d.buttons===undefined?undefined:d.buttons as Prisma.InputJsonValue,components:this.toComponents(merged) as Prisma.InputJsonValue,externalTemplateId:d.metaTemplateId===undefined?undefined:d.metaTemplateId?.trim()||null,metaTemplateId:d.metaTemplateId===undefined?undefined:d.metaTemplateId?.trim()||null,isActive:d.isActive}}); await this.auditSafe(org,'whatsapp.template.updated','WhatsappTemplate',id,ctx.id,cur,up); return up; }
  async archiveTemplate(id:string,user:AuthenticatedUserRef){ const ctx=await this.access.resolve(user); const cur=await this.getTemplate(id,user); const up=await this.prisma.whatsappTemplate.update({where:{id},data:{archivedAt:new Date(),isActive:false}}); await this.auditSafe(cur.organizationId,'whatsapp.template.archived','WhatsappTemplate',id,ctx.id,cur,up); return up; }
  async restoreTemplate(id:string,user:AuthenticatedUserRef){ const ctx=await this.access.resolve(user); const org=this.scope(ctx); const cur=await this.prisma.whatsappTemplate.findFirst({where:{id,organizationId:org,OR:[{deletedAt:{not:null}},{archivedAt:{not:null}}]}}); if(!cur) throw new NotFoundException('Template arquivado não encontrado'); const up=await this.prisma.whatsappTemplate.update({where:{id},data:{deletedAt:null,archivedAt:null,isActive:true}}); await this.auditSafe(org,'whatsapp.template.restored','WhatsappTemplate',id,ctx.id,cur,up); return up; }
  async deleteTemplate(id:string,user:AuthenticatedUserRef){ const ctx=await this.access.resolve(user); const cur=await this.getTemplate(id,user); await this.prisma.whatsappTemplate.update({where:{id},data:{deletedAt:new Date(),isActive:false}}); await this.auditSafe(cur.organizationId,'whatsapp.template.deleted','WhatsappTemplate',id,ctx.id,cur,{id,deletedAt:true}); return {success:true}; }
  async syncTemplates(d: SyncWhatsappTemplatesDto, user: AuthenticatedUserRef) {
    const ctx=await this.access.resolve(user); const org=this.scope(ctx); const a:any=await this.accountInOrg(d.whatsappAccountId,org,true);
    if(a.provider!=='META_CLOUD') throw new BadRequestException('WHATSAPP_TEMPLATE_SYNC_META_ONLY');
    const now=new Date(); const summary={totalFound:0,created:0,updated:0,unchanged:0,archived:0,errors:[] as string[]};
    try {
      const templates=await this.meta.syncTemplates({accessToken:this.crypto.decrypt(a.accessToken),businessAccountId:a.wabaId,apiVersion:a.apiVersion}); summary.totalFound=templates.length; const seen:string[]=[];
      for(const t of templates) { try { const metaId=t.id?.trim()||null; const existing:any=await this.prisma.whatsappTemplate.findFirst({where:{organizationId:org,whatsappAccountId:a.id,OR:[...(metaId?[{metaTemplateId:metaId}]:[]),{name:t.name,language:t.language}]}}); const status=this.mapTemplateStatus(t.status); const parsed=parseMetaTemplateComponents(t.components); const quality=typeof t.quality_score==='object'?JSON.stringify(t.quality_score):t.quality_score?String(t.quality_score):null; const values:any={externalTemplateId:metaId,metaTemplateId:metaId,displayName:t.name,metaName:t.name,name:t.name,language:t.language,category:t.category,status:status.internal,metaStatus:status.raw,qualityScore:quality,rejectionReason:t.rejected_reason?.slice(0,500)||null,parameterFormat:t.parameter_format||null,previousCategory:t.previous_category||null,createdAtMeta:t.created_time?new Date(t.created_time):null,components:parsed.components,headerType:parsed.headerType,headerText:parsed.headerText,body:parsed.body,footer:parsed.footer,buttons:parsed.buttons,archivedAt:null,deletedAt:null,isActive:status.internal==='APPROVED',lastSyncedAt:now};
        if(existing){ const keys=Object.keys(values).filter(k=>k!=='lastSyncedAt'); const comparable=(o:any)=>JSON.stringify(Object.fromEntries(keys.map(k=>[k,o[k] instanceof Date?o[k].toISOString():o[k]]))); if(comparable(existing)===comparable(values)){await this.prisma.whatsappTemplate.update({where:{id:existing.id},data:{lastSyncedAt:now}});summary.unchanged++;}else{await this.prisma.whatsappTemplate.update({where:{id:existing.id},data:values});summary.updated++;} seen.push(existing.id);
        } else { const created=await this.prisma.whatsappTemplate.create({data:{organizationId:org,whatsappAccountId:a.id,...values}}); seen.push(created.id); summary.created++; }
      } catch(error){summary.errors.push(sanitizeError(error));} }
      const archived=await this.prisma.whatsappTemplate.updateMany({where:{organizationId:org,whatsappAccountId:a.id,deletedAt:null,archivedAt:null,...(seen.length?{id:{notIn:seen}}:{})},data:{archivedAt:now,isActive:false,lastSyncedAt:now}}); summary.archived=archived.count;
      await this.prisma.whatsappAccount.update({where:{id:a.id},data:{lastSyncAt:now}}); await this.auditSafe(org,'whatsapp.templates.synced','WhatsappAccount',a.id,ctx.id,null,summary); return summary;
    } catch(error) { throw new BadRequestException({code:'WHATSAPP_META_TEMPLATE_SYNC_FAILED',message:sanitizeError(error)}); }
  }
  private mapTemplateStatus(status?: string) { const raw=String(status||'UNKNOWN').toUpperCase().slice(0,64); const known=['PENDING','APPROVED','REJECTED','PAUSED','DISABLED','IN_APPEAL','PENDING_DELETION','DELETED','LIMIT_EXCEEDED','DRAFT']; return {internal:known.includes(raw)?raw:'UNKNOWN',raw}; }
  private async validateTemplateAccount(org:string,accountId?:string){ if(!accountId) return; const account=await this.prisma.whatsappAccount.findFirst({where:{id:accountId,organizationId:org,deletedAt:null}}); if(!account) throw new BadRequestException('WHATSAPP_TEMPLATE_ACCOUNT_INVALID'); }
  private validateTemplate(name:string,metaName:string,body:string,headerType?:string,headerText?:string|null){ if(!name?.trim()) throw new BadRequestException('Nome interno é obrigatório'); if(!/^[a-z0-9_]+$/.test(metaName?.trim()||'')) throw new BadRequestException('Nome Meta deve usar apenas letras minúsculas, números e _'); if(!body?.trim()) throw new BadRequestException('Body do template é obrigatório'); if(headerType==='TEXT'&&!headerText?.trim()) throw new BadRequestException('Header de texto exige conteúdo'); }
  private toComponents(d:any){ const components:any[]=[]; if(d.headerType==='TEXT'&&d.headerText) components.push({type:'HEADER',format:'TEXT',text:d.headerText}); components.push({type:'BODY',text:d.body}); if(d.footer) components.push({type:'FOOTER',text:d.footer}); if(d.buttons?.length) components.push({type:'BUTTONS',buttons:d.buttons}); return components; }

  async verifyWebhook(mode?: string, verifyToken?: string, challenge?: string) { if (mode !== 'subscribe' || !verifyToken || !challenge) throw new BadRequestException('WHATSAPP_WEBHOOK_VERIFY_INVALID'); const verifyTokenHash=createHash('sha256').update(verifyToken).digest('hex'); let found:any=await this.prisma.whatsappAccount.findFirst({where:{verifyTokenHash,provider:'META_CLOUD' as never,deletedAt:null}}); if(!found){ const legacy:any[]=await this.prisma.whatsappAccount.findMany({where:{verifyTokenHash:null,provider:'META_CLOUD' as never,deletedAt:null}}); found=legacy.find(account=>this.safeSecretEquals(this.crypto.decrypt(account.verifyToken),verifyToken)); if(found) await this.prisma.whatsappAccount.update({where:{id:found.id},data:{verifyTokenHash}}); } if(!found||!this.safeSecretEquals(this.crypto.decrypt(found.verifyToken),verifyToken)) throw new UnauthorizedException('WHATSAPP_WEBHOOK_VERIFY_TOKEN_INVALID'); return challenge; }
  private safeSecretEquals(left:string,right:string){ const a=Buffer.from(left),b=Buffer.from(right); return a.length===b.length&&timingSafeEqual(a,b); }
  validateSignature(raw: Buffer, signature: string|undefined, appSecret: string|undefined){ if(!appSecret||!signature?.startsWith('sha256=')) throw new UnauthorizedException('WHATSAPP_WEBHOOK_SIGNATURE_INVALID'); const expected=Buffer.from('sha256='+createHmac('sha256',appSecret).update(raw).digest('hex')); const received=Buffer.from(signature); if(expected.length!==received.length||!timingSafeEqual(expected,received)) throw new UnauthorizedException('WHATSAPP_WEBHOOK_SIGNATURE_INVALID'); }
  private async webhookAccount(phoneNumberId?:string, wabaId?:string){ if(phoneNumberId){ const account:any=await this.prisma.whatsappAccount.findFirst({where:{provider:'META_CLOUD' as never,deletedAt:null,phoneNumberId}}); return account&&wabaId&&account.wabaId!==wabaId?null:account; } if(!wabaId) return null; const accounts:any[]=await this.prisma.whatsappAccount.findMany({where:{provider:'META_CLOUD' as never,deletedAt:null,wabaId},take:2}); return accounts.length===1?accounts[0]:null; }
  async receiveWebhook(payload:any, raw:Buffer, signature?:string){ if(payload?.object!=='whatsapp_business_account'||!Array.isArray(payload.entry)) throw new BadRequestException('WHATSAPP_WEBHOOK_PAYLOAD_INVALID'); const changes=payload.entry.flatMap((e:any)=>e.changes||[]); for(const change of changes){ const value=change.value||{}; const phoneNumberId=value.metadata?.phone_number_id; const entryWabaId=payload.entry.find((entry:any)=>(entry.changes||[]).includes(change))?.id; const account:any=await this.webhookAccount(phoneNumberId,entryWabaId); if(!account) continue; this.validateSignature(raw,signature,account.appSecret?this.crypto.decrypt(account.appSecret):undefined); const key=createHash('sha256').update(raw).update(account.id).update(change.field||'unknown').digest('hex'); const event=await this.createEvent(account,change.field||'unknown',key,undefined,{object:payload.object,entry:[{id:entryWabaId,changes:[change]}]},entryWabaId,phoneNumberId); if(event) setImmediate(()=>{void this.processValue(account,value).catch(async error=>{ await this.prisma.whatsappWebhookEvent.update({where:{id:event.id},data:{status:'FAILED' as never,errorMessage:sanitizeError(error)}}).catch(()=>undefined); });}); } return {success:true}; }
  private async processValue(account:any,value:any){ for(const m of value.messages||[]) await this.processInbound(account,value,m); for(const s of value.statuses||[]) await this.processStatus(account,s); if(value.message_template_id||value.template_id) await this.processTemplateUpdate(account,value); }
  private async processTemplateUpdate(account:any,value:any){
    const metaTemplateId=String(value.message_template_id||value.template_id); const rawStatus=value.event||value.status; const mapped=rawStatus?this.mapTemplateStatus(rawStatus):null; const key=`template:${metaTemplateId}:${rawStatus||''}:${value.category||''}:${value.timestamp||''}`;
    const ev=await this.createEvent(account,'message_template_status_update',key,metaTemplateId,{message_template_id:metaTemplateId,event:rawStatus,category:value.category,previous_category:value.previous_category,reason:value.reason,quality_score:value.quality_score}); if(!ev)return;
    const template:any=await this.prisma.whatsappTemplate.findFirst({where:{organizationId:account.organizationId,whatsappAccountId:account.id,metaTemplateId}});
    if(!template){ await this.prisma.whatsappWebhookEvent.update({where:{id:ev.id},data:{errorMessage:'WHATSAPP_TEMPLATE_SYNC_REQUIRED'}}); return; }
    await this.prisma.whatsappTemplate.update({where:{id:template.id},data:{status:mapped?.internal as never,metaStatus:mapped?.raw,category:value.category||undefined,previousCategory:value.previous_category||template.category,rejectionReason:value.reason?.slice(0,500)||undefined,qualityScore:value.quality_score?String(value.quality_score).slice(0,64):undefined,isActive:mapped?mapped.internal==='APPROVED':undefined,webhookUpdatedAt:new Date()}});
    await this.prisma.whatsappWebhookEvent.update({where:{id:ev.id},data:{status:'PROCESSED' as never,processedAt:new Date()}});
  }
  private async createEvent(account:any,type:string,key:string,externalMessageId?:string,payload?:unknown,wabaId?:string,phoneNumberId?:string){ try{return await this.prisma.whatsappWebhookEvent.create({data:{organizationId:account.organizationId,whatsappAccountId:account.id,wabaId:wabaId||account.wabaId,phoneNumberId:phoneNumberId||account.phoneNumberId,eventType:type,deduplicationKey:key,externalMessageId,sanitizedPayload:redactSecrets(payload) as Prisma.InputJsonValue}});}catch(error){ if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002') return null; throw error; } }
  private async processInbound(account:any,value:any,m:any){ const key=m.id||createHash('sha256').update(JSON.stringify(m)).digest('hex'); const ev=await this.createEvent(account,'message',key,m.id,{id:m.id,type:m.type}); if(!ev) return; const phone=this.normalizePhone(m.from); const contact=value.contacts?.find((c:any)=>c.wa_id===m.from); const lead=await this.findOrCreateLead(account.organizationId,phone,contact?.profile?.name); const now=new Date(Number(m.timestamp||Date.now()/1000)*1000); const ends=this.windowPolicy.windowEndsAt(now); let conv:any=await this.prisma.whatsappConversation.findFirst({where:{whatsappAccountId:account.id,normalizedPhone:phone,deletedAt:null}}); if(conv) conv=await this.prisma.whatsappConversation.update({where:{id:conv.id},data:{leadId:lead.id,contactName:contact?.profile?.name,lastMessageAt:now,lastInboundAt:now,customerServiceWindowEndsAt:ends,status:'OPEN' as never,unreadCount:{increment:1}}}); else conv=await this.prisma.whatsappConversation.create({data:{organizationId:account.organizationId,whatsappAccountId:account.id,leadId:lead.id,contactPhone:m.from,normalizedPhone:phone,contactName:contact?.profile?.name,lastMessageAt:now,lastInboundAt:now,customerServiceWindowEndsAt:ends,unreadCount:1}}); await this.prisma.whatsappMessage.upsert({where:{organizationId_externalMessageId:{organizationId:account.organizationId,externalMessageId:m.id}},update:{},create:{organizationId:account.organizationId,whatsappAccountId:account.id,conversationId:conv.id,leadId:lead.id,externalMessageId:m.id,direction:'INBOUND' as never,type:this.mapType(m.type) as never,status:'RECEIVED' as never,senderPhone:phone,recipientPhone:account.normalizedPhone,text:m.text?.body,mediaId:m.image?.id||m.document?.id||m.audio?.id||m.video?.id,mimeType:m.image?.mime_type||m.document?.mime_type||m.audio?.mime_type||m.video?.mime_type,fileName:m.document?.filename,metadata:redactSecrets({location:m.location,interactive:m.interactive,contacts:m.contacts,unknown:m.type&&!['text','image','document','audio','video','location','interactive','contacts'].includes(m.type)?m:undefined}) as Prisma.InputJsonValue,createdAt:now}}); await this.prisma.whatsappWebhookEvent.update({where:{id:ev.id},data:{status:'PROCESSED' as never,processedAt:new Date()}}); }
  private async processStatus(account: any, s: any) {
    const key = `${s.id}:${s.status}:${s.timestamp || ''}`;
    const ev = await this.createEvent(account, 'status', key, s.id, {
      id: s.id,
      status: s.status,
      errors: s.errors,
    });
    if (!ev) return;

    const msg: any = await this.prisma.whatsappMessage.findFirst({
      where: { organizationId: account.organizationId, externalMessageId: s.id },
    });

    if (msg) {
      const status = this.mapStatus(s.status);
      const eventAt=new Date(Number(s.timestamp||Date.now()/1000)*1000);
      const failureAllowed=status==='FAILED'&&!['READ','DELIVERED'].includes(msg.status)&&(!msg.sentAt||eventAt>=msg.sentAt);
      if (status && ((status!=='FAILED'&&statusRank[status] >= statusRank[msg.status]) || failureAllowed)) {
        await this.prisma.whatsappMessage.update({
          where: { id: msg.id },
          data: {
            status: status as never,
            deliveredAt: status === 'DELIVERED' ? eventAt : undefined,
            readAt: status === 'READ' ? eventAt : undefined,
            failedAt: status === 'FAILED' ? eventAt : undefined,
            errorCode: s.errors?.[0]?.code?.toString(),
            errorMessage: s.errors?.[0]?.title?.slice(0, 500),
          },
        });
        await this.updateDistributionFromWhatsappMessage(msg, status, s.errors?.[0]?.title);
        const recipientId=msg.metadata?.recipientId;const classified=classifyMetaError(s.errors?.[0]?.title||s.errors?.[0]?.message||'Meta status failed');if(recipientId)await this.prisma.campaignRecipient.updateMany({where:{id:recipientId,organizationId:account.organizationId,externalMessageId:s.id,...(status==='DELIVERED'?{status:{in:['SENT','DELIVERED']}}:status==='READ'?{status:{in:['SENT','DELIVERED','READ']}}:status==='FAILED'?{status:{notIn:['READ','DELIVERED']}}:{})},data:{status:status==='FAILED'?(classified.retryable?'FAILED_RETRYABLE':'FAILED_PERMANENT'):status as never,deliveredAt:status==='DELIVERED'?eventAt:undefined,readAt:status==='READ'?eventAt:undefined,failedAt:status==='FAILED'?eventAt:undefined,errorCode:s.errors?.[0]?.code?.toString(),errorCategory:status==='FAILED'?classified.category:undefined,errorMessage:status==='FAILED'?classified.message:undefined,nextRetryAt:status==='FAILED'&&classified.retryable?new Date():undefined}});
      }
    }

    await this.prisma.whatsappWebhookEvent.update({
      where: { id: ev.id },
      data: { status: 'PROCESSED' as never, processedAt: new Date() },
    });
  }
  private async updateDistributionFromWhatsappMessage(msg:any,status:string,errorMessage?:string){ const distributionId=msg.metadata?.distributionId; if(!distributionId) return; await this.prisma.leadDistribution.update({where:{id:distributionId},data:{status:status==='FAILED'?'FAILED' as never:status==='DELIVERED'?'DELIVERED' as never:status==='READ'?'READ' as never:'CONTACT_SENT' as never,errorMessage:errorMessage?.slice(0,500)??null}}).catch(()=>undefined); }
  private mapType(t:string){ return ({text:'TEXT',image:'IMAGE',document:'DOCUMENT',audio:'AUDIO',video:'VIDEO',location:'LOCATION',interactive:'INTERACTIVE',contacts:'CONTACTS'} as any)[t]||'UNKNOWN'; }
  private mapStatus(s:string){ return ({sent:'SENT',delivered:'DELIVERED',read:'READ',failed:'FAILED'} as any)[s]||null; }
  private async findOrCreateLead(org:string,phone:string,name?:string){ const existing=await this.prisma.lead.findFirst({where:{organizationId:org,normalizedPhone:phone,deletedAt:null}}); if(existing) return existing; const lead=await this.prisma.lead.create({data:{organizationId:org,phone,normalizedPhone:phone,name:name||null,source:'WHATSAPP' as never,createdByUserId:null,lastInteractionAt:new Date()}}); await this.prisma.leadEvent.create({data:{organizationId:org,leadId:lead.id,eventType:'LEAD_CREATED' as never,description:'Lead criado automaticamente por mensagem WhatsApp oficial',idempotencyKey:`whatsapp-auto-lead:${org}:${phone}`,payload:{source:'WHATSAPP'}}}).catch(()=>undefined); return lead; }
  private async ensureUser(org:string,userId:string){ const u=await this.prisma.user.findFirst({where:{id:userId,organizationId:org,status:'ACTIVE',deletedAt:null}}); if(!u) throw new BadRequestException('WHATSAPP_USER_NOT_IN_ORGANIZATION'); }
}
