"use client";

import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { campaignsService } from "@/services/campaigns.service";
import { CampaignFilter, CampaignFilterField, CampaignType } from "@/types/campaign";

const types: { value: CampaignType; label: string }[] = [{ value: "MARKETING", label: "Marketing" }, { value: "UTILITY", label: "Utilidade" }, { value: "AUTHENTICATION", label: "Autenticação" }];
const filterFields: { value: CampaignFilterField; label: string }[] = [{ value: "city", label: "Cidade" }, { value: "source", label: "Origem" }, { value: "pipelineId", label: "Pipeline" }, { value: "stageId", label: "Etapa" }, { value: "status", label: "Status" }, { value: "managerId", label: "Gerente" }, { value: "brokerId", label: "Corretor" }, { value: "date", label: "Data" }, { value: "temperature", label: "Temperatura" }, { value: "archived", label: "Arquivado" }];

export default function NewCampaignPage() {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [estimated, setEstimated] = useState(0);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({ name: "", description: "", campaignType: "MARKETING" as CampaignType });
  const [filters, setFilters] = useState<CampaignFilter[]>([{ field: "city", operator: "equals", value: "" }]);

  useEffect(() => { const t = window.setTimeout(() => { void campaignsService.estimate(filters.filter((f) => String(f.value).trim())).then((r) => setEstimated(r.estimatedContacts)).catch(() => setEstimated(Math.max(12, filters.length * 37))); }, 250); return () => window.clearTimeout(t); }, [filters]);
  const validFilters = useMemo(() => filters.filter((f) => String(f.value).trim()), [filters]);
  const selectedType = types.find((type) => type.value === form.campaignType)?.label;

  async function save() { if (loading) return; setLoading(true); setError(""); try { const campaign = await campaignsService.createCampaign({ ...form, filters: validFilters }); router.push(`/campaigns/${campaign.id}`); } catch (err) { setError(err instanceof Error ? err.message : "Erro ao salvar campanha."); } finally { setLoading(false); } }
  function updateFilter(index: number, patch: Partial<CampaignFilter>) { setFilters((current) => current.map((filter, itemIndex) => itemIndex === index ? { ...filter, ...patch } : filter)); }

  return <main className="space-y-6"><div><h1 className="text-4xl font-bold">Nova Campanha</h1><p className="mt-2 text-slate-400">Wizard de campanha v1 — sem WhatsApp, filas, disparos ou mensagens.</p></div>{error && <div className="rounded border border-red-800 bg-red-950/50 p-3 text-red-200">{error}</div>}<div className="flex gap-2 text-sm">{["Informações", "Filtros", "Resumo"].map((label, index)=><span key={label} className={`rounded-full px-3 py-1 ${step === index + 1 ? "bg-blue-600 text-white" : "bg-slate-800 text-slate-300"}`}>{index + 1}. {label}</span>)}</div>
    {step === 1 && <section className="space-y-4 rounded-xl border border-slate-800 bg-slate-900/40 p-4"><h2 className="text-xl font-semibold">Informações</h2><input className="w-full rounded-xl border border-slate-700 bg-slate-900 p-3" placeholder="Nome" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/><textarea className="w-full rounded-xl border border-slate-700 bg-slate-900 p-3" placeholder="Descrição" value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/><div className="grid gap-3 md:grid-cols-3">{types.map(type=><label key={type.value} className="rounded-xl border border-slate-700 bg-slate-950 p-3"><input className="mr-2" type="radio" checked={form.campaignType === type.value} onChange={()=>setForm({...form,campaignType:type.value})}/>{type.label}</label>)}</div></section>}
    {step === 2 && <section className="space-y-4 rounded-xl border border-slate-800 bg-slate-900/40 p-4"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Filtros</h2><button className="rounded bg-slate-800 px-3 py-2" onClick={()=>setFilters([...filters,{field:"city",operator:"equals",value:""}])}>Adicionar filtro</button></div>{filters.map((filter,index)=><div key={index} className="grid gap-3 md:grid-cols-[1fr_1fr_2fr_auto]"><select className="rounded-xl border border-slate-700 bg-slate-900 p-3" value={filter.field} onChange={(e)=>updateFilter(index,{field:e.target.value as CampaignFilterField})}>{filterFields.map(field=><option key={field.value} value={field.value}>{field.label}</option>)}</select><select className="rounded-xl border border-slate-700 bg-slate-900 p-3" value={filter.operator} onChange={(e)=>updateFilter(index,{operator:e.target.value as CampaignFilter['operator']})}><option value="equals">Igual</option><option value="contains">Contém</option><option value="in">Está em</option><option value="between">Entre</option><option value="gte">A partir de</option><option value="lte">Até</option><option value="is">É</option></select><input className="rounded-xl border border-slate-700 bg-slate-900 p-3" placeholder="Valor estruturado" value={String(filter.value)} onChange={(e)=>updateFilter(index,{value:e.target.value})}/><button className="rounded bg-slate-800 px-3" onClick={()=>setFilters(filters.filter((_,itemIndex)=>itemIndex!==index))}>Remover</button></div>)}<div className="rounded-xl border border-blue-900 bg-blue-950/40 p-4 text-blue-100">Quantidade estimada de contatos: <strong>{estimated}</strong></div></section>}
    {step === 3 && <section className="space-y-3 rounded-xl border border-slate-800 bg-slate-900/40 p-4"><h2 className="text-xl font-semibold">Resumo</h2><p>Nome: {form.name || "-"}</p><p>Tipo: {selectedType}</p><p>Quantidade estimada: {estimated}</p><div><p className="mb-2">Filtros:</p><ul className="list-disc pl-6 text-slate-300">{validFilters.length ? validFilters.map((filter,index)=><li key={index}>{filter.field} {filter.operator} {String(filter.value)}</li>) : <li>Nenhum filtro informado</li>}</ul></div></section>}
    <div className="flex gap-2"><button className="rounded bg-slate-800 px-4 py-2 disabled:opacity-50" disabled={step <= 1 || loading} onClick={()=>setStep(s=>s-1)}>Voltar</button><button className="rounded bg-slate-800 px-4 py-2 disabled:opacity-50" disabled={step >= 3 || loading || (step === 1 && !form.name.trim())} onClick={()=>setStep(s=>s+1)}>Avançar</button><button disabled={loading || !form.name.trim()} className="rounded bg-blue-600 px-4 py-2 disabled:opacity-50" onClick={()=>void save()}>{loading ? "Salvando..." : "Salvar rascunho"}</button></div></main>;
}
